"""Emit runtime-health.{json,csv,md,html} from per-app records."""

from __future__ import annotations
from pathlib import Path
import csv
import json


STATE_ORDER = ("UNKNOWN", "TIMEOUT", "NEEDS-SERVICE", "CONSOLE-ERRORS", "MISSING-MOUNT", "OK")
STATE_TITLES = {
    "UNKNOWN":        "UNKNOWN — probe crashed (no observations)",
    "TIMEOUT":        "TIMEOUT — page did not reach networkidle",
    "NEEDS-SERVICE":  "NEEDS-SERVICE — UI text indicates a backend dependency",
    "CONSOLE-ERRORS": "CONSOLE-ERRORS — non-empty console.error after noise filter",
    "MISSING-MOUNT":  "MISSING-MOUNT — no primary interactive landmark",
    "OK":             "OK — loaded cleanly with a primary mount",
}


def totals(records: list[dict]) -> dict[str, int]:
    out = {s: 0 for s in STATE_ORDER}
    for r in records:
        out[r["state"]] = out.get(r["state"], 0) + 1
    out["total"] = len(records)
    return out


def render_json(records: list[dict], out_path: Path, *, audit_version: str, now_iso: str) -> None:
    payload = {
        "audit_version": audit_version,
        "generated_at": now_iso,
        "totals": totals(records),
        "apps": {r["key"]: {k: v for k, v in r.items() if k != "key"} for r in records},
    }
    out_path.write_text(json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False), encoding="utf-8")


_CSV_COLS = ("app", "state", "confidence", "load_ok", "timed_out", "load_time_ms",
             "mount_found", "n_console_errors", "n_ui_matches", "reasons")


def _csv_row(r: dict) -> dict:
    p = r.get("probe", {})
    return {
        "app": r["key"],
        "state": r["state"],
        "confidence": r["confidence"],
        "load_ok": p.get("load_ok"),
        "timed_out": p.get("timed_out"),
        "load_time_ms": p.get("load_time_ms"),
        "mount_found": p.get("mount_found"),
        "n_console_errors": len(p.get("console_errors") or []),
        "n_ui_matches": len(p.get("ui_text_matches") or []),
        "reasons": " | ".join(r.get("reasons", [])),
    }


def render_csv(records: list[dict], out_path: Path) -> None:
    with out_path.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(_CSV_COLS))
        w.writeheader()
        for r in records:
            w.writerow(_csv_row(r))


def render_md(records: list[dict], out_path: Path, *, audit_version: str, now_iso: str) -> None:
    t = totals(records)
    lines = [
        "<!-- sentinel:skip-file — generated by audit/runtime_health.py -->",
        "",
        "# allmeta runtime-health audit",
        "",
        f"Generated: {now_iso} · auditor v{audit_version} · {t['total']} apps",
        "",
        "## Summary",
        "",
    ]
    for s in STATE_ORDER:
        lines.append(f"- {STATE_TITLES[s]}: {t[s]}")
    lines.append("")
    for s in STATE_ORDER:
        bucket = sorted([r for r in records if r["state"] == s], key=lambda x: x["key"].lower())
        if not bucket:
            continue
        lines.append(f"## {STATE_TITLES[s]} ({len(bucket)})")
        lines.append("")
        for r in bucket:
            reasons = " · ".join(r.get("reasons", []))
            lines.append(f"- **{r['key']}** — {reasons}")
        lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")


_HTML_TEMPLATE = """<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<title>allmeta runtime-health audit</title>
<style>
  body{font:14px/1.45 system-ui,sans-serif;margin:1.5rem;color:#0f172a;background:#f8fafc}
  h1{margin:0 0 .25rem}
  .meta{color:#475569;margin-bottom:1rem}
  .filters{display:flex;gap:.5rem;flex-wrap:wrap;margin-bottom:1rem}
  .chip{padding:.25rem .6rem;border:1px solid #cbd5e1;border-radius:9999px;background:#fff;cursor:pointer;font-size:13px}
  .chip.is-active{background:#0f172a;color:#fff;border-color:#0f172a}
  table{border-collapse:collapse;width:100%;background:#fff;border:1px solid #e2e8f0}
  th,td{padding:.4rem .55rem;border-bottom:1px solid #e2e8f0;text-align:left;vertical-align:top;font-size:13px}
  th{cursor:pointer;background:#f1f5f9}
  td.s-UNKNOWN        {background:#e0e7ff}
  td.s-TIMEOUT        {background:#fecaca}
  td.s-NEEDS-SERVICE  {background:#fed7aa}
  td.s-CONSOLE-ERRORS {background:#fef9c3}
  td.s-MISSING-MOUNT  {background:#fde68a}
  td.s-OK             {background:#dcfce7}
  input[type=search]{padding:.4rem .6rem;border:1px solid #cbd5e1;border-radius:6px;width:280px}
</style></head><body>
<h1>allmeta runtime-health audit</h1>
<div class="meta" id="meta-line"></div>
<div class="filters">
  <input type="search" id="q" placeholder="Search app name…">
  <button class="chip is-active" data-state="all">All</button>
  <button class="chip" data-state="UNKNOWN">UNKNOWN</button>
  <button class="chip" data-state="TIMEOUT">TIMEOUT</button>
  <button class="chip" data-state="NEEDS-SERVICE">NEEDS-SERVICE</button>
  <button class="chip" data-state="CONSOLE-ERRORS">CONSOLE-ERRORS</button>
  <button class="chip" data-state="MISSING-MOUNT">MISSING-MOUNT</button>
  <button class="chip" data-state="OK">OK</button>
</div>
<table id="t">
  <thead><tr>
    <th data-k="key">App</th><th data-k="state">State</th><th data-k="confidence">Conf</th>
    <th>Reasons</th>
  </tr></thead>
  <tbody></tbody>
</table>
<script>
const DATA = __DATA__;
const tbody = document.querySelector("#t tbody");
let state = "all", q = "", sortKey = "state", sortDir = 1;
function render(){
  tbody.innerHTML = "";
  let rows = DATA.slice().filter(r => (state==="all" || r.state===state)
    && (q==="" || r.key.toLowerCase().includes(q)));
  rows.sort((a,b) => {
    const av = a[sortKey] ?? "", bv = b[sortKey] ?? "";
    if (av < bv) return -1*sortDir;
    if (av > bv) return 1*sortDir;
    return 0;
  });
  for (const r of rows){
    const tr = document.createElement("tr");
    const tdK = document.createElement("td"); tdK.textContent = r.key;
    const tdS = document.createElement("td"); tdS.textContent = r.state; tdS.className = "s-" + r.state;
    const tdC = document.createElement("td"); tdC.textContent = r.confidence;
    const tdR = document.createElement("td"); tdR.textContent = (r.reasons||[]).join(" · ");
    tr.append(tdK, tdS, tdC, tdR);
    tbody.appendChild(tr);
  }
  document.getElementById("meta-line").textContent = rows.length + " of " + DATA.length + " apps";
}
document.querySelectorAll(".chip").forEach(c => c.addEventListener("click", () => {
  document.querySelectorAll(".chip").forEach(x => x.classList.remove("is-active"));
  c.classList.add("is-active");
  state = c.dataset.state;
  render();
}));
document.getElementById("q").addEventListener("input", e => { q = e.target.value.toLowerCase(); render(); });
document.querySelectorAll("th[data-k]").forEach(h => h.addEventListener("click", () => {
  const k = h.dataset.k;
  if (sortKey === k) sortDir *= -1; else { sortKey = k; sortDir = 1; }
  render();
}));
render();
</script>
</body></html>"""


def render_html(records: list[dict], out_path: Path, *, audit_version: str, now_iso: str) -> None:
    data = [
        {
            "key": r["key"],
            "state": r["state"],
            "confidence": r["confidence"],
            "reasons": r.get("reasons", []),
        }
        for r in records
    ]
    blob = json.dumps(data, ensure_ascii=False).replace("</", "<\\/")
    html = _HTML_TEMPLATE.replace("__DATA__", blob)
    header = f"<!-- generated {now_iso} · auditor v{audit_version} -->\n"
    out_path.write_text(header + html, encoding="utf-8")
