/**
 * Full parity of shared/dose-response.js (fitDR) with dosresmeta 2.2.0 on every multi-study
 * binary dataset shipped with dosresmeta (16 datasets after dropping studies without counts):
 *   models      linear, quadratic, rcs 3/4/5 knots
 *   covariance  Greenland–Longnecker (all models), Hamling (linear, rcs3, rcs4), independent (linear, rcs3)
 *   approach    two-stage reml/ml/fixed/mm, one-stage reml/ml/fixed; two-stage meta-regression
 *               (coffee_mort ~ year, coffee_stroke ~ nordic)
 *   outputs     coefficients, vcov, Ψ, log-likelihood, Q test, Wald tests, gof(), predictions
 * A fit dosresmeta refuses (e.g. two-stage with a study that has fewer non-reference doses
 * than coefficients, or a non-positive-definite Hamling covariance) must be refused by the app.
 * Ground truth: _dr_parity_fixture.json (generated by _dr_parity_gen.R). Tolerances and
 * scales: _dr_parity_check.mjs.
 */
import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { studiesOf, optsOf, runAll, compare, tolerance } from './_dr_parity_check.mjs';
const APP = 'http://localhost:8088/dose-response-ma/index.html';
const BENIGN = /frame-ancestors|ERR_CONNECTION/;
const FIX = JSON.parse(readFileSync(new URL('./_dr_parity_fixture.json', import.meta.url), 'utf-8'));

for (const ds of FIX.datasets) {
  test(`fitDR matches dosresmeta on ${ds.dataset} (${ds.fits.length} fits)`, async ({ page }) => {
    const errs = [];
    page.on('console', (m) => { if (m.type() === 'error' && !BENIGN.test(m.text())) errs.push(m.text()); });
    await page.goto(APP, { waitUntil: 'load' });
    const st = studiesOf(ds);
    const res = await page.evaluate(runAll, ds.fits.map((f) => ({ studies: st, opts: optsOf(f), pred: f.pred })));
    const bad = [];
    ds.fits.forEach((f, i) => {
      const tag = `${f.model}/${f.covariance}/${f.proc}/${f.method}${f.mod ? '~' + f.mod : ''}`;
      if (f.ok !== res[i].ok) { bad.push(`${tag}: dosresmeta ${f.ok ? 'fits' : 'refuses'}, app ${res[i].ok ? 'fits' : 'refuses (' + res[i].error + ')'}`); return; }
      if (!f.ok) return;
      const m = compare(res[i], f), tol = tolerance(f);
      for (const k in m) if (!(m[k] <= tol[k])) bad.push(`${tag}: ${k} = ${m[k].toExponential(2)} > ${tol[k]}`);
    });
    expect(bad, 'differences beyond tolerance').toEqual([]);
    expect(errs, 'no console errors').toEqual([]);
  });
}

test('linear fit() (per-study slope + ma-core REML) matches dosresmeta on all datasets, incl. non-zero reference doses', async ({ page }) => {
  await page.goto(APP, { waitUntil: 'load' });
  const cases = FIX.datasets.map((ds) => ({ name: ds.dataset, studies: studiesOf(ds).map((s) => s.rows),
    ref: ds.fits.find((f) => f.model === 'linear' && f.covariance === 'gl' && f.proc === '2stage' && f.method === 'reml' && !f.mod) }));
  const out = await page.evaluate((cs) => cs.map((c) => { const r = window.AlmDoseResponse.fit(c.studies, { method: 'REML' }); return { slope: r.slope, se: r.se }; }), cases);
  const bad = [];
  cases.forEach((c, i) => {
    const se = Math.sqrt(c.ref.vcov[0]);
    if (!(Math.abs(out[i].slope - c.ref.coef[0]) / se < 1e-3) || !(Math.abs(out[i].se - se) / se < 1e-3)) bad.push(`${c.name}: app ${out[i].slope} (${out[i].se}) vs R ${c.ref.coef[0]} (${se})`);
  });
  expect(bad).toEqual([]);
});
