/**
 * Regression: 4-knot restricted cubic spline pooling (shared/dose-response.js → fitSpline).
 *
 * dosresmeta can fit a two-stage 4-knot spline to three of its bundled datasets
 * (alcohol_cvd, alcohol_crc, alcohol_lc). Up to allmeta 511aa72 the app's stage-2
 * multivariate REML stopped far from the optimum on all three: the per-study (stage-1)
 * coefficients matched dosresmeta, but the pooled Ψ was degenerate (e.g. alcohol_lc
 * Ψ33 ≈ 1.4e9) and its REML log-likelihood was lower than at dosresmeta's Ψ. Cause: a
 * Nelder–Mead search from a clamped moment start with a fixed 0.01 step and a 600-
 * iteration cap. The fix ports mixmeta's REML (Ψ0 = 0.001·I, 10 RIGLS iterations, then
 * BFGS with the analytic gradient and reltol = sqrt(eps)).
 *
 * Reference values: dosresmeta 2.2.0, logrr ~ rcs(dose, quantile(dose, c(.05,.35,.65,.95))),
 * method = "reml" (fixture generated by _dr_parity_gen.R).
 */
import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
const APP = 'http://localhost:8088/dose-response-ma/index.html';
const FIX = JSON.parse(readFileSync(new URL('./_dr_parity_fixture.json', import.meta.url), 'utf-8'));

const studiesOf = (ds) => {
  const by = new Map();
  for (const r of ds.rows) { if (!by.has(r.id)) by.set(r.id, []); by.get(r.id).push(r); }
  return [...by.values()];
};
const maxAbs = (a, b) => Math.max(...a.map((v, i) => Math.abs(v - b[i])));
const relDiff = (a, b) => Math.max(...a.map((v, i) => Math.abs(v - b[i]) / Math.max(1, Math.abs(b[i]))));

for (const name of ['alcohol_cvd', 'alcohol_crc', 'alcohol_lc']) {
  test(`4-knot spline pooled estimates match dosresmeta on ${name}`, async ({ page }) => {
    const ds = FIX.datasets.find((d) => d.dataset === name);
    const ref = ds.fits.find((f) => f.model === 'rcs4' && f.covariance === 'gl' && f.proc === '2stage' && f.method === 'reml' && !f.mod);
    expect(ref.ok).toBe(true);
    await page.goto(APP, { waitUntil: 'load' });
    const r = await page.evaluate((studies) => {
      const f = window.AlmDoseResponse.fitSpline(studies, { nk: 4 });
      if (!f.beta) return null;
      return { knots: f.knots, beta: f.beta, cov: [].concat(...f.cov), Psi: [].concat(...f.Psi) };
    }, studiesOf(ds));
    expect(r, 'fitSpline returned an estimate').not.toBeNull();
    expect(maxAbs(r.knots, ref.knots)).toBeLessThan(1e-9);
    // R stores matrices column-major; all three are symmetric, so the row-major flattening is identical.
    expect(relDiff(r.beta, ref.coef), 'coefficients').toBeLessThan(1e-5);
    expect(relDiff(r.cov, ref.vcov), 'vcov').toBeLessThan(1e-5);
    expect(relDiff(r.Psi, ref.Psi), 'Psi').toBeLessThan(1e-5);
  });
}
