/**
 * Full parity of shared/dta-bivariate.js with mada 0.5.12 (reitsma; mvmeta 1.0.3 underneath) on all
 * six datasets shipped with mada (AuditC, Dementia, IAQ, SAQ, skin_tests, smoking):
 *   methods     reml, ml, fixed, mm, vc
 *   correction  correction.control all / single / none (0.5); "none" with a zero cell must be refused
 *   meta-regr.  smoking ~ type, ~ population, ~ type + population (all five methods)
 *   outputs     coefficients, vcov, Ψ, log-likelihood (Jacobian-adjusted), AIC, BIC; summary
 *               sensitivity/FPR with 95% CIs, random-effects correlation, Rutter–Gatsonis parameters,
 *               AUC and partial AUC (Rutter–Gatsonis and naive SROC), SROC values, the 95% confidence
 *               and prediction regions (both directions), and the Moses–Littenberg regression (mslSROC)
 * Ground truth: _dta_parity_fixture.json (generated by _dta_parity_gen.R). Tolerances and their
 * reasons: _dta_parity_check.mjs. Up to allmeta 0f8b86d the engine fitted ML only, and drew the
 * prediction region from Ψ alone instead of Ψ + vcov as mada does.
 */
import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { jobsOf, runAll, mosesJobs, runMoses, checkDataset } from './_dta_parity_check.mjs';
const APP = 'http://localhost:8088/dta-sroc/index.html';
const BENIGN = /frame-ancestors|ERR_CONNECTION/;
const FIX = JSON.parse(readFileSync(new URL('./_dta_parity_fixture.json', import.meta.url), 'utf-8'));

for (const ds of FIX.datasets) {
  test(`dta-bivariate matches mada::reitsma on ${ds.dataset} (${ds.fits.length} fits)`, async ({ page }) => {
    const errs = [];
    page.on('console', (m) => { if (m.type() === 'error' && !BENIGN.test(m.text())) errs.push(m.text()); });
    await page.goto(APP, { waitUntil: 'load' });
    const res = await page.evaluate(runAll, jobsOf(ds));
    const mres = await page.evaluate(runMoses, mosesJobs(ds));
    const { bad, n } = checkDataset(ds, res, mres);
    expect(n).toBeGreaterThan(ds.fits.length);
    expect(bad, 'differences beyond tolerance').toEqual([]);
    expect(errs, 'no console errors').toEqual([]);
  });
}

test('the app shows the REML fit by default and switches method, correction rule and covariate', async ({ page }) => {
  await page.goto(APP, { waitUntil: 'load' });
  const set = (id, v) => page.evaluate(([id, v]) => { const e = document.getElementById(id); e.value = v; e.dispatchEvent(new Event('change')); }, [id, v]);
  const auditc = FIX.datasets.find((d) => d.dataset === 'AuditC');
  await set('f-example', 'AuditC');
  await page.click('#btn-example');
  let b = await page.evaluate(() => window.__almBivariate());
  const reml = auditc.fits.find((f) => f.method === 'reml' && f.correction === 'all');
  expect(b.method).toBe('reml');
  expect(Math.abs(b.coef[0] - reml.coef[0])).toBeLessThan(1e-6);
  expect(await page.locator('#stats-wrap').textContent()).toMatch(/Summary Se \(REML\)/);
  await set('f-method', 'ml');
  b = await page.evaluate(() => window.__almBivariate());
  expect(Math.abs(b.Psi[0][0] - auditc.fits.find((f) => f.method === 'ml' && f.correction === 'all').Psi[0])).toBeLessThan(1e-6);
  await set('f-cc', 'none');
  expect(await page.evaluate(() => window.__almBivariate())).toBeNull();
  expect(await page.locator('#warn-banner').textContent()).toMatch(/zero cell and the continuity correction is set to none/);
  await set('f-cc', 'all');
  expect(await page.locator('#warn-banner').textContent()).toMatch(/0\.5 was added to every cell of every study/);
  // smoking ~ type through the covariate column
  await set('f-method', 'reml');
  await set('f-example', 'smoking');
  await page.click('#btn-example');
  const mr = await page.evaluate(() => window.__almMetaRegression());
  const ref = FIX.datasets.find((d) => d.dataset === 'smoking').fits.find((f) => f.method === 'reml' && f.formula === 'cbind(tsens, tfpr) ~ type');
  expect(mr.coef.map((v, i) => Math.abs(v - ref.coef[i])).every((d) => d < 1e-6)).toBe(true);
  expect(mr.coefTable[1].term).toBe('covariate = SAQ');
  expect(await page.locator('#stats-wrap').textContent()).toMatch(/Bivariate meta-regression \(REML\)/);
  const r = await page.evaluate(() => window.__almResults());
  expect(r._schema).toBe('dta-sroc-results-v2');
  expect(r.meta_regression.coefficients).toHaveLength(4);
});
