/**
 * Parity of the heterogeneity app (heterogeneity/index.html, window.__almHetCompute: the function the page renders
 * from) with metafor 5.2-1 on the BCG vaccine trials (metadat::dat.bcg, log risk ratios), for every tau^2 estimator
 * the app offers:
 *   tau^2, mu, SE, 95% CI (z)              rma(method = M)
 *   HKSJ 95% CI (q* floored at 1)          rma(method = M, test = "adhoc")
 *   95% prediction interval (t_{k-1})      predict(rma(method = M, test = "t"))
 *   Q, p(Q), I^2 (Q-based), Q-profile CIs  rma(), confint() (tau2.max widened)
 *   leave-one-out mu and tau^2             leave1out()
 *   Baujat x and y                         baujat()
 * Ground truth: _heterogeneity_parity_fixture.json (metafor with tight convergence controls; generated by
 * heterogeneity-reproducible bench/reference_metafor.R). Tolerance 1e-9, relative to max(1, |value|) except I^2 and
 * p-values (absolute). The full validation (every intercept-only model in metadat's examples) is in
 * github.com/mahmood726-cyber/heterogeneity-reproducible.
 * Before this test: the t quantile was a 1e-6 bisection (HKSJ and prediction intervals off in the 7th digit), and the
 * Baujat influence held tau^2 fixed and divided by the full-model variance (neither Baujat's nor metafor's definition).
 */
import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
const APP = 'http://localhost:8088/heterogeneity/index.html';
const BENIGN = /frame-ancestors|ERR_CONNECTION/;
const FIX = JSON.parse(readFileSync(new URL('./_heterogeneity_parity_fixture.json', import.meta.url), 'utf-8'));
const KEYS = ['pm', 'reml', 'ml', 'eb', 'sj', 'he', 'hs', 'dl'];
const rel = (a, b) => Math.abs(a - b) / Math.max(1, Math.abs(b));

test('heterogeneity app matches metafor on the BCG trials for all eight tau^2 estimators', async ({ page }) => {
  const errs = [];
  page.on('console', (m) => { if (m.type() === 'error' && !BENIGN.test(m.text())) errs.push(m.text()); });
  await page.goto(APP, { waitUntil: 'load' });
  await page.waitForFunction(() => typeof window.__almHetCompute === 'function');
  const text = FIX.studies.map(([l, y, s]) => `${l}, ${y}, ${s}`).join('\n');
  const res = await page.evaluate(([t, keys]) => Object.fromEntries(keys.map((k) => [k, window.__almHetCompute(t, k)])), [text, KEYS]);
  const bad = [];
  const c = FIX.common, s0 = res.pm.sum, q = res.pm.qpci;
  if (rel(s0.Q, c.Q) > 1e-9) bad.push(['Q', s0.Q, c.Q]);
  if (Math.abs(s0.pQ - c.pQ) > 1e-9) bad.push(['pQ', s0.pQ, c.pQ]);
  if (Math.abs(s0.I2 - c.I2) > 1e-9) bad.push(['I2', s0.I2, c.I2]);
  for (const [a, b] of [[q.tau2Lo, c.tau2_lo], [q.tau2Hi, c.tau2_hi]]) if (rel(a, b) > 1e-9) bad.push(['tau2 CI', a, b]);
  for (const [a, b] of [[q.I2Lo, c.I2_lo], [q.I2Hi, c.I2_hi]]) if (Math.abs(a - b) > 1e-9) bad.push(['I2 CI', a, b]);
  for (const k of KEYS) {
    const r = FIX.configs[k], a = res[k], S = a.sum;
    expect(a.dlRefused, `${k}: refusal`).toBe(r.refused === true || r.refused === 'true');
    const pairs = [['tau2', a.tau2, r.tau2], ['mu', S.mu, r.mu], ['se', S.se, r.se], ['ci_lo', S.ciLo, r.ci_lo], ['ci_hi', S.ciHi, r.ci_hi],
      ['hk_lo', S.ciLoHKSJ, r.hk_lo], ['hk_hi', S.ciHiHKSJ, r.hk_hi], ['pi_lo', a.pi.lo, r.pi_lo], ['pi_hi', a.pi.hi, r.pi_hi]];
    a.loo.forEach((l, i) => pairs.push([`loo_mu[${i}]`, l.mu, r.loo_mu[i]], [`loo_tau2[${i}]`, l.tau2, r.loo_tau2[i]]));
    a.baujat.forEach((b, i) => pairs.push([`baujat_x[${i}]`, b.x, r.baujat_x[i]], [`baujat_y[${i}]`, b.y, r.baujat_y[i]]));
    for (const [n, x, y] of pairs) if (!(rel(x, y) <= 1e-9)) bad.push([k, n, x, y]);
  }
  expect(bad, 'differences beyond tolerance').toEqual([]);
  expect(errs, 'no console errors').toEqual([]);
});

test('the page labels the estimator it used, shows Greek letters as written, and refuses DL below k = 10', async ({ page }) => {
  await page.goto(APP, { waitUntil: 'load' });
  await page.click('#btn-example');   // the built-in example has 8 trials
  await page.evaluate(() => { const s = document.getElementById('f-tau2'); s.value = 'dl'; s.dispatchEvent(new Event('input', { bubbles: true })); });
  await expect(page.locator('#warn-banner')).toContainText('DL is disabled for k<10');
  await expect(page.locator('#stats-wrap')).toContainText('(PM)');
  await expect(page.locator('#loo-table th').nth(2)).toHaveText('μ');
  await expect(page.locator('#loo-table th').nth(5)).toHaveText('τ²');
  const lab = await page.locator('#stats-wrap .stat .k').first().evaluate((e) => getComputedStyle(e).textTransform);
  expect(lab).toBe('none');
});
