/**
 * Full parity of the nma app's engine (shared/nma-multiarm-v1.js, analyse()) with netmeta 3.7.0 on every
 * dataset shipped with netmeta (13; contrasts built with pairwise() and each dataset's summary measure),
 * with both random-effects CI methods ("classic", "t-dist"):
 *   common- and random-effects league tables (estimate, SE, 95% CI, p), prediction intervals, Q (df, p),
 *   tau^2, I^2 with its CI, the design-based decomposition of Q (decomp.design), and P-scores (netrank)
 *   with small values desirable and undesirable. Dong2013 must be refused (one three-arm study has an
 *   undefined comparison, so netmeta refuses the network).
 * Ground truth: _nma_parity_fixture.json (generated by _nma_parity_gen.R). Tolerances: _nma_parity_check.mjs.
 * Up to allmeta 76d3e9d the app dropped such a study and fitted the rest, showed the league table as
 * column versus row under a "rows vs columns" heading, and ranked by simulated SUCRA assuming smaller is
 * better; it reported no CIs other than normal ones, no prediction intervals, p-values, I^2 or Q decomposition.
 */
import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { jobsOf, runAll, checkDataset } from './_nma_parity_check.mjs';
const APP = 'http://localhost:8088/nma/index.html';
const BENIGN = /frame-ancestors|ERR_CONNECTION/;
const FIX = JSON.parse(readFileSync(new URL('./_nma_parity_fixture.json', import.meta.url), 'utf-8'));

for (const ds of FIX.datasets) {
  test(`nma engine matches netmeta on ${ds.dataset}`, async ({ page }) => {
    const errs = [];
    page.on('console', (m) => { if (m.type() === 'error' && !BENIGN.test(m.text())) errs.push(m.text()); });
    await page.goto(APP, { waitUntil: 'load' });
    const res = await page.evaluate(runAll, jobsOf(ds));
    const { bad, n } = checkDataset(ds, res);
    expect(n).toBeGreaterThanOrEqual(ds.fits.length);
    expect(bad, 'differences beyond tolerance').toEqual([]);
    expect(errs, 'no console errors').toEqual([]);
  });
}

test('the page shows netmeta\'s results for an example dataset, row versus column', async ({ page }) => {
  await page.goto(APP, { waitUntil: 'load' });
  const set = (id, v) => page.evaluate(([id, v]) => { const e = document.getElementById(id); e.value = v; e.dispatchEvent(new Event('change')); }, [id, v]);
  const senn = FIX.datasets.find((d) => d.dataset === 'Senn2013').fits.find((f) => f.method_random_ci === 'classic');
  await set('f-example', 'Senn2013');
  await page.click('#btn-example');
  expect(await page.locator('#f-model').inputValue()).toBe('re');
  expect(await page.locator('#f-ref').inputValue()).toBe('plac');
  const het = await page.locator('#het-host').textContent();
  expect(het).toContain(senn.tau2.toFixed(4));
  expect(het).toMatch(/Between designs \(inconsistency\)/);
  // league cell (row = metf, column = plac) is metf versus plac, i.e. netmeta TE.random["metf", "plac"]
  const i = senn.trts.indexOf('metf'), j = senn.trts.indexOf('plac'), n = senn.trts.length;
  await set('f-scale', 'log');
  const cell = await page.evaluate(() => { const t = document.querySelector('#league-host table'); const heads = [...t.querySelectorAll('thead th')].map((h) => h.textContent);
    const row = [...t.querySelectorAll('tbody tr')].find((r) => r.querySelector('th').textContent === 'metf'); return row.querySelectorAll('td')[heads.indexOf('plac') - 1].textContent; });
  expect(cell.startsWith(senn.TE_random[i * n + j].toFixed(3))).toBe(true);
  // the stat label keeps its Greek letter
  expect(await page.locator('#stats-wrap').textContent()).toContain('τ²');
  // P-scores follow the chosen direction (Senn2013: HbA1c, smaller is better)
  const top = await page.evaluate(() => document.querySelectorAll('#sucra-host .sucra-row')[1].firstChild.textContent);
  const ps = senn.pscore_desirable.random, best = senn.trts[ps.indexOf(Math.max(...ps))];
  expect(top).toBe(best);
});
