/**
 * nma-parity.spec.mjs — basic frequentist NMA R-parity vs netmeta.
 *
 * Consistent fixture => DL tau2=0 => common == random. Oracle: nma/tests/fixtures/nma-oracle.json
 * (nma-oracle.R, rounded to 8 decimals for effects, 6 for P-scores).
 * The oracle was generated by giving netmeta the app's estimate (treatment2 - treatment1) as its TE,
 * which netmeta reads as treatment1 - treatment2: the oracle's effects are therefore the negative of the
 * app's, and its "desirable" P-scores are the app's "undesirable" ones. This is stated here once instead
 * of auto-detecting the orientation, which could not catch a sign or direction error. The full parity
 * check (every netmeta dataset, all outputs) is nma-netmeta-parity.spec.mjs.
 */
import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';

const APP_URL = 'http://localhost:8088/nma/';
const O = JSON.parse(readFileSync(
  new URL('../../../nma/tests/fixtures/nma-oracle.json', import.meta.url), 'utf-8'));
const FIXTURE = [
  'S1, A, B, 0.20, 0.10', 'S2, A, B, 0.35, 0.12', 'S3, A, B, 0.28, 0.09',
  'S4, A, C, 0.50, 0.11', 'S5, A, C, 0.42, 0.13',
  'S6, B, C, 0.18, 0.10', 'S7, B, C, 0.25, 0.14',
].join('\n');
const TOL = 1e-7;      // oracle rounded to 8 decimals
const PS_TOL = 1e-6;   // oracle P-scores rounded to 6 decimals

test.describe('nma', () => {
  test('loads, no console errors, hook present', async ({ page }) => {
    const errs = [];
    const benign = t => (t.includes('frame-ancestors') &&
      t.includes('Content Security Policy')) || t.includes('ERR_CONNECTION_REFUSED');
    page.on('console', m => {
      if (m.type() === 'error' && !benign(m.text())) errs.push(m.text());
    });
    page.on('pageerror', e => { if (!benign(e.message)) errs.push(e.message); });
    await page.goto(APP_URL);
    await page.waitForFunction(() => typeof window.__almNmaCompute === 'function',
      { timeout: 10_000 });
    expect(errs, 'console errors: ' + errs.join('; ')).toEqual([]);
  });

  test('netmeta R-parity (nma-tiny: effects, SE, tau2 and P-scores)',
    async ({ page }) => {
      await page.goto(APP_URL);
      await page.waitForFunction(
        () => typeof window.__almNmaCompute === 'function', { timeout: 10_000 });
      const r = await page.evaluate(
        (t) => window.__almNmaCompute(t, 'A'), FIXTURE);
      expect(r && r.fe && !r.fe.error, 'compute failed').toBeTruthy();

      const near = (g, e, n) =>
        expect(Math.abs(g - e), `${n}: js=${g} R=${e}`).toBeLessThan(TOL);

      const sgn = -1;   // see the header: the oracle's netmeta TE is the negative of the app's estimate

      for (const model of ['fe', 're']) {
        const f = r[model];
        near(f.tau2, O.tau2, `${model} tau2`);
        for (const t of O.trts) {
          near(f.est[t].d, sgn * O.TE[t], `${model} effect ${t} vs A`);
          near(f.est[t].se, O.seTE[t], `${model} SE ${t}`);
        }
      }

      // P-scores (closed form, as netmeta netrank): app "desirable" = oracle "undesirable" and vice versa
      for (const t of O.trts) {
        expect(Math.abs(r.pscore.desirable.fe[t] - O.pscore_undesirable[t]), `P-score ${t}`).toBeLessThan(PS_TOL);
        expect(Math.abs(r.pscore.undesirable.fe[t] - O.pscore_desirable[t]), `P-score ${t}`).toBeLessThan(PS_TOL);
      }
    });
});
