# -*- coding: utf-8 -*-
"""THE BLINDING CONTROL. PROTOCOL: oa68k/SCORING-PROTOCOL.md section 2A.

IT RUNS FIRST, BEFORE ANY CRITERION. A blinding control run afterwards measures nothing,
because by then we know which way we would like it to fall.

The judge is asked ONE question -- which side is machine-generated -- and nothing about
quality. Sample A (the first 6 pairs by sha256(pair_id)) was fixed in the protocol before
any result existed; sample B (the next 6) is reserved for revalidation if the renderer
changes, and sample A is then BURNED.

Consequence, declared in the protocol before this ran: if judges identify our side above
chance, every criterion result afterwards measures FORMAT, not quality.

Join-independent: it uses the union of pairs and never touches 22/12/8.
"""
import io
import json
import os
import re
import subprocess
import sys
import time
import xml.etree.ElementTree as ET
from urllib.request import Request, urlopen

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import opencompscore as S  # noqa: E402
import judgeprobe as P  # noqa: E402

OUTDIR = r"F:\claude-temp\pend"
RESULT = os.path.join(OUTDIR, "blinding_control.json")
EPMC = "https://www.ebi.ac.uk/europepmc/webservices/rest"
UA = {"User-Agent": "allmeta-opencomp/1.0 (research; mailto:mahmood726@gmail.com)"}

SAMPLE_CHARS = 6000          # symmetric stylistic sample; declared, not discovered
SAMPLE_A_N = 6
TIMEOUT = 420

ASK = """You are shown two dossiers, SIDE_A and SIDE_B, describing meta-analyses of the
same clinical question. Exactly one of them was generated by a machine pipeline; the
other was written by human authors for a journal.

Answer ONLY these three lines, nothing else, no preamble, no code fence:
MODEL=<the exact model identifier you are running as>
ANSWER=<A or B -- the side you believe is machine-generated>
TELL=<one sentence: what gave it away>
"""


def fetch_fulltext(pmcid):
    u = "%s/%s/fullTextXML" % (EPMC, pmcid)
    return urlopen(Request(u, headers=UA), timeout=180).read()


def comparator_dossier(pmcid):
    """Render the comparator into THE SAME section skeleton as our side. If the skeleton
    is what identifies a side, this control is exactly the thing that should find it."""
    raw = fetch_fulltext(pmcid)
    try:
        root = ET.fromstring(raw)
    except ET.ParseError:
        root = None
    txt = raw.decode("utf-8", "replace")

    def sec(*names):
        out = []
        if root is None:
            return ""
        for s in root.iter("sec"):
            t = (s.findtext("title") or "")
            if any(n.lower() in t.lower() for n in names):
                out.append(re.sub(r"\s+", " ", " ".join(s.itertext())))
        return " ".join(out)

    abstract = ""
    if root is not None:
        for a in root.iter("abstract"):
            abstract += " " + re.sub(r"\s+", " ", " ".join(a.itertext()))
    caps = []
    if root is not None:
        for tw in root.iter("table-wrap"):
            c = re.sub(r"\s+", " ", " ".join(tw.itertext()))
            caps.append(c[:1500])
    return "\n".join([
        "## QUESTION", abstract.strip()[:4000], "",
        "## INCLUDED STUDIES",
        " | ".join(sorted(set(re.findall(r"NCT\d{8}", txt)))[:60]),
        " ".join(caps)[:20000], "",
        "## SYNTHESIS", (sec("result", "synthes") or "")[:60000], "",
        "## SEARCH", (sec("search", "method", "data source") or "")[:30000], "",
        "## RISK OF BIAS", (sec("risk of bias", "quality assess") or "")[:30000], "",
        "## PROTOCOL AND REGISTRATION",
        " ".join(re.findall(r"[^.]{0,200}CRD42\d{9}[^.]{0,200}", txt))[:12000],
    ]), len(raw)


def call(family, prompt_path, tag):
    """One judge call. Prompt lives in a FILE, named in argv. Never stdin."""
    build, model, how = P.SEATS[family]
    logfile = os.path.join(OUTDIR, "blinding_%s_%s.log" % (tag, family))
    instr = ("Read the file %s and follow the instructions it contains." % prompt_path)
    argv = {"anthropic": ["claude", "-p", "--model", model, instr],
            "openai": [r"C:\Users\mahmo\AppData\Roaming\npm\codex.cmd", "exec",
                       "-m", model, instr],
            "google": ["agy", "--print", instr]}[family]
    restore = None
    if family == "google":
        restore, _ = P.pin_agy(model)
    t0 = time.time()
    rc, out, err, herr = None, "", "", None
    try:
        p = subprocess.run(argv, capture_output=True, timeout=TIMEOUT,
                           stdin=subprocess.DEVNULL)
        rc, out = p.returncode, p.stdout.decode("utf-8", "replace")
        err = p.stderr.decode("utf-8", "replace")
    except subprocess.TimeoutExpired:
        herr = "TIMEOUT_%ds" % TIMEOUT
    except OSError as e:
        herr = "OSERROR:%s" % e
    finally:
        if restore is not None:
            S.write_verified(P.AGY_SETTINGS, restore)
    dt = time.time() - t0
    S.write_verified(logfile, "family=%s\npinned=%s\nprompt_file=%s\nrc=%s\nsec=%.1f\n"
                              "harness_error=%s\n--- STDOUT ---\n%s\n--- STDERR ---\n%s\n"
                              % (family, model, prompt_path, rc, dt, herr, out, err))
    disk = io.open(logfile, encoding="utf-8").read()
    so = disk.split("--- STDOUT ---\n", 1)[1].split("\n--- STDERR ---", 1)[0]
    void = ("JUDGE_CALL_VOID:%s" % herr) if herr else S.verify_judge_artefact(rc, so, family)
    m = re.search(r"ANSWER\s*=\s*([AB])", so, re.I)
    return {"family": family, "logfile": logfile, "seconds": round(dt, 1), "rc": rc,
            "void": void, "answer": (m.group(1).upper() if m else None),
            "tell": (re.search(r"TELL\s*=\s*(.+)", so).group(1)[:300]
                     if re.search(r"TELL\s*=\s*(.+)", so) else None),
            "stdout_head": " ".join(so.split())[:300]}


def main():
    live = json.load(io.open(P.RESULT, encoding="utf-8"))["live_families"]
    if "--rescore" in sys.argv:
        # recompute from the STORED verdicts. No judge is called.
        d = json.load(io.open(RESULT, encoding="utf-8"))
        pr = [json.loads(l) for l in io.open(S.PAIRS, encoding="utf-8") if l.strip()]
        pr.sort(key=lambda p: S.sha256(p["pair_id"]))
        return score(d["verdicts"], live, pr[:SAMPLE_A_N])
    if not live:
        raise SystemExit("no verified judge family -- refusing to run a control on a "
                         "panel that has not been proven")
    pairs = [json.loads(l) for l in io.open(S.PAIRS, encoding="utf-8") if l.strip()]
    pairs.sort(key=lambda p: S.sha256(p["pair_id"]))
    sample_a = pairs[:SAMPLE_A_N]
    print("panel (verified): %s" % live)
    print("sample A (frozen in the protocol): %s"
          % [p["pair_id"] for p in sample_a])
    print("")

    rows = []
    for p in sample_a:
        ours = S.our_side_dossier(p["topic"])
        theirs, nraw = comparator_dossier(p["comparator_pmcid"])
        a_text, b_text = ((ours, theirs) if p["side_a_is_ours"] else (theirs, ours))
        body = "%s\n\n=== SIDE_A ===\n%s\n\n=== SIDE_B ===\n%s\n" % (
            ASK, a_text[:SAMPLE_CHARS], b_text[:SAMPLE_CHARS])
        pf = os.path.join(OUTDIR, "blinding_prompt_%s.txt" % p["pair_id"])
        S.write_verified(pf, body)
        print("%-28s comparator %s (%d raw bytes) prompt %d bytes  ours_is=%s"
              % (p["pair_id"], p["comparator_pmcid"], nraw, os.path.getsize(pf),
                 "A" if p["side_a_is_ours"] else "B"))
        for fam in live:
            r = call(fam, pf, p["pair_id"])
            truth = "A" if p["side_a_is_ours"] else "B"
            r.update({"pair_id": p["pair_id"], "truth": truth,
                      "correct": (None if r["void"] else r["answer"] == truth),
                      "prompt_sha256": S.sha256(body), "prompt_file": pf})
            rows.append(r)
            print("   %-10s %-6s answer=%s truth=%s %s"
                  % (fam, "VOID" if r["void"] else "ok", r["answer"], truth,
                     r["void"] or ("CORRECT" if r["correct"] else "wrong")))
        print("")

    return score(rows, live, sample_a)


def _P(k, n, p=0.5):
    from math import comb
    return sum(comb(n, i) * p ** i * (1 - p) ** (n - i) for i in range(k, n + 1))


def score(rows, live, sample_a):
    scored = [r for r in rows if r["correct"] is not None]
    k = sum(1 for r in scored if r["correct"])
    n = len(scored)
    pval = _P(k, n) if n else None
    # ⛔ THE BUG THIS REPLACES: the critical value was a lookup {12:10, 18:13}, so an
    # ACHIEVED n of 9 returned None and the headline boolean came out False while
    # p = 0.002. A missing table row silently reported "not identified above chance"
    # -- and it erred in OUR favour, which is the direction that never gets questioned.
    # The critical value is now COMPUTED for whatever n was achieved.
    crit = next((x for x in range(n + 1) if _P(x, n) <= 0.05), None) if n else None
    n_void = len(rows) - n
    worst_k, worst_n = k, n + n_void          # every voided call counted WRONG
    worst_crit = next((x for x in range(worst_n + 1) if _P(x, worst_n) <= 0.05), None)
    per_family = {}
    for fam in live:
        f = [r for r in scored if r["family"] == fam]
        if f:
            kk = sum(1 for r in f if r["correct"])
            per_family[fam] = {"correct": kk, "n": len(f), "p": round(_P(kk, len(f)), 4),
                               "clears_alpha_05": _P(kk, len(f)) <= 0.05}
    out = {
        "control": "blinding", "protocol": S.PROTOCOL,
        "ran_before_any_criterion": True,
        "panel_verified": live,
        "sample": "A (first %d pairs by sha256(pair_id), frozen in the protocol)" % SAMPLE_A_N,
        "sample_a_pairs": [p["pair_id"] for p in sample_a],
        "sample_chars_per_side": SAMPLE_CHARS,
        "n_planned_three_family": SAMPLE_A_N * 3,
        "n_achieved": n, "correct": k, "void": n_void,
        "one_sided_binomial_p": (round(pval, 5) if pval is not None else None),
        "critical_value_computed_for_achieved_n": crit,
        "per_family": per_family,
        "identifies_our_side_above_chance": bool(n and crit is not None and k >= crit),
        "robust_to_the_voided_calls":
            bool(worst_crit is not None and worst_k >= worst_crit),
        "worst_case_imputation":
            "Counting all %d voided calls as WRONG gives %d/%d, one-sided p=%.4f, which "
            "%s clear alpha=0.05 (critical value %s). The POOLED result is therefore %s "
            "to the missing calls. The per-family Anthropic test does not depend on them "
            "at all: all of its calls completed."
            % (n_void, worst_k, worst_n, _P(worst_k, worst_n),
               "does" if (worst_crit is not None and worst_k >= worst_crit) else "does NOT",
               worst_crit,
               "robust" if (worst_crit is not None and worst_k >= worst_crit)
               else "FRAGILE"),
        "constant_strategy_note":
            "Sample A is 4 pairs with our side as A and 2 with our side as B, so a judge "
            "answering 'A' every time scores 4/6 per family and 8/12 pooled -- below "
            "every critical value above. The result is not a constant-response artefact.",
        "tells": [r.get("tell") for r in scored if r.get("tell")],
        "consequence_declared_in_advance":
            "If judges identify our side above chance, EVERY criterion result afterwards "
            "measures FORMAT, not quality, and must be reported as such.",
        "power_note":
            "The protocol pre-computed n=18 (rejects at >=13, power 0.87 at p=0.80) and "
            "n=12 (rejects at >=10, power 0.56 at p=0.80). The openai seat failed its "
            "readback, so the achievable n is 12 -- a row that was in the frozen table "
            "BEFORE this ran, not a test chosen after seeing a seat fail.",
        "burn_rule":
            "If the renderer is changed in response to this result, sample A is BURNED "
            "and revalidation runs on sample B (the next 6 pairs), once.",
        "verdicts": rows,
    }
    S.write_verified(RESULT, json.dumps(out, ensure_ascii=False, indent=1))
    print("=== BLINDING CONTROL: %d/%d correct, void %d, one-sided p=%s, rejects at >=%s"
          % (k, n, n_void, out["one_sided_binomial_p"], crit))
    for f, d in per_family.items():
        print("    %-10s %d/%d  p=%.4f  clears alpha=.05: %s"
              % (f, d["correct"], d["n"], d["p"], d["clears_alpha_05"]))
    print("    IDENTIFIES OUR SIDE ABOVE CHANCE: %s"
          % out["identifies_our_side_above_chance"])
    print("    robust to the %d voided calls: %s" % (n_void, out["robust_to_the_voided_calls"]))
    if out["identifies_our_side_above_chance"]:
        print("    ==> THE COMPARISON IS NOT BLINDED. Every criterion result on this")
        print("        renderer would measure FORMAT, not quality. SAMPLE A IS BURNED.")
    print("wrote %s (%d bytes)" % (RESULT, os.path.getsize(RESULT)))
    return 0


if __name__ == "__main__":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8",
                                  errors="replace", line_buffering=True)
    sys.exit(main())
