# Writes dta-sroc/example-datasets.js: the six diagnostic-accuracy datasets shipped with the R package
# mada, in the app's input format (label, TP, FP, FN, TN [, covariate]). Sources as documented in
# mada's ?`mada-data`.
#   Rscript _make_examples.R example-datasets.js
suppressMessages(library(mada))
args <- commandArgs(trailingOnly = TRUE)
out <- if (length(args)) args[1] else "example-datasets.js"
src <- c(AuditC = "AUDIT-C for unhealthy alcohol use (Kriston et al. 2008)",
  Dementia = "Mini-Mental State Examination for dementia (Mitchell 2009)",
  IAQ = "Interviewer-administered questionnaires for smoking (Patrick et al. 1994)",
  SAQ = "Self-administered questionnaires for smoking (Patrick et al. 1994)",
  skin_tests = "Penicillin allergy skin tests (Sousa-Pinto et al. 2021)",
  smoking = "Self-reported smoking, IAQ and SAQ combined, covariate type (Patrick et al. 1994)")
items <- character()
for (d in names(src)) {
  e <- new.env(); data(list = d, package = "mada", envir = e); x <- as.data.frame(get(d, e))
  lab <- if (!is.null(x$author)) paste0(gsub(",", "", x$author), " #", x$result_id) else paste("Study", seq_len(nrow(x)))
  cov <- if (d == "smoking") paste0(", ", x$type) else ""
  lines <- paste0(lab, ", ", x$TP, ", ", x$FP, ", ", x$FN, ", ", x$TN, cov)
  items <- c(items, sprintf('  %s: { title: "%s", covariate: %s, data: "%s" }', d, src[[d]],
                            if (d == "smoking") '"type"' else "null", paste(lines, collapse = "\\n")))
}
cat("/* The six example datasets shipped with the R package mada 0.5.12 (Doebler P, Holling H), as\n",
    " * label, TP, FP, FN, TN (+ covariate). Generated by dta-sroc/_make_examples.R; do not edit. */\n",
    "window.DTA_EXAMPLES = {\n", paste(items, collapse = ",\n"), "\n};\n", sep = "", file = out)
