"""Emit triage.{json,csv,md,html} from per-app records."""

from __future__ import annotations
from pathlib import Path
from typing import Iterable
import json
import csv


def _totals(records: list[dict]) -> dict[str, int]:
    out = {f"tier_{i}": 0 for i in range(1, 6)}
    for r in records:
        out[f"tier_{r['tier']}"] += 1
    out["total"] = len(records)
    return out


def render_json(records: list[dict], out_path: Path, *, scanner_version: str, now_iso: str) -> None:
    payload = {
        "scanner_version": scanner_version,
        "generated_at": now_iso,
        "totals": _totals(records),
        "apps": {r["key"]: {k: v for k, v in r.items() if k != "key"} for r in records},
    }
    out_path.write_text(json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False), encoding="utf-8")


_CSV_COLS = (
    "app", "tier", "auto_tier", "kind", "confidence",
    "stub_count", "test_count", "has_r_parity", "last_touched_days",
    "total_size_kb", "is_hub_linked", "featured_rank", "reasons",
)


def _record_to_csv_row(r: dict) -> dict:
    s = r.get("signals", {})
    return {
        "app": r["key"],
        "tier": r["tier"],
        "auto_tier": r["auto_tier"],
        "kind": r["kind"],
        "confidence": r["confidence"],
        "stub_count": s.get("stub_count"),
        "test_count": s.get("test_count"),
        "has_r_parity": s.get("has_r_parity"),
        "last_touched_days": s.get("last_touched_days"),
        "total_size_kb": s.get("total_size_kb"),
        "is_hub_linked": s.get("is_hub_linked"),
        "featured_rank": s.get("featured_rank"),
        "reasons": " | ".join(r.get("reasons", [])),
    }


def render_csv(records: list[dict], out_path: Path) -> None:
    with out_path.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(_CSV_COLS))
        w.writeheader()
        for r in records:
            w.writerow(_record_to_csv_row(r))


_TIER_TITLES = {
    5: "Tier 5 — Active rebuild",
    4: "Tier 4 — Hardening priority",
    3: "Tier 3 — Polish needed",
    2: "Tier 2 — Working",
    1: "Tier 1 — Validated",
}


def render_md(records: list[dict], out_path: Path, *, scanner_version: str, now_iso: str) -> None:
    totals = _totals(records)
    lines = [
        f"<!-- sentinel:skip-file — generated by triage/scan.py -->",
        "",
        f"# allmeta triage atlas",
        f"",
        f"Generated: {now_iso} · scanner v{scanner_version} · {totals['total']} apps",
        "",
        "## Summary",
        "",
    ]
    for t in (1, 2, 3, 4, 5):
        lines.append(f"- {_TIER_TITLES[t]}: {totals[f'tier_{t}']}")
    lines.append("")
    for t in (5, 4, 3, 2, 1):
        bucket = sorted([r for r in records if r["tier"] == t], key=lambda x: x["key"].lower())
        if not bucket:
            continue
        lines.append(f"## {_TIER_TITLES[t]} ({len(bucket)})")
        lines.append("")
        for r in bucket:
            override_flag = " · **override**" if r.get("override") else ""
            reasons = " · ".join(r.get("reasons", []))
            lines.append(f"- **{r['key']}** — {reasons}{override_flag}")
        lines.append("")
    low = [r for r in records if r["confidence"] == "low"]
    if low:
        lines.append(f"## Low-confidence flags ({len(low)})")
        lines.append("")
        for r in sorted(low, key=lambda x: x["key"].lower()):
            lines.append(f"- {r['key']} (tier {r['tier']}) — manual review")
        lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")
