/* shared/rob-core.js — allmeta deterministic Risk-of-Bias signalling engine.
 *
 * One source of truth, used by BOTH:
 *   • /rob/index.html  (browser: window.RobCore)
 *   • benchmark/run_rob_benchmark.mjs  (node: require/import)
 *
 * It scans study text (abstract / methods / full text) for Cochrane-Handbook
 * signalling phrases and SUGGESTS a per-domain judgment with the supporting
 * sentence it keyed on. It is a *suggestion* engine — it never finalises a
 * judgment. Confirmation/override is the reviewer's (mirrors the Screen app).
 *
 * Cue phrases are derived from the published Cochrane Handbook RoB criteria
 * (Higgins & Green; Sterne 2019 for RoB 2) — NOT fitted to any benchmark
 * labels. This makes the benchmark a held-out, zero-shot evaluation.
 *
 * No dependencies. ASCII only. Deterministic (no Date/Math.random).
 */
(function (root) {
  "use strict";

  // --- judgment vocabulary -------------------------------------------------
  // 3-way RoB-1 / RoB-2-domain scale used internally:
  //   low | some | high   (plus "unclear" === "some" for RoB-1 framing).
  // RoB 2 domain verdicts: low | some | high. ROBINS-I: low | moderate | serious | critical.

  // --------------------------------------------------------------------------
  // 1. SIGNALLING PHRASE MODELS (Cochrane Handbook RoB-1 domains)
  //    These power both (a) the head-to-head benchmark vs RobotReviewer and
  //    (b) the auto-suggestions for RoB 2 / ROBINS-I signalling questions.
  //
  //    Each cue: { re, w, note }  where w in [0,1] is the strength.
  //    A LOW cue votes "low"; a HIGH cue votes "high". The strongest cue wins.
  //    `neg:true` cues are skipped when immediately preceded by a negation word
  //    (no / not / without / lack of / fail) — e.g. "not randomly generated".
  // --------------------------------------------------------------------------

  var DOMAINS = {
    sequence: {
      key: "sequence",
      name: "Random sequence generation",
      rob1: "random sequence generation (selection bias)",
      blurb: "Was the allocation sequence generated by a truly random process?",
      low: [
        // canonical random-generation methods (order-independent where possible)
        { re: /computer[\s-]?generat(?:ed|ion)?/i, w: 0.92, note: "computer-generated", neg: true },
        { re: /\bcomputer(?:ised|ized)?\s+random/i, w: 0.9, note: "computerised randomisation", neg: true },
        { re: /random(?:isation|ization)?\s+(?:was\s+|were\s+)?(?:computer|generated by (?:a\s+)?computer)/i, w: 0.9, note: "randomisation computer-generated", neg: true },
        { re: /\brandom(?:ly)?\s+number\s+(?:table|generat)/i, w: 0.92, note: "random number table/generator", neg: true },
        { re: /table\s+of\s+random\s+numbers/i, w: 0.9, note: "table of random numbers", neg: true },
        { re: /random\s+numbers?\s+(?:table|list|were|was|generated)/i, w: 0.82, note: "random numbers", neg: true },
        { re: /\brandom\s+number\s+generator\b/i, w: 0.92, note: "random number generator", neg: true },
        { re: /random(?:ly)?\s+generated\s+(?:sequence|list|code|allocation|number)/i, w: 0.88, note: "randomly generated sequence", neg: true },
        { re: /\bcoin[\s-]?toss/i, w: 0.85, note: "coin toss", neg: true },
        { re: /(?:throw|roll|rolling|tossing)\s+(?:of\s+)?(?:a\s+|the\s+)?dic?e/i, w: 0.8, note: "dice", neg: true },
        { re: /drawing\s+of\s+lots/i, w: 0.8, note: "drawing of lots", neg: true },
        { re: /\bshuffl(?:e|ing|ed)\b/i, w: 0.7, note: "shuffling", neg: true },
        { re: /minimi[sz]ation\b/i, w: 0.82, note: "minimisation", neg: true },
        { re: /(?:permuted|varying|random(?:ly)?)[\s-]?block/i, w: 0.86, note: "permuted/varying blocks", neg: true },
        { re: /block(?:s|ing|[\s-]?allocat\w*)?\s+(?:of\s+(?:size\s+)?(?:\w+|\d)|random|by\s+random)/i, w: 0.78, note: "blocked randomisation", neg: true },
        { re: /\bblock[\s-]?randomi[sz]/i, w: 0.82, note: "block randomisation", neg: true },
        { re: /stratified\s+(?:block\s+)?random/i, w: 0.8, note: "stratified randomisation", neg: true },
        { re: /random(?:i[sz]ation|ly)?\s*(?:was\s+|,\s+)?stratified/i, w: 0.76, note: "randomisation stratified", neg: true },
        { re: /allocation\s+sequence\s+(?:was\s+)?(?:computer|random|generated|central)/i, w: 0.82, note: "allocation sequence generated", neg: true },
        { re: /random(?:ly)?\s+(?:allocat|assign).{0,40}\b(?:computer|table|generator|software|sequence generated)/i, w: 0.78, note: "random allocation by computer/table" },
      ],
      high: [
        { re: /\b(?:odd\s+or\s+even|even\s+or\s+odd)\b/i, w: 0.9, note: "odd/even rule" },
        { re: /(?:date|day)\s+of\s+(?:birth|admission)/i, w: 0.88, note: "date of birth/admission" },
        { re: /(?:hospital|clinic|record|chart|medical[\s-]?record|case)\s+number/i, w: 0.82, note: "record-number allocation" },
        { re: /\balternat(?:e(?:ly)?|ing|ion)\b/i, w: 0.82, note: "alternation" },
        { re: /quasi[\s-]?random/i, w: 0.78, note: "quasi-random" },
        { re: /(?:order|sequence)\s+of\s+(?:admission|presentation|enrol)/i, w: 0.72, note: "order of admission" },
        { re: /day\s+of\s+the\s+week/i, w: 0.8, note: "day of week" },
      ],
    },

    allocation: {
      key: "allocation",
      name: "Allocation concealment",
      rob1: "allocation concealment (selection bias)",
      blurb: "Was the allocation sequence concealed from enrollers until assignment?",
      low: [
        { re: /central(?:i[sz]ed)?\s+(?:allocation|randomi[sz]ation|assignment)/i, w: 0.9, note: "central allocation", neg: true },
        { re: /(?:telephone|phone|web[\s-]?based|internet|online|pharmacy[\s-]?controlled|interactive\s+voice)\s*(?:[\s-]?(?:based|controlled))?\s*randomi[sz]/i, w: 0.9, note: "telephone/web/pharmacy randomisation", neg: true },
        { re: /sequentially\s+numbered,?\s+opaque,?\s+sealed\s+envelope/i, w: 0.95, note: "SNOSE (opaque sealed envelopes)", neg: true },
        { re: /opaque,?\s+sealed\s+envelope/i, w: 0.9, note: "opaque sealed envelopes", neg: true },
        { re: /\bopaque\b/i, w: 0.78, note: "opaque envelopes", neg: true },
        { re: /sequentially\s+numbered\s+(?:drug\s+)?container/i, w: 0.85, note: "sequentially numbered containers", neg: true },
        { re: /identical\s+(?:in\s+)?appearance/i, w: 0.7, note: "identical containers", neg: true },
        { re: /allocation\s+(?:was\s+)?conceal/i, w: 0.82, note: "allocation concealed", neg: true },
        { re: /conceal(?:ed|ment)\s+(?:of\s+)?(?:the\s+)?allocation/i, w: 0.82, note: "concealment of allocation", neg: true },
        { re: /\bSNOSE\b/, w: 0.85, note: "SNOSE" },
        // central / off-site / independent randomisation implies concealment (Handbook)
        { re: /central(?:ly)?\s+(?:randomi[sz]|allocat|administered)/i, w: 0.85, note: "central randomisation", neg: true },
        { re: /(?:off[\s-]?site|remote|third[\s-]?party)\s+randomi[sz]/i, w: 0.82, note: "off-site randomisation", neg: true },
        { re: /independent\s+(?:statistician|pharmacist|pharmacy|person|researcher|party|unit|centre|center)\s+(?:who\s+)?(?:prepared|generated|held|performed|administered|randomi|kept|controlled|managed)/i, w: 0.84, note: "independent party held/prepared allocation", neg: true },
        { re: /allocation\s+(?:was\s+)?(?:performed|done|carried out|generated|managed)\s+(?:centrally|off[\s-]?site|remotely|by\s+(?:an?\s+)?independent)/i, w: 0.85, note: "allocation performed centrally/independently", neg: true },
        { re: /computer[\s-]?generat(?:ed|ion)?/i, w: 0.62, note: "computer-generated sequence (concealment inferred)", neg: true },
      ],
      high: [
        { re: /open\s+(?:random\s+)?allocation\s+(?:schedule|list)/i, w: 0.88, note: "open allocation schedule" },
        { re: /\balternat(?:e(?:ly)?|ing|ion)\b/i, w: 0.82, note: "alternation" },
        { re: /(?:unsealed|non[\s-]?opaque|not\s+opaque|translucent)\s+envelope/i, w: 0.85, note: "unsealed/non-opaque envelopes" },
        { re: /(?:date|day)\s+of\s+(?:birth|admission)/i, w: 0.8, note: "date-based allocation" },
        { re: /no\s+(?:allocation\s+)?concealment/i, w: 0.85, note: "no concealment" },
        { re: /(?:hospital|record|case)\s+number/i, w: 0.72, note: "record-number allocation" },
      ],
    },

    performance: {
      key: "performance",
      name: "Blinding of participants and personnel",
      rob1: "blinding of participants and personnel (performance bias)",
      blurb: "Were participants and care providers blind to the assigned intervention?",
      low: [
        { re: /double[\s-]?blind/i, w: 0.9, note: "double-blind", neg: true },
        { re: /triple[\s-]?blind/i, w: 0.9, note: "triple-blind", neg: true },
        { re: /participants?\b[^.;:]{0,45}?\b(?:were\s+|was\s+)?(?:blind|mask)(?:ed|ing)?\b/i, w: 0.85, note: "participants blinded", neg: true },
        { re: /(?:matching|identical)[\s-]?(?:looking\s+)?placebo/i, w: 0.82, note: "matching placebo", neg: true },
        { re: /blinding\s+of\s+participants\s+and\s+(?:personnel|care|staff)/i, w: 0.85, note: "blinding of participants & personnel", neg: true },
        { re: /(?:participants|patients|subjects)\s+(?:and\s+staff\s+)?(?:were\s+)?unaware\s+of\s+(?:their\s+)?(?:treatment|group|allocation)/i, w: 0.8, note: "participants unaware of allocation" },
      ],
      high: [
        { re: /open[\s-]?label/i, w: 0.85, note: "open-label" },
        { re: /(?:no|not|without|lack\s+of)\s+blind/i, w: 0.82, note: "no blinding" },
        { re: /\bunblind/i, w: 0.8, note: "unblinded" },
        { re: /blinding\s+(?:was\s+)?(?:not\s+(?:possible|feasible)|impractical)/i, w: 0.82, note: "blinding not possible" },
        { re: /participants?\s+(?:were\s+)?aware\s+of\s+(?:their\s+)?(?:treatment|allocation|group)/i, w: 0.78, note: "participants aware of allocation" },
      ],
    },

    detection: {
      key: "detection",
      name: "Blinding of outcome assessment",
      rob1: "blinding of outcome assessment (detection bias)",
      blurb: "Were outcome assessors blind to the assigned intervention?",
      low: [
        { re: /(?:outcome\s+)?assessors?\s+(?:were\s+)?(?:blind|mask)/i, w: 0.9, note: "assessors blinded", neg: true },
        { re: /blinded\s+(?:outcome\s+)?(?:assessment|assessor|evaluation|adjudicat)/i, w: 0.9, note: "blinded outcome assessment", neg: true },
        { re: /assessor[\s-]?(?:blind|mask)/i, w: 0.88, note: "assessor-blind", neg: true },
        { re: /(?:independent|central|masked)\s+(?:and\s+blinded\s+)?(?:outcome\s+)?(?:assessment|adjudicat|committee)/i, w: 0.8, note: "independent/masked assessment", neg: true },
        { re: /double[\s-]?blind/i, w: 0.78, note: "double-blind (covers assessors)", neg: true },
        { re: /outcome.{0,30}(?:assessed|measured|adjudicated)\s+by\s+(?:a\s+)?(?:blinded|masked|independent)/i, w: 0.82, note: "outcome assessed by blinded staff" },
        { re: /(?:technician|investigator|radiologist|laborator\w+|reader|adjudicat\w+|pathologist|microscopist|clinician|nurse|examiner)s?\s+(?:who\s+were\s+|were\s+)?(?:blind|mask)/i, w: 0.85, note: "assessing staff blinded", neg: true },
        { re: /blind(?:ed)?\s+to\s+(?:the\s+)?(?:clinical|treatment|group|allocation|intervention|assignment|study\s+arm)/i, w: 0.82, note: "assessor blinded to allocation", neg: true },
      ],
      high: [
        { re: /assessors?\s+(?:were\s+)?(?:aware|not\s+blind|unblind|unmask)/i, w: 0.85, note: "assessors aware" },
        { re: /(?:no|not|without|lack\s+of)\s+blind(?:ing)?\s+of\s+(?:the\s+)?(?:outcome|assess)/i, w: 0.82, note: "no blinding of assessment" },
        { re: /open[\s-]?label/i, w: 0.6, note: "open-label (assessment may be unblinded)" },
        { re: /self[\s-]?report(?:ed)?\s+outcome/i, w: 0.5, note: "self-reported (subjective) outcome" },
      ],
    },

    attrition: {
      key: "attrition",
      name: "Incomplete outcome data",
      rob1: "incomplete outcome data (attrition bias)",
      blurb: "Were outcome data complete, or missingness unlikely to bias the result?",
      low: [
        { re: /intention[\s-]?to[\s-]?treat/i, w: 0.85, note: "intention-to-treat analysis", neg: true },
        { re: /\bITT\b/, w: 0.78, note: "ITT", neg: true },
        { re: /no\s+(?:missing\s+(?:outcome\s+)?data|loss(?:es)?\s+to\s+follow|dropout|withdrawal|attrition)/i, w: 0.85, note: "no missing data / no loss to follow-up" },
        { re: /(?:complete|full)\s+(?:outcome\s+)?(?:data|follow[\s-]?up)\s+(?:was|were)?\s*(?:available|obtained|achieved)?/i, w: 0.72, note: "complete follow-up", neg: true },
        { re: /all\s+(?:randomi[sz]ed\s+)?(?:participants|patients|subjects)\s+(?:were\s+)?(?:analy[sz]ed|included\s+in\s+the\s+analysis)/i, w: 0.8, note: "all participants analysed", neg: true },
        { re: /multiple\s+imputation/i, w: 0.72, note: "multiple imputation", neg: true },
        { re: /(?:no(?:ne)?|0)\s+(?:participants?\s+|patients?\s+)?(?:were\s+)?(?:lost\s+to\s+follow|withdrew|excluded)/i, w: 0.78, note: "none lost / excluded" },
      ],
      high: [
        { re: /(?:high|substantial|large|considerable|significant)\s+(?:rate\s+of\s+)?(?:attrition|dropout|loss\s+to\s+follow)/i, w: 0.82, note: "high attrition" },
        { re: /differential\s+(?:dropout|attrition|loss|missing)/i, w: 0.85, note: "differential dropout" },
        { re: /excluded\s+(?:from\s+(?:the\s+)?analysis|after\s+randomi)/i, w: 0.72, note: "post-randomisation exclusions" },
        { re: /per[\s-]?protocol\s+(?:analysis|population)(?!.{0,40}intention)/i, w: 0.6, note: "per-protocol analysis only" },
        { re: /\b([2-9]\d|\d{3,})\s*%\s+(?:were\s+)?(?:lost|dropout|withdrew|missing|attrition)/i, w: 0.75, note: "large numeric dropout" },
      ],
    },

    reporting: {
      key: "reporting",
      name: "Selective reporting",
      rob1: "selective reporting (reporting bias)",
      blurb: "Were all pre-specified outcomes reported (protocol/registration available)?",
      low: [
        { re: /(?:prospectively\s+)?registered\s+(?:at|with|on|in)\s+(?:clinicaltrials|isrctn|the\s+)/i, w: 0.85, note: "prospectively registered" },
        { re: /\bNCT\d{6,}/, w: 0.85, note: "ClinicalTrials.gov NCT id" },
        { re: /\bISRCTN\d{6,}/i, w: 0.85, note: "ISRCTN id" },
        { re: /clinicaltrials\.gov/i, w: 0.78, note: "ClinicalTrials.gov" },
        { re: /(?:trial|study)\s+registration(?:\s+number)?/i, w: 0.7, note: "trial registration" },
        { re: /(?:study\s+|trial\s+)?protocol\s+(?:was\s+|is\s+|has\s+been\s+)?(?:available|published|registered|pre[\s-]?specified|followed)/i, w: 0.75, note: "protocol available/published" },
        { re: /pre[\s-]?specified\s+(?:primary\s+)?outcome/i, w: 0.72, note: "pre-specified outcomes" },
        { re: /all\s+(?:pre[\s-]?specified\s+)?(?:primary\s+(?:and\s+secondary\s+)?)?outcomes\s+(?:were\s+)?reported/i, w: 0.72, note: "all outcomes reported" },
      ],
      high: [
        { re: /(?:primary\s+)?outcome.{0,30}(?:not\s+(?:pre[\s-]?specified|reported)|changed|switched)/i, w: 0.78, note: "outcome not pre-specified / changed" },
        { re: /data\s+not\s+shown/i, w: 0.6, note: "data not shown" },
        { re: /post[\s-]?hoc\s+(?:analysis|outcome)/i, w: 0.55, note: "post-hoc outcome" },
        { re: /selective(?:ly)?\s+report/i, w: 0.7, note: "selective reporting" },
      ],
    },
  };

  // --- negation guard -------------------------------------------------------
  var NEG_RE = /\b(?:no|not|without|lack(?:ing|s)?(?:\s+of)?|fail(?:ed|s|ure)?|never|absence\s+of|did\s+not|was\s+not|were\s+not|n['e]?o)\b[^.;:]{0,18}$/i;

  function isNegated(text, idx) {
    var pre = text.slice(Math.max(0, idx - 28), idx);
    return NEG_RE.test(pre);
  }

  // --- sentence extraction around a match ----------------------------------
  function sentenceAround(text, idx, len) {
    // find sentence boundaries (. ! ? or newline) around [idx, idx+len)
    var start = idx, end = idx + len;
    for (var i = idx; i > 0 && idx - i < 400; i--) {
      var c = text[i - 1];
      if ((c === "." || c === "!" || c === "?" || c === "\n") && /\s/.test(text[i] || " ")) { start = i; break; }
      start = i - 1;
    }
    for (var j = end; j < text.length && j - end < 400; j++) {
      var d = text[j];
      if (d === "." || d === "!" || d === "?" || d === "\n") { end = j + 1; break; }
      end = j + 1;
    }
    return text.slice(start, end).replace(/\s+/g, " ").trim();
  }

  // --- core: score one domain over text ------------------------------------
  // Returns { judgment: 'low'|'high'|'unclear', confidence, sentence, cue, votes }
  function scoreDomain(text, domain) {
    if (!text || !domain) return { judgment: "unclear", confidence: 0, sentence: "", cue: "", votes: [] };
    var t = String(text);
    var best = { low: null, high: null };
    var votes = [];

    function scan(cues, side) {
      for (var k = 0; k < cues.length; k++) {
        var cue = cues[k];
        cue.re.lastIndex = 0;
        var m = cue.re.exec(t);
        if (!m) continue;
        if (cue.neg && isNegated(t, m.index)) continue; // negated low cue -> skip
        var rec = { side: side, w: cue.w, note: cue.note, idx: m.index, match: m[0] };
        votes.push(rec);
        if (!best[side] || cue.w > best[side].w) best[side] = rec;
      }
    }
    scan(domain.low, "low");
    scan(domain.high, "high");

    var lo = best.low, hi = best.high, winner = null;
    if (lo && hi) {
      // Strongest cue wins; ties -> high (precautionary, matches reviewer instinct).
      winner = hi.w >= lo.w ? hi : lo;
    } else winner = hi || lo;

    if (!winner) return { judgment: "unclear", confidence: 0.2, sentence: "", cue: "", votes: votes };

    var judgment = winner.side === "low" ? "low" : "high";
    // confidence: cue strength, tempered when an opposing cue of similar strength exists
    var opp = winner.side === "low" ? hi : lo;
    var conf = winner.w;
    if (opp) conf = Math.max(0.45, winner.w - 0.6 * opp.w);
    var sentence = sentenceAround(t, winner.idx, winner.match.length);
    return { judgment: judgment, confidence: +conf.toFixed(2), sentence: sentence, cue: winner.note, votes: votes };
  }

  // Map RoBBR/Cochrane bias string -> canonical domain key (for benchmarking).
  function canonicalDomain(biasString) {
    var b = String(biasString || "").toLowerCase();
    if (b.indexOf("random sequence") >= 0 || b.indexOf("sequence generation") >= 0) return "sequence";
    if (b.indexOf("allocation concealment") >= 0) return "allocation";
    if (b.indexOf("blinding of outcome") >= 0 || b.indexOf("detection bias") >= 0) return "detection";
    if (b.indexOf("blinding of participants") >= 0 || (b.indexOf("performance bias") >= 0 && b.indexOf("detection") < 0)) return "performance";
    if (b.indexOf("incomplete outcome") >= 0 || b.indexOf("attrition") >= 0 || b.indexOf("missing data") >= 0 || b.indexOf("missing outcome") >= 0) return "attrition";
    if (b.indexOf("selective reporting") >= 0 || b.indexOf("reporting bias") >= 0 || b.indexOf("selective outcome") >= 0) return "reporting";
    return null;
  }

  // --------------------------------------------------------------------------
  // 2. ROB 2 (Sterne 2019) — signalling questions + deterministic judge.
  //    The phrase engine pre-fills suggested answers; the reviewer edits.
  // --------------------------------------------------------------------------
  var ROB2_DOMAINS = [
    { id: "D1", name: "Randomization process", q: ["1.1", "1.2", "1.3"],
      questions: {
        "1.1": "Was the allocation sequence random?",
        "1.2": "Was the allocation sequence concealed until enrolment?",
        "1.3": "Did baseline differences suggest a problem with randomization?",
      },
      judge: function (a) {
        var yy = function (v) { return v === "Y" || v === "PY"; }, nn = function (v) { return v === "N" || v === "PN"; };
        // Sterne 2019 D1 algorithm: adequate sequence + concealment, with no
        // evidence of a baseline problem (N/PN/NI on 1.3), -> Low. Only a
        // positive baseline-imbalance signal (Y/PY on 1.3) blocks Low.
        if (yy(a["1.1"]) && yy(a["1.2"]) && !yy(a["1.3"])) return "low";
        if (nn(a["1.1"]) || nn(a["1.2"]) || yy(a["1.3"])) return "high";
        return "some";
      } },
    { id: "D2", name: "Deviations from intended interventions", q: ["2.1", "2.2", "2.5"],
      questions: {
        "2.1": "Were participants aware of their assigned intervention?",
        "2.2": "Were carers/those delivering interventions aware?",
        "2.5": "Was an appropriate (e.g. ITT) analysis used?",
      },
      judge: function (a) {
        var yy = function (v) { return v === "Y" || v === "PY"; }, nn = function (v) { return v === "N" || v === "PN"; };
        if (nn(a["2.5"])) return "high";
        if (!yy(a["2.1"]) && !yy(a["2.2"]) && yy(a["2.5"])) return "low";
        if (yy(a["2.5"])) return "some";
        return "some";
      } },
    { id: "D3", name: "Missing outcome data", q: ["3.1", "3.2"],
      questions: {
        "3.1": "Were outcome data available for all/nearly all participants?",
        "3.2": "Is there evidence the result was not biased by missing data?",
      },
      judge: function (a) {
        var yy = function (v) { return v === "Y" || v === "PY"; };
        if (yy(a["3.1"])) return "low";
        if (yy(a["3.2"])) return "low";
        return "some";
      } },
    { id: "D4", name: "Measurement of the outcome", q: ["4.1", "4.3"],
      questions: {
        "4.1": "Was the method of measuring the outcome inappropriate?",
        "4.3": "Were outcome assessors aware of the intervention received?",
      },
      judge: function (a) {
        var yy = function (v) { return v === "Y" || v === "PY"; }, nn = function (v) { return v === "N" || v === "PN"; };
        if (yy(a["4.1"])) return "high";
        if (nn(a["4.3"])) return "low";
        if (yy(a["4.3"])) return "some";
        return "some";
      } },
    { id: "D5", name: "Selection of the reported result", q: ["5.1", "5.2"],
      questions: {
        "5.1": "Was the result analysed per a pre-specified plan?",
        "5.2": "Was the result likely selected from multiple measurements/analyses?",
      },
      judge: function (a) {
        var yy = function (v) { return v === "Y" || v === "PY"; }, nn = function (v) { return v === "N" || v === "PN"; };
        if (yy(a["5.1"]) && nn(a["5.2"])) return "low";
        if (yy(a["5.2"])) return "high";
        return "some";
      } },
  ];

  // judgment(low/high/unclear) -> suggested signalling answer for a given question
  function answerFromJudgment(j, polarity) {
    // polarity: 'lowIsYes' (yes answer indicates low risk) or 'lowIsNo'.
    if (j === "low") return polarity === "lowIsYes" ? "PY" : "PN";
    if (j === "high") return polarity === "lowIsYes" ? "PN" : "PY";
    return "NI";
  }

  // Build RoB 2 suggestion for a study from its text.
  function suggestRoB2(text) {
    var seq = scoreDomain(text, DOMAINS.sequence);
    var alloc = scoreDomain(text, DOMAINS.allocation);
    var perf = scoreDomain(text, DOMAINS.performance);
    var det = scoreDomain(text, DOMAINS.detection);
    var attr = scoreDomain(text, DOMAINS.attrition);
    var rep = scoreDomain(text, DOMAINS.reporting);

    var answers = {
      D1: { "1.1": answerFromJudgment(seq.judgment, "lowIsYes"), "1.2": answerFromJudgment(alloc.judgment, "lowIsYes"), "1.3": "NI" },
      D2: { "2.1": perf.judgment === "high" ? "PY" : (perf.judgment === "low" ? "PN" : "NI"),
            "2.2": perf.judgment === "high" ? "PY" : (perf.judgment === "low" ? "PN" : "NI"),
            "2.5": answerFromJudgment(attr.judgment, "lowIsYes") },
      D3: { "3.1": answerFromJudgment(attr.judgment, "lowIsYes"), "3.2": attr.judgment === "low" ? "PY" : "NI" },
      D4: { "4.1": "PN", "4.3": det.judgment === "low" ? "PN" : (det.judgment === "high" ? "PY" : "NI") },
      D5: { "5.1": answerFromJudgment(rep.judgment, "lowIsYes"), "5.2": rep.judgment === "high" ? "PY" : "PN" },
    };
    var support = { D1: seq.sentence || alloc.sentence, D2: perf.sentence, D3: attr.sentence, D4: det.sentence, D5: rep.sentence };
    var cues = { D1: seq.cue || alloc.cue, D2: perf.cue, D3: attr.cue, D4: det.cue, D5: rep.cue };
    var conf = { D1: Math.max(seq.confidence, alloc.confidence), D2: perf.confidence, D3: attr.confidence, D4: det.confidence, D5: rep.confidence };

    var verdicts = {};
    for (var i = 0; i < ROB2_DOMAINS.length; i++) {
      var d = ROB2_DOMAINS[i];
      verdicts[d.id] = d.judge(answers[d.id]);
    }
    verdicts.overall = overallRoB2(verdicts);
    return { framework: "RoB2", answers: answers, verdicts: verdicts, support: support, cues: cues, confidence: conf,
             raw: { sequence: seq, allocation: alloc, performance: perf, detection: det, attrition: attr, reporting: rep } };
  }

  function overallRoB2(v) {
    var ids = ["D1", "D2", "D3", "D4", "D5"], vals = [];
    for (var i = 0; i < ids.length; i++) vals.push(v[ids[i]]);
    if (vals.every(function (x) { return x === "low"; })) return "low";
    if (vals.some(function (x) { return x === "high"; })) return "high";
    return "some";
  }

  // --------------------------------------------------------------------------
  // 3. ROBINS-I (Sterne 2016) — domain scaffold + light phrase cues.
  //    Non-randomized studies. Judgments: low | moderate | serious | critical | NI.
  // --------------------------------------------------------------------------
  var ROBINSI_DOMAINS = [
    { id: "D1", name: "Confounding", maps: null,
      cue: { low: /(?:propensity\s+score|multivariable\s+adjust|adjusted\s+for\s+confound|inverse\s+probability|matched\s+(?:on|for)|instrumental\s+variable)/i,
             high: /(?:no\s+adjustment|unadjusted|did\s+not\s+(?:adjust|control)\s+for|crude\s+(?:estimate|analysis))/i } },
    { id: "D2", name: "Selection of participants", maps: null,
      cue: { low: /(?:consecutive\s+(?:patients|participants)|all\s+eligible|inception\s+cohort|prospectively\s+enrolled)/i,
             high: /(?:selected\s+based\s+on|prevalent\s+(?:cases|users)|survivor|immortal\s+time)/i } },
    { id: "D3", name: "Classification of interventions", maps: null,
      cue: { low: /(?:intervention\s+(?:status|groups?)\s+(?:were\s+)?(?:well[\s-]?defined|recorded\s+at\s+baseline|prospectively))/i,
             high: /(?:misclassif|recall\s+bias|self[\s-]?report(?:ed)?\s+(?:exposure|intervention))/i } },
    { id: "D4", name: "Deviations from intended interventions", maps: "performance" },
    { id: "D5", name: "Missing data", maps: "attrition" },
    { id: "D6", name: "Measurement of outcomes", maps: "detection" },
    { id: "D7", name: "Selection of the reported result", maps: "reporting" },
  ];

  function suggestRobinsI(text) {
    var out = { framework: "ROBINS-I", verdicts: {}, support: {}, cues: {}, confidence: {} };
    for (var i = 0; i < ROBINSI_DOMAINS.length; i++) {
      var d = ROBINSI_DOMAINS[i], j, sent = "", cue = "", conf = 0;
      if (d.maps) {
        var s = scoreDomain(text, DOMAINS[d.maps]);
        j = s.judgment === "low" ? "low" : (s.judgment === "high" ? "serious" : "moderate");
        sent = s.sentence; cue = s.cue; conf = s.confidence;
      } else {
        var lowM = d.cue.low.exec(text || ""), highM = d.cue.high.exec(text || "");
        if (highM) { j = "serious"; sent = sentenceAround(text, highM.index, highM[0].length); cue = "ROBINS-I high cue"; conf = 0.7; }
        else if (lowM) { j = "low"; sent = sentenceAround(text, lowM.index, lowM[0].length); cue = "ROBINS-I low cue"; conf = 0.7; }
        else { j = "moderate"; conf = 0.2; }
      }
      out.verdicts[d.id] = j; out.support[d.id] = sent; out.cues[d.id] = cue; out.confidence[d.id] = conf;
    }
    var order = { low: 0, moderate: 1, serious: 2, critical: 3 }, worst = "low";
    for (var k in out.verdicts) if (order[out.verdicts[k]] > order[worst]) worst = out.verdicts[k];
    out.verdicts.overall = worst;
    return out;
  }

  // --------------------------------------------------------------------------
  // 4. Public API
  // --------------------------------------------------------------------------
  var RobCore = {
    VERSION: "rob-core-v1",
    DOMAINS: DOMAINS,
    ROB2_DOMAINS: ROB2_DOMAINS,
    ROBINSI_DOMAINS: ROBINSI_DOMAINS,
    scoreDomain: scoreDomain,
    canonicalDomain: canonicalDomain,
    suggestRoB2: suggestRoB2,
    suggestRobinsI: suggestRobinsI,
    overallRoB2: overallRoB2,
    sentenceAround: sentenceAround,
    // Benchmark helper: predict low/high/unclear for a canonical domain.
    // For the RobotReviewer head-to-head we collapse to binary downstream.
    predict: function (text, biasString) {
      var key = canonicalDomain(biasString);
      if (!key) return { judgment: "unclear", confidence: 0, sentence: "", cue: "", domain: null };
      var s = scoreDomain(text, DOMAINS[key]);
      s.domain = key;
      return s;
    },
  };

  if (typeof module !== "undefined" && module.exports) module.exports = RobCore;
  if (typeof window !== "undefined") window.RobCore = RobCore;
  if (root) root.RobCore = RobCore;
})(typeof globalThis !== "undefined" ? globalThis : this);
