#!/usr/bin/env python
"""Quarterly-review snapshot generator.

Produces an accurate, evidence-based starting point for the next Multi-Persona
Review (review-findings-vN.md) so the cycle never relies on memory:
  - the live DEFERRED list, parsed straight from ROADMAP.md open boxes
    ([ ] not started, [~] partial) with their phase heading;
  - shipped-asset lint status (scripts/lint_repo.py);
  - parity-ledger headline (R-parity tests / assertions / oracles);
  - catalog app count (hub/projects.js).

Usage:
  python scripts/review_cycle.py                 # markdown snapshot to stdout
  python scripts/review_cycle.py --out FILE.md   # also write to FILE

Run it at the start of each quarterly cycle (see REVIEW-CYCLE.md), paste the
output under a new review-findings-vN.md, and triage the deferred list down.
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def deferred_items() -> list[tuple[str, str]]:
    """(phase heading, item text) for every open [ ] / [~] box in ROADMAP.md."""
    out: list[tuple[str, str]] = []
    phase = "(preamble)"
    for line in (ROOT / "ROADMAP.md").read_text(encoding="utf-8").splitlines():
        h = re.match(r"^#{2,4}\s+(.*)", line)
        if h:
            phase = h.group(1).strip()
            continue
        m = re.match(r"^\s*- \[([ ~])\]\s+(.*)", line)
        if m:
            mark = "not started" if m.group(1) == " " else "partial"
            text = re.sub(r"\s+", " ", m.group(2)).strip()
            out.append((phase, f"[{mark}] {text[:160]}"))
    return out


def lint_status() -> str:
    r = subprocess.run([sys.executable, str(ROOT / "scripts" / "lint_repo.py")],
                       capture_output=True, text=True)
    last = (r.stdout.strip().splitlines() or ["(no output)"])[-1]
    return ("CLEAN — " if r.returncode == 0 else "VIOLATIONS — ") + last


def parity_headline() -> str:
    try:
        js = (ROOT / "parity" / "parity-ledger.js").read_text(encoding="utf-8")
    except FileNotFoundError:
        return "(parity-ledger.js missing)"
    def g(k):
        m = re.search(rf'"{k}":\s*(\d+)', js)
        return m.group(1) if m else "?"
    return (f'{g("parityTestCount")} R-parity tests '
            f'({g("specCount")} Playwright + {g("pyCount")} Python), '
            f'{int(g("assertionCount")) + int(g("pyAssertionCount") or 0)} assertions, '
            f'{g("oracleCount")} R oracles')


def catalog_count() -> int:
    proj = (ROOT / "hub" / "projects.js").read_text(encoding="utf-8", errors="replace")
    return len(re.findall(r'path:\s*"\./', proj))


def render() -> str:
    items = deferred_items()
    by_phase: dict[str, list[str]] = {}
    for phase, txt in items:
        by_phase.setdefault(phase, []).append(txt)
    L = ["# Quarterly review — prep snapshot",
         "",
         "> Auto-generated by `scripts/review_cycle.py`. Stamp the date + commit",
         "> when you start the cycle; see `REVIEW-CYCLE.md` for the protocol.",
         "",
         "## Health",
         f"- Catalog apps: **{catalog_count()}**",
         f"- Parity: **{parity_headline()}**",
         f"- Shipped-asset lint: **{lint_status()}**",
         "",
         f"## Deferred list ({len(items)} open items)",
         ""]
    if not items:
        L.append("_No open items in ROADMAP.md — the deferred list is empty._")
    for phase, txts in by_phase.items():
        L.append(f"### {phase}")
        L.extend(f"- {t}" for t in txts)
        L.append("")
    L += ["## Review checklist (4 personas)",
          "- **Methods** — statistical correctness vs R; new findings in `advanced-stats.md`?",
          "- **Engineering** — lint clean, no regressions, test counts holding, CSP intact.",
          "- **A11y** — `a11y-sweep` green; forced-colors / reduced-motion respected.",
          "- **Domain** — claims match implementation; citations/identifiers verified.",
          "",
          "Goal: triage the deferred list **down**, not up. Close or explicitly",
          "re-scope each item; record the verdict in the new `review-findings-vN.md`."]
    return "\n".join(L) + "\n"


def main() -> int:
    # Windows console defaults to cp1252 and mangles em-dashes / bullets in the
    # snapshot (lessons.md). Re-wrap stdout to UTF-8 here (inside main, not at
    # module level, so pytest's capture is never disturbed).
    if getattr(sys.stdout, "encoding", "").lower() not in ("utf-8", "utf8"):
        import io
        sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    md = render()
    sys.stdout.write(md)
    if "--out" in sys.argv:
        dst = Path(sys.argv[sys.argv.index("--out") + 1])
        dst.write_text(md, encoding="utf-8")
        sys.stderr.write(f"\n[review_cycle] wrote {dst}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
