/* AUTO-GENERATED by scripts/build-parity-ledger.mjs — do not edit by hand. */
window.ALM_PARITY_LEDGER = {
  "generated": "2026-06-01",
  "specCount": 43,
  "assertionCount": 173,
  "oracleCount": 32,
  "stataCount": 26,
  "rows": [
    {
      "spec": "bayesian-ma-parity.spec.mjs",
      "title": "bayesian-ma-parity.spec.mjs — conjugate normal-normal R-parity.\r  bayesian-ma is",
      "module": null,
      "oracles": [
        "metafor"
      ],
      "stata": null,
      "tests": 2,
      "asserts": 0,
      "tightestDecimals": null
    },
    {
      "spec": "bayesian-mcmc-parity.spec.mjs",
      "title": "bayesian-mcmc-parity.spec.mjs — Gibbs sampler validation (done right).\r  A real ",
      "module": null,
      "oracles": [
        "analytic/conjugate (R-checked)"
      ],
      "stata": null,
      "tests": 2,
      "asserts": 0,
      "tightestDecimals": null
    },
    {
      "spec": "bayesian-nma-parity.spec.mjs",
      "title": "bayesian-nma-parity.spec.mjs — approximate-Bayes NMA R-parity.\r  WLS consistency",
      "module": null,
      "oracles": [
        "netmeta"
      ],
      "stata": null,
      "tests": 2,
      "asserts": 0,
      "tightestDecimals": null
    },
    {
      "spec": "component-nma-parity.spec.mjs",
      "title": "component-nma-parity.spec.mjs — additive CNMA R-parity vs netmeta::discomb.\r  Th",
      "module": null,
      "oracles": [
        "meta::discomb",
        "netmeta::discomb"
      ],
      "stata": "network / mvmeta (NMA)",
      "tests": 2,
      "asserts": 0,
      "tightestDecimals": null
    },
    {
      "spec": "copas-parity.spec.mjs",
      "title": "copas-parity.spec.mjs — Copas & Shi (2000) profile-MLE R-parity.\r  The copas app",
      "module": null,
      "oracles": [
        "R (formula-checked)"
      ],
      "stata": "meta bias / estat",
      "tests": 1,
      "asserts": 0,
      "tightestDecimals": null
    },
    {
      "spec": "correlation-ma-parity.spec.mjs",
      "title": "the correlation meta-analysis app",
      "module": null,
      "oracles": [
        "metafor::escalc"
      ],
      "stata": "meta summarize / meta esize",
      "tests": 2,
      "asserts": 7,
      "tightestDecimals": 5
    },
    {
      "spec": "diagnostic-plots-parity.spec.mjs",
      "title": "the three diagnostic-plot coordinate engines (shared/diagnostic-plots",
      "module": "diagnostic-plots.js",
      "oracles": [
        "metafor::baujat",
        "metafor::radial",
        "metafor::labbe"
      ],
      "stata": "meta galbraith / meta labbe",
      "tests": 7,
      "asserts": 8,
      "tightestDecimals": 8
    },
    {
      "spec": "doi-lfk-parity.spec.mjs",
      "title": "the Doi plot / LFK index (shared/doi-lfk",
      "module": "doi-lfk.js",
      "oracles": [
        "metasens::lfkindex"
      ],
      "stata": null,
      "tests": 3,
      "asserts": 2,
      "tightestDecimals": 5
    },
    {
      "spec": "dose-response-parity.spec.mjs",
      "title": "two-stage linear dose-response MA (shared/dose-response",
      "module": "dose-response.js",
      "oracles": [
        "dosresmeta(formula=logrr~dose, method=\"reml\")",
        "dosresmeta"
      ],
      "stata": "drmeta (package)",
      "tests": 3,
      "asserts": 3,
      "tightestDecimals": 5
    },
    {
      "spec": "dose-response-spline-parity.spec.mjs",
      "title": "NON-LINEAR (restricted cubic spline) dose-response MA (shared/dose-response",
      "module": "dose-response.js",
      "oracles": [
        "dosresmeta(logrr ~ rcs(dose,3)",
        "dosresmeta"
      ],
      "stata": "drmeta (package)",
      "tests": 5,
      "asserts": 15,
      "tightestDecimals": 6
    },
    {
      "spec": "dta-bivariate-parity.spec.mjs",
      "title": "the PURE-JS bivariate random-effects DTA MLE (shared/dta-bivariate",
      "module": "dta-bivariate.js",
      "oracles": [
        "mada::reitsma"
      ],
      "stata": "metandi / midas (DTA)",
      "tests": 3,
      "asserts": 7,
      "tightestDecimals": 4
    },
    {
      "spec": "dta-region-parity.spec.mjs",
      "title": "the bivariate DTA region ellipses (AlmDTABivariate",
      "module": null,
      "oracles": [
        "mada"
      ],
      "stata": "metandi / midas (DTA)",
      "tests": 2,
      "asserts": 12,
      "tightestDecimals": 9
    },
    {
      "spec": "dta-sroc-parity.spec.mjs",
      "title": "the dta-sroc Moses-Littenberg SROC regression",
      "module": null,
      "oracles": [],
      "stata": "metandi / midas (DTA)",
      "tests": 3,
      "asserts": 6,
      "tightestDecimals": 6
    },
    {
      "spec": "evalue-parity.spec.mjs",
      "title": "the E-value (shared/evalue",
      "module": "evalue.js",
      "oracles": [
        "EValue"
      ],
      "stata": "evalue (package)",
      "tests": 3,
      "asserts": 10,
      "tightestDecimals": 5
    },
    {
      "spec": "fragility-parity.spec.mjs",
      "title": "the meta-analysis fragility index (shared/fragility",
      "module": "fragility.js",
      "oracles": [
        "fragility::frag"
      ],
      "stata": null,
      "tests": 3,
      "asserts": 1,
      "tightestDecimals": 4
    },
    {
      "spec": "gosh-metareg-parity.spec.mjs",
      "title": "gosh-metareg-parity.spec.mjs — meta-regression R-parity vs metafor.\r  After the ",
      "module": null,
      "oracles": [
        "metafor::rma"
      ],
      "stata": null,
      "tests": 2,
      "asserts": 0,
      "tightestDecimals": null
    },
    {
      "spec": "km-reconstructor-parity.spec.mjs",
      "title": "km-reconstructor-parity.spec.mjs — KM IPD reconstruction validation.\r  The app i",
      "module": null,
      "oracles": [
        "R (formula-checked)"
      ],
      "stata": null,
      "tests": 2,
      "asserts": 0,
      "tightestDecimals": null
    },
    {
      "spec": "limit-ma-parity.spec.mjs",
      "title": "limit-ma-parity.spec.mjs — Rücker (2011) limit meta-analysis R-parity.\r  The lim",
      "module": null,
      "oracles": [
        "metasens::limitmeta"
      ],
      "stata": null,
      "tests": 1,
      "asserts": 0,
      "tightestDecimals": null
    },
    {
      "spec": "location-scale-parity.spec.mjs",
      "title": "the location-scale meta-regression engine (shared/location-scale",
      "module": "location-scale.js",
      "oracles": [
        "metafor::rma"
      ],
      "stata": "meta regress (no scale submodel in Stata)",
      "tests": 4,
      "asserts": 9,
      "tightestDecimals": 5
    },
    {
      "spec": "ma-core-parity.spec.mjs",
      "title": "the audited single-source pooler shared/ma-core",
      "module": "ma-core.js",
      "oracles": [
        "metafor::rma"
      ],
      "stata": "meta summarize / meta esize",
      "tests": 4,
      "asserts": 14,
      "tightestDecimals": 10
    },
    {
      "spec": "mcid-parity.spec.mjs",
      "title": "mcid-parity.spec.mjs — MCID rule-arithmetic + exact-qnorm guard.\r  mcid is deter",
      "module": null,
      "oracles": [
        "R (base stats)"
      ],
      "stata": null,
      "tests": 2,
      "asserts": 0,
      "tightestDecimals": null
    },
    {
      "spec": "median-to-mean-parity.spec.mjs",
      "title": "median-to-mean-parity.spec.mjs — Wan/Luo/Shi R-parity.\r  Oracle = the published ",
      "module": null,
      "oracles": [
        "R (base stats)"
      ],
      "stata": null,
      "tests": 2,
      "asserts": 0,
      "tightestDecimals": null
    },
    {
      "spec": "multi-outcome-ma-parity.spec.mjs",
      "title": "the bivariate (multi-outcome) random-effects MA engine",
      "module": null,
      "oracles": [
        "metafor::rma.mv"
      ],
      "stata": null,
      "tests": 2,
      "asserts": 11,
      "tightestDecimals": 5
    },
    {
      "spec": "multilevel-reml-parity.spec.mjs",
      "title": "the three-level (multilevel) REML engine (shared/multilevel-reml",
      "module": "multilevel-reml.js",
      "oracles": [
        "metafor::rma.mv"
      ],
      "stata": null,
      "tests": 3,
      "asserts": 5,
      "tightestDecimals": 5
    },
    {
      "spec": "multivariate-ma-parity.spec.mjs",
      "title": "multivariate / multiple-outcome meta-analysis (shared/multivariate-ma",
      "module": "multivariate-ma.js",
      "oracles": [
        "metafor::rma.mv"
      ],
      "stata": "mvmeta (package)",
      "tests": 3,
      "asserts": 8,
      "tightestDecimals": 5
    },
    {
      "spec": "nma-global-inconsistency-parity.spec.mjs",
      "title": "nma-global-inconsistency-parity.spec.mjs — netmeta decomp.design R-parity.\r  App",
      "module": null,
      "oracles": [
        "netmeta"
      ],
      "stata": "network / mvmeta (NMA)",
      "tests": 2,
      "asserts": 0,
      "tightestDecimals": null
    },
    {
      "spec": "nma-inconsistency-parity.spec.mjs",
      "title": "nma-inconsistency-parity.spec.mjs — netmeta FE R-parity.\r  The app is fixed-effe",
      "module": null,
      "oracles": [
        "netmeta"
      ],
      "stata": "network / mvmeta (NMA)",
      "tests": 2,
      "asserts": 0,
      "tightestDecimals": null
    },
    {
      "spec": "nma-meta-reg-parity.spec.mjs",
      "title": "the network meta-regression engine",
      "module": null,
      "oracles": [
        "meta::netmetareg",
        "netmeta::netmetareg"
      ],
      "stata": "network / mvmeta (NMA)",
      "tests": 1,
      "asserts": 4,
      "tightestDecimals": 6
    },
    {
      "spec": "nma-parity.spec.mjs",
      "title": "nma-parity.spec.mjs — basic frequentist NMA R-parity vs netmeta.\r  Consistent fi",
      "module": null,
      "oracles": [
        "netmeta"
      ],
      "stata": "network / mvmeta (NMA)",
      "tests": 2,
      "asserts": 0,
      "tightestDecimals": null
    },
    {
      "spec": "personalised-te-parity.spec.mjs",
      "title": "the personalised-TE empirical-Bayes shrinkage engine",
      "module": null,
      "oracles": [
        "metafor::blup"
      ],
      "stata": null,
      "tests": 1,
      "asserts": 4,
      "tightestDecimals": 5
    },
    {
      "spec": "powerma-parity.spec.mjs",
      "title": "powerma-parity.spec.mjs — pre-MA sample size / RIS R-parity.\r  Oracle = the docu",
      "module": null,
      "oracles": [
        "R (base stats)"
      ],
      "stata": null,
      "tests": 2,
      "asserts": 0,
      "tightestDecimals": null
    },
    {
      "spec": "pubbias-binary-parity.spec.mjs",
      "title": "the binary small-study tests",
      "module": null,
      "oracles": [
        "meta::metabias"
      ],
      "stata": "meta bias / estat",
      "tests": 1,
      "asserts": 2,
      "tightestDecimals": 2
    },
    {
      "spec": "rare-events-cmel-parity.spec.mjs",
      "title": "the CM",
      "module": null,
      "oracles": [
        "metafor::rma.glmm"
      ],
      "stata": null,
      "tests": 3,
      "asserts": 3,
      "tightestDecimals": 5
    },
    {
      "spec": "rare-events-glmm-parity.spec.mjs",
      "title": "the rare-events binomial-normal GLMM (UM",
      "module": null,
      "oracles": [
        "metafor"
      ],
      "stata": "meta esize, exact / metan",
      "tests": 6,
      "asserts": 12,
      "tightestDecimals": 4
    },
    {
      "spec": "reml-validator-parity.spec.mjs",
      "title": "the webr-validator's browser fit (browserFit → AlmMaCore",
      "module": null,
      "oracles": [
        "metafor::rma"
      ],
      "stata": null,
      "tests": 2,
      "asserts": 1,
      "tightestDecimals": 5
    },
    {
      "spec": "rmst-ma-parity.spec.mjs",
      "title": "RMST meta-analysis",
      "module": null,
      "oracles": [
        "metafor::rma"
      ],
      "stata": "meta summarize (RMST diffs)",
      "tests": 2,
      "asserts": 4,
      "tightestDecimals": 5
    },
    {
      "spec": "robma-parity.spec.mjs",
      "title": "the RoBMA-style robust Bayesian MA (shared/robma",
      "module": "robma.js",
      "oracles": [
        "RoBMA"
      ],
      "stata": null,
      "tests": 3,
      "asserts": 6,
      "tightestDecimals": 9
    },
    {
      "spec": "rve-meta-cr2-parity.spec.mjs",
      "title": "the CR2 bias-reduced RVE (Tipton 2015; Pustejovsky-Tipton 2018) with HTJ CORR-model τ² and per-coefficient Satterthwaite df",
      "module": null,
      "oracles": [
        "robumeta",
        "meta::robu"
      ],
      "stata": "robumeta (package)",
      "tests": 3,
      "asserts": 4,
      "tightestDecimals": 6
    },
    {
      "spec": "rve-meta-parity.spec.mjs",
      "title": "the RVE (Hedges-Tipton-Johnson CORR) meta-regression engine",
      "module": null,
      "oracles": [
        "robumeta",
        "meta::robu"
      ],
      "stata": "robumeta (package)",
      "tests": 1,
      "asserts": 2,
      "tightestDecimals": 6
    },
    {
      "spec": "selmodel-parity.spec.mjs",
      "title": "the Vevea-Hedges step-function selection model (shared/selmodel",
      "module": "selmodel.js",
      "oracles": [
        "metafor::selmodel"
      ],
      "stata": "meta bias / estat",
      "tests": 3,
      "asserts": 6,
      "tightestDecimals": 4
    },
    {
      "spec": "trimfill-parity.spec.mjs",
      "title": "Duval-Tweedie trim-and-fill (shared/trimfill",
      "module": "trimfill.js",
      "oracles": [
        "metafor::trimfill"
      ],
      "stata": "meta trimfill",
      "tests": 3,
      "asserts": 7,
      "tightestDecimals": 8
    },
    {
      "spec": "tsa-parity.spec.mjs",
      "title": "tsa-parity.spec.mjs — Trial Sequential Analysis R-parity.\r  Oracle = the advance",
      "module": null,
      "oracles": [
        "R (base stats)"
      ],
      "stata": "metacumbounds (package)",
      "tests": 2,
      "asserts": 0,
      "tightestDecimals": null
    },
    {
      "spec": "workbench-parity.spec.mjs",
      "title": "workbench-parity.spec.mjs — MA Workbench canonical Paule-Mandel\r random-effects ",
      "module": null,
      "oracles": [
        "metafor"
      ],
      "stata": "meta summarize / meta esize",
      "tests": 2,
      "asserts": 0,
      "tightestDecimals": null
    }
  ]
};
