window.HTML_APPS_PROJECTS = [
  {
    name: "RoB (automated)",
    featured: true,
    course: "https://mahmood726-cyber.github.io/synthesis-courses/risk-of-bias-mastery-course.html",
    folder: "allmeta/rob",
    path: "./rob/index.html",
    added: "2026-06-08",
    collection: "new",
    mode: "file",
    category: "Risk of Bias",
    summary: "Automated Risk-of-Bias assessment for RoB 2 (randomized trials) and ROBINS-I (non-randomized). Paste each study's abstract/methods (or pull from Extract via the sr-extract-v1 / ma-studies-v1 bus); a free in-browser phrase engine reads Cochrane signalling cues and SUGGESTS a per-domain low/some/high judgment with the supporting sentence it keyed on. Every suggestion is reviewer-confirmed or overridden — never auto-final (Screen pattern). Outputs a RoB table + traffic-light figure, feeding the synthesis/MA apps and PRISMA. Optional AI via agent-handoff / BYO-key. Honestly benchmarked: 62.6 vs RobotReviewer 56.7 Macro-F1 on the RoBBR gold subset [measured].",
    note: "Completes the Design → Search → Screen → Extract → RoB → synthesis pipeline. Beats RobotReviewer on the RoBBR head-to-head (3 of 4 domains); below frontier LLMs. Reproduce: node benchmark/run_rob_benchmark.mjs.",
    tags: ["risk-of-bias", "rob2", "robins-i", "automated", "signalling-questions", "robotreviewer", "traffic-light", "pipeline"]
  },
  {
    name: "RCT Extractor",
    featured: true,
    course: "https://mahmood726-cyber.github.io/synthesis-courses/ai-meta-analysis-course.html",
    folder: "allmeta/rct-extractor",
    path: "./rct-extractor/index.html",
    added: "2026-04-21",
    collection: "existing",
    mode: "file",
    category: "Screening & Extraction",
    summary: "Extract effect estimates (HR, OR, RR, MD, SMD, IRR, RD) from RCT publications via a locally-running rct-extractor-v2 FastAPI server (180+ regex patterns, 97.7% sensitivity). Optional local-LLM consensus layer, PDF upload with browser-side text extraction, one-click hand-off to MA Workbench / Forest Plot Viewer.",
    note: "Requires a one-time Python install; see the in-app hint.",
    tags: ["extraction", "pdf", "rct", "regex", "fastapi"]
  },
  {
    name: "RevMan Importer",
    featured: true,
    folder: "allmeta/revman-importer",
    path: "./revman-importer/",
    added: "2026-05-24",
    collection: "new",
    mode: "file",
    category: "Screening & Extraction",
    summary: "Drop a Cochrane RevMan .rm5 / .rm6 file; this app reads the comparisons (DICH, CONTINUOUS, and O-E-Variance), lists the studies, and pushes the selected comparison into the shared ma-comparisons-v1 bus so nma-pro-v2 / forest-plot / bayesian-nma can load it without re-typing.",
    note: "100% browser-side; nothing is uploaded. JSZip vendored under shared/vendor/.",
    tags: ["revman", "cochrane", "rm5", "rm6", "import", "extraction"]
  },
  {
    name: "Cross-network synthesis (NMA + IPD + obs)",
    featured: true,
    folder: "allmeta/cross-network",
    path: "./cross-network/",
    added: "2026-05-24",
    collection: "new",
    mode: "file",
    category: "Network MA",
    summary: "Combine RCT NMA + IPD trial-level + observational evidence under a unified bias model. Per-contrast design-bias δ_design + bias variance σ²_design estimated by method of moments against the RCT anchor.",
    note: "References: Welton, Cooper, Ades, Lu, Sutton 2009 (Stat Med); Efthimiou et al. 2017 'GetReal in NMA' (Res Synth Methods 8:23-39).",
    tags: ["cross-network", "ipd", "observational", "bias-corrected", "synthesis", "welton"]
  },
  {
    name: "Everything model (outcome × time × RoB)",
    featured: true,
    folder: "allmeta/everything-model",
    path: "./everything-model/",
    added: "2026-05-24",
    collection: "new",
    mode: "file",
    category: "Living Evidence",
    summary: "Joint Bayesian hierarchical model decomposing each effect into outcome mean μ_o + study RE δ_i + time period γ_t + optional RoB shift. Variational EM, browser-tractable. The unifying frame for multi-outcome × multi-snapshot living-evidence syntheses.",
    note: "Variational EM converges in 50-200 iterations. Closed-form analytic posterior at fixed variance components.",
    tags: ["bayesian", "hierarchical", "multi-outcome", "time-varying", "rob", "variational-em"]
  },
  {
    name: "Sequential MA (α-spending)",
    featured: true,
    folder: "allmeta/sequential-ma",
    path: "./sequential-ma/",
    added: "2026-05-24",
    collection: "new",
    mode: "file",
    category: "Trial Sequential Analysis",
    summary: "Adaptive-design TSA with α-spending boundaries (O'Brien-Fleming, Pocock, linear) at each look + optional β-spending futility. Avoids the multiple-comparisons inflation of naive cumulative testing.",
    note: "References: Lan & DeMets 1983 (Biometrika); O'Brien-Fleming 1979 (Biometrics); Wetterslev et al. 2008 (Clin Epidemiol) on TSA.",
    tags: ["sequential", "tsa", "alpha-spending", "obrien-fleming", "pocock", "futility"]
  },
  {
    name: "Personalised TE (subgroup shrinkage)",
    featured: true,
    folder: "allmeta/personalised-te",
    path: "./personalised-te/",
    added: "2026-05-24",
    collection: "new",
    mode: "file",
    category: "Pairwise MA",
    summary: "Empirical Bayes shrinkage of subgroup-specific effect estimates toward the overall pooled effect. Personalised prediction: returns the EB posterior for a patient's subgroup label, or falls back to overall when the subgroup wasn't observed.",
    note: "References: Kent et al. 2018 PATH Statement (Ann Intern Med 172:35-45); Morris 1983 posterior variance; James-Stein / EB classics.",
    tags: ["personalised", "subgroup", "shrinkage", "empirical-bayes", "path", "hte"]
  },
  {
    name: "Rare-events GLMM",
    featured: true,
    folder: "allmeta/rare-events-glmm",
    path: "./rare-events-glmm/",
    added: "2026-05-24",
    collection: "new",
    mode: "file",
    category: "Pairwise MA",
    summary: "Binomial-normal random-effects logistic regression for rare-event meta-analysis. Avoids the +0.5 continuity correction that biases OR pooling toward the null. Both conditional (CM.AL, fast) and unconditional (UM.FS, full-likelihood) variants — 10-point Gauss-Hermite quadrature + damped Newton-Raphson on (θ, log τ).",
    note: "Reference: Stijnen, Hamza, Ozdemir 2010 (Stat Med 29:3046-3067). UM.FS matches metafor::rma.glmm(model='UM.FS') within Hermite precision.",
    tags: ["glmm", "rare-events", "binomial", "stijnen", "zero-cells", "logistic-re"]
  },
  {
    name: "Living RoB pool",
    featured: true,
    folder: "allmeta/living-rob-pool",
    path: "./living-rob-pool/",
    added: "2026-05-24",
    collection: "new",
    mode: "file",
    category: "Living Evidence",
    summary: "Living-evidence pooling with time-varying RoB. Each snapshot uses each study's RoB AS RATED ON or before that date, so the pool's drift reflects BOTH new studies AND updated judgements on existing ones — the two reasons a living systematic review's bottom line moves.",
    note: "Default RoB → bias mapping: low=0, some=0.25, high=0.5. Pairs naturally with the EvidenceOS living-evidence cron + GH Actions update.",
    tags: ["living-evidence", "time-varying-rob", "snapshots", "drift", "rob2", "sensitivity"]
  },
  {
    name: "Network meta-regression",
    featured: true,
    folder: "allmeta/nma-meta-reg",
    path: "./nma-meta-reg/",
    added: "2026-05-24",
    collection: "new",
    mode: "file",
    category: "Network MA",
    summary: "NMA with a study-level covariate × treatment interaction. Each non-reference treatment gets its own slope γ_k. Centred at the covariate mean for interpretability; predictions at arbitrary covariate values come with proper SEs accounting for Cov(β̂, γ̂). PM τ² + GLS.",
    note: "Reference: Cooper et al. 2009 (Stat Med); Dias et al. 2018 NICE DSU TSD 3. Single-covariate; fit separately for each covariate of interest.",
    tags: ["nma", "meta-regression", "covariate", "interaction", "cooper", "nice-tsd"]
  },
  {
    name: "Multi-outcome NMA (Achana 2014)",
    featured: true,
    folder: "allmeta/multi-outcome-nma",
    path: "./multi-outcome-nma/",
    added: "2026-05-24",
    collection: "new",
    mode: "file",
    category: "Network MA",
    summary: "Multi-arm × multi-outcome network meta-analysis with joint random-effects pooling. Σ_per_study = Σ_RE^outcomes ⊗ G_arm (G_arm has 1 on diag, 0.5 off — the multi-arm shared-control correction). β̂ via GLS with block-diagonal Σ.",
    note: "Reference: Achana et al. 2014 §3.2 Res Synth Methods 5:35-49. Handles missing outcomes per study; borrows strength across correlated outcomes.",
    tags: ["nma", "multi-outcome", "multi-arm", "achana", "kronecker", "borrowing"]
  },
  {
    name: "Multi-outcome MA (bivariate REML)",
    featured: true,
    folder: "allmeta/multi-outcome-ma",
    path: "./multi-outcome-ma/",
    added: "2026-05-24",
    collection: "new",
    mode: "file",
    category: "Pairwise MA",
    summary: "Bivariate (K=2) random-effects meta-analysis with REML estimation of the 2×2 between-study covariance Σ_RE = (τ₁, τ₂, ρ_between). Borrows strength across correlated outcomes — studies that report only one outcome still contribute to the joint pooled estimate via ρ_between. Side-by-side comparison with separate univariate REML shows the CI tightening.",
    note: "Reference: Riley 2007 (Biostatistics); Jackson, Riley & White 2011 (Stat Med); Achana 2014 §3.1 (Res Synth Methods). Roadmap: K ≥ 3 and network multi-outcome.",
    tags: ["multivariate", "bivariate", "multi-outcome", "borrowing-of-strength", "reml", "achana"]
  },
  {
    name: "Cross-design synthesis",
    featured: true,
    folder: "allmeta/cross-design",
    path: "./cross-design/",
    added: "2026-05-24",
    collection: "new",
    mode: "file",
    category: "Pairwise MA",
    summary: "Combine RCT and observational evidence with three side-by-side estimators: naive pool (reference only), power prior (observational at downweight α ∈ [0,1]), and Welton design-bias random-effects (RCTs anchor μ; δ_obs and σ²_bias estimated from obs studies). Closes a methodology gap in HTA / decision-modelling contexts where RCT evidence alone is insufficient.",
    note: "Reference: Welton, Cooper, Ades, Lu, Sutton 2009 (Stat Med); Ibrahim & Chen 2000 power prior; Schmitz, Adams, Walsh 2013 (Res Synth Methods).",
    tags: ["cross-design", "rct", "observational", "power-prior", "design-bias", "hta"]
  },
  {
    name: "PROSPERO Templater",
    featured: true,
    folder: "allmeta/prospero-templater",
    path: "./prospero-templater/",
    added: "2026-05-24",
    collection: "new",
    mode: "file",
    category: "PRISMA & Reporting",
    summary: "Fill the 39-field PROSPERO registration form from your PICO + protocol draft. Auto-saves locally; export the whole filled form as Markdown for review or copy each field into PROSPERO.",
    note: "Unofficial templater — submit at https://www.crd.york.ac.uk/PROSPERO/. No data leaves your device.",
    tags: ["prospero", "registration", "protocol", "prisma", "templater"]
  },
  {
    name: "BMA across τ² priors",
    featured: true,
    folder: "allmeta/bma-tau-priors",
    path: "./bma-tau-priors/",
    added: "2026-05-24",
    collection: "new",
    mode: "file",
    category: "Pairwise MA",
    summary: "Bayesian Model Averaging across τ² priors (half-normal, half-Cauchy, inverse-gamma, uniform). Closes prior-sensitivity for small-k random-effects meta-analysis: the averaged posterior automatically downweights priors that fit the data poorly via their marginal likelihood. Drop-in sensitivity layer over any pooler.",
    note: "Reference: Friede, Röver, Wandel & Neuenschwander 2017 (Biom J). Simpson-rule marginalisation over a τ² grid + Laplace approximation for μ given τ².",
    tags: ["bma", "bayesian", "model-averaging", "tau-prior", "sensitivity", "small-k"]
  },
  {
    name: "RVE Meta-Regression",
    featured: true,
    folder: "allmeta/rve-meta",
    path: "./rve-meta/",
    added: "2026-05-24",
    collection: "new",
    mode: "file",
    category: "Pairwise MA",
    summary: "Robust Variance Estimation (Hedges-Tipton-Johnson 2010 CORR working model + CR1 small-sample correction). Cluster-robust meta-regression for dependent effect sizes (multiple outcomes per study, multi-arm trials, repeated measures) — coefficient SEs are correct even when the within-cluster correlation ρ is misspecified.",
    note: "Closes the inverse-variance underestimate that breaks standard meta-regression when effects are nested. Parity target: robumeta::robu(model='CORR').",
    tags: ["rve", "robumeta", "cluster-robust", "meta-regression", "dependent-effects", "hedges-tipton"]
  },
  {
    name: "EvidenceOS",
    featured: true,
    folder: "allmeta/evidenceos",
    path: "./evidenceos/",
    added: "2026-05-14",
    collection: "new",
    mode: "file",
    category: "Living Evidence",
    summary: "Serverless living-evidence watch that turns open ClinicalTrials.gov and OpenAlex metadata into a source-backed update gate for a living meta-analysis.",
    note: "MVP topic: finerenone cardiorenal evidence. Detects update signals and emits a draft TruthCert receipt without inferring clinical effects.",
    tags: ["living-evidence", "ctgov", "openalex", "truthcert", "surveillance", "meta-analysis"]
  },
  {
    name: "Local AI setup",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/ai-meta-analysis-course.html",
    folder: "allmeta/local-ai",
    path: "./local-ai/index.html",
    added: "2026-04-21",
    collection: "existing",
    mode: "file",
    category: "R / WASM",
    summary: "One-page guide to running a local LLM via Ollama so allmeta apps can do structured extraction (PICO from abstracts, effect sizes from results paragraphs) — without sending any data off your device. Live connectivity check included.",
    note: "Complements WebR Studio. PICO Formulator and Effect-Size Converter already wire into it.",
    tags: ["ollama", "local-ai", "llm", "extraction", "privacy"]
  },
  {
    name: "WebR Studio",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/becoming-methodologist.html",
    folder: "allmeta/webr-studio",
    path: "./webr-studio/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "R / WASM",
    summary: "Run real R in your browser via WebR. Curated templates for metafor, meta, netmeta, metasens, bayesmeta, and mada — genuine CRAN package output, no server. First load downloads ~30 MB.",
    note: "Use for gold-standard validation and analyses the browser-native apps can only approximate.",
    tags: ["webr", "r", "wasm", "metafor", "netmeta", "bayesmeta", "metasens", "mada"]
  },
  {
    name: "Annualised Outcome Plot (R/Shinylive)",
    folder: "allmeta/r-shiny/annualised-plot",
    path: "./r-shiny/annualised-plot/",
    added: "2026-05-14",
    collection: "new",
    mode: "file",
    category: "R / WASM",
    summary: "Legacy R Shiny annualised-rate plotting app exported with Shinylive. Runs the original Shiny UI in the browser through webR, with sample CSV support and local file upload.",
    note: "Pilot conversion from the D-drive R portfolio; first load uses the shared Shinylive/webR runtime.",
    tags: ["shinylive", "webr", "r-shiny", "plotting", "annualised-rate"]
  },
  {
    name: "Diagnostic Test Accuracy (R/Shinylive)",
    folder: "allmeta/r-shiny/dta-diagnostic",
    path: "./r-shiny/dta-diagnostic/",
    added: "2026-05-14",
    collection: "new",
    mode: "file",
    category: "R / WASM",
    summary: "Legacy R Shiny diagnostic test accuracy app exported with Shinylive. Computes threshold-based classification summaries and ROC/AUC outputs using browser-side R.",
    note: "Pilot conversion from the D-drive R portfolio; data stays in the browser.",
    tags: ["shinylive", "webr", "r-shiny", "dta", "roc"]
  },
  {
    name: "Mean Single-Group Meta-Analysis (R/Shinylive)",
    folder: "allmeta/r-shiny/mean-single-group",
    path: "./r-shiny/mean-single-group/",
    added: "2026-05-14",
    collection: "new",
    mode: "file",
    category: "R / WASM",
    summary: "Legacy R Shiny single-group meta-analysis app exported with Shinylive. Uses browser-side R and metafor for pooled mean analyses, plots, and tabular diagnostics.",
    note: "Pilot conversion from the D-drive R portfolio; heavier analyses may take longer on first load.",
    tags: ["shinylive", "webr", "r-shiny", "metafor", "single-group"]
  },
  {
    name: "Local R Install",
    folder: "allmeta/local-install",
    path: "./local-install/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "R / WASM",
    summary: "One-stop recipe for installing R + the allmeta CRAN stack locally, including Stan / JAGS back-ends for real MCMC (gemtc, multinma, rstan, cmdstanr, brms, bayesmeta). Reproduces every browser app in native R.",
    note: "For the 10% of tasks that need local compute.",
    tags: ["r", "install", "stan", "jags", "local", "reproducibility"]
  },
  {
    name: "NMA Global Inconsistency",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/advanced-meta-analysis-course.html",
    folder: "allmeta/nma-global-inconsistency",
    path: "./nma-global-inconsistency/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Network Meta-Analysis",
    summary: "Fit NMA under consistency vs full design-inconsistency model; compare with a likelihood-ratio test (Higgins 2012). Per-design residual plot to localise inconsistent loops.",
    note: "Complements the per-comparison node-splitting tool.",
    tags: ["nma", "inconsistency", "lr-test", "design-by-treatment"]
  },
  {
    name: "p-curve / p-uniform",
    subcategory: "Publication bias",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/publication-bias-detective.html",
    folder: "allmeta/p-curve",
    path: "./p-curve/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Publication-bias-robust effect estimation from p-values alone. Right-skew and flatness tests (Simonsohn 2014) plus p-uniform effect size (van Assen 2015).",
    note: "Uses only significant p-values; complements Funnel / PET-PEESE.",
    tags: ["p-curve", "p-uniform", "evidential-value", "p-hacking"]
  },
  {
    name: "Limit meta-analysis",
    subcategory: "Publication bias",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/publication-bias-detective.html",
    folder: "allmeta/limit-ma",
    path: "./limit-ma/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Rücker limit meta-analysis: extrapolates to the zero-variance limit to adjust for small-study effects. Outputs the FE, RE, and limit estimate with a funnel overlay.",
    note: "Matches metasens::limitmeta (simplified).",
    tags: ["limit-meta", "rucker", "small-study-adjustment"]
  },
  {
    name: "GOSH Meta-Regression",
    subcategory: "Heterogeneity",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/advanced-meta-analysis-course.html",
    folder: "allmeta/gosh-metareg",
    path: "./gosh-metareg/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "All-subset meta-regression: for every non-trivial subset, fit a single-moderator meta-regression and scatter β against residual I². Reveals whether the moderator effect is subset-robust.",
    note: "k ≤ 18 studies. Extends GOSH with a regression layer.",
    tags: ["gosh", "meta-regression", "robustness", "moderator"]
  },
  {
    name: "PowerMA / RIS",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/cast-when-certainty-kills.html",
    folder: "allmeta/powerma",
    path: "./powerma/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Trial Design",
    summary: "Pre-meta-analysis power and Required Information Size (RIS) calculator. Binary (RRR) or continuous (MD/SMD) outcomes, α and power, with I² and D² heterogeneity inflation per Wetterslev TSA conventions.",
    note: "Plan a review's target N before starting.",
    tags: ["power", "ris", "sample-size", "tsa"]
  },
  {
    name: "GRADE-CERQual",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/grade-certainty-course.html",
    folder: "allmeta/cerqual",
    path: "./cerqual/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Qualitative Synthesis",
    summary: "Confidence in qualitative-review findings. Rate four components (methodological limitations, coherence, adequacy, relevance) per finding; derives High / Moderate / Low / Very low confidence.",
    note: "Lewin 2018. Pairs with Thematic Synthesis.",
    tags: ["cerqual", "qualitative", "confidence", "certainty"]
  },
  {
    name: "ROBINS-E",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/risk-of-bias-mastery-course.html",
    folder: "allmeta/robins-e",
    path: "./robins-e/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Risk of Bias",
    summary: "Risk of Bias in Non-randomized Studies of Exposures: 7 domains with signaling questions and algorithmic judgments, plus traffic-light chart.",
    note: "Higgins, Morgan, Rooney et al. Environ Int 2024;186:108602. For exposure epidemiology.",
    tags: ["robins-e", "exposure", "environmental", "risk-of-bias"]
  },
  {
    name: "Citation Chaser",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/meta-analysis-topic-selection-course.html",
    folder: "allmeta/citation-chaser",
    path: "./citation-chaser/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Search",
    summary: "Forward and backward citation chasing via the OpenAlex API. Paste DOIs as seeds; discover references and citing works. Deduplicated, exportable as CSV, with year histogram.",
    note: "Uses OpenAlex public API — no key required.",
    tags: ["citation-chasing", "openalex", "search", "reference-mining"]
  },
  {
    name: "NMA Inconsistency",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/advanced-meta-analysis-course.html",
    folder: "allmeta/nma-inconsistency",
    path: "./nma-inconsistency/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Network Meta-Analysis",
    summary: "Node-splitting (Dias 2010) and design-by-treatment inconsistency test (Higgins 2012) for network meta-analysis. Compares direct vs indirect estimates per comparison.",
    note: "Critical check before interpreting NMA results.",
    tags: ["nma", "inconsistency", "node-splitting", "dbt"]
  },
  {
    name: "Bucher Indirect",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/advanced-meta-analysis-course.html",
    folder: "allmeta/bucher",
    path: "./bucher/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Network Meta-Analysis",
    summary: "Bucher (1997) indirect comparison: estimate A vs B from direct A vs C and B vs C, with log-scale back-transform for ratios.",
    note: "Simplest possible indirect comparison — the building block of NMA.",
    tags: ["bucher", "indirect-comparison", "itc"]
  },
  {
    name: "Multi-level MA",
    subcategory: "Pooling",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/advanced-meta-analysis-course.html",
    folder: "allmeta/multilevel-ma",
    path: "./multilevel-ma/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Three-level random-effects meta-analysis for dependent effect sizes nested within studies. Separates within-study (τ²_within) from between-study (τ²_study) heterogeneity.",
    note: "Mirrors metafor::rma.mv with a moment-based iteration.",
    tags: ["multi-level", "three-level", "nested", "rma.mv"]
  },
  {
    name: "Pub-bias Tests",
    subcategory: "Publication bias",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/publication-bias-detective.html",
    folder: "allmeta/pubbias-tests",
    path: "./pubbias-tests/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Suite of small-study-effect tests beyond Egger: Begg-Mazumdar rank correlation, Peters (for binary), Harbord-Egger, and Thompson-Sharp multiplicative.",
    note: "Different tests have different power against different bias mechanisms — report multiple.",
    tags: ["pub-bias", "egger", "begg", "peters", "harbord", "thompson"]
  },
  {
    name: "Copas selection",
    subcategory: "Publication bias",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/publication-bias-detective.html",
    folder: "allmeta/copas",
    path: "./copas/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Copas selection model: sensitivity of the pooled effect across plausible selection strengths γ. Shows how the adjusted estimate shifts as the assumed unpublished fraction grows.",
    note: "Simplified browser implementation. Full MLE in metasens::copas.",
    tags: ["copas", "pub-bias", "selection-model", "sensitivity"]
  },
  {
    name: "Reporting-bias cockpit (ROB-ME)",
    folder: "allmeta/reporting-bias",
    path: "./reporting-bias/index.html",
    added: "2026-06-06",
    collection: "existing",
    mode: "file",
    category: "Publication bias",
    summary: "Missing-evidence cockpit: quantify the registered-vs-included linkage-rate denominator (~63.6% publish), the protocol-vs-paper outcome-switching diff (~24% dropped), and Egger small-study asymmetry — feeding a ROB-ME-aligned (Page 2023) risk-of-bias judgement. Turns funnel/Egger from the verdict into one input.",
    note: "ROB-ME signalling prompts are paraphrased — see riskofbias.info for official wording/algorithm. Egger R-verified vs lm.",
    tags: ["rob-me", "reporting-bias", "missing-evidence", "publication-bias", "outcome-switching", "egger"]
  },
  {
    name: "Registry publication bias",
    folder: "allmeta/registry-pubbias",
    path: "./registry-pubbias/",
    added: "2026-06-11",
    collection: "new",
    mode: "file",
    category: "Publication bias",
    summary: "Turn reporting bias from an INFERENCE problem into a MEASUREMENT one: the registry observes the posted-but-unpublished 'ghost' trials, so the bias is measured directly (published-only pool vs registry-complete pool) and that ground truth disambiguates Egger funnel asymmetry — classifying it as measured-bias, spurious-asymmetry (Egger flags but the observed ghosts barely move it → don't trim-and-fill), no-bias, or inference-only.",
    note: "Reuses the audited ma-core (PM pool) + egger engines. Only measures trials that posted data; truly dark trials stay unmeasured. Complements ROB-ME / Copas / trim-fill. Idea integrated from the glp1-obesity-mbnma registry-pubbias arm.",
    tags: ["registry", "publication-bias", "ghost-trials", "egger", "trim-fill", "missing-evidence", "measurement", "ct.gov"]
  },
  {
    name: "Influence Diagnostics",
    subcategory: "Heterogeneity",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/advanced-meta-analysis-course.html",
    folder: "allmeta/influence",
    path: "./influence/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Per-study influence on a random-effects MA: Cook's distance, hat values, studentized residuals, DFFITS, covariance ratio, leave-one-out pooled estimates, plus an influence plot.",
    note: "Mirrors metafor::influence(). Flags studies in red on thresholds.",
    tags: ["influence", "cooks-distance", "dffits", "hat", "leave-one-out"]
  },
  {
    name: "Bayesian MA — MCMC",
    subcategory: "Pooling",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/advanced-meta-analysis-course.html",
    folder: "allmeta/bayesian-mcmc",
    path: "./bayesian-mcmc/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Real Gibbs MCMC for random-effects meta-analysis. Multi-chain with R-hat and ESS diagnostics. Posterior densities for μ and τ, trace plot, and predictive interval.",
    note: "For serious use: bayesmeta / RoBMA / Stan. This is a browser-native implementation.",
    tags: ["bayesian", "mcmc", "gibbs", "predictive", "bayesmeta"]
  },
  {
    name: "MH / Peto pooling",
    subcategory: "Pooling",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/meta-analysis-methods-course.html",
    folder: "allmeta/mh-peto",
    path: "./mh-peto/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Mantel-Haenszel pooling for OR/RR/RD and Peto one-step OR. Recommended for rare events (&lt; 1%) — no continuity correction required.",
    note: "Cochrane Handbook 10.4.4.",
    tags: ["mantel-haenszel", "peto", "rare-events", "2x2"]
  },
  {
    name: "Thematic Synthesis",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/qualitative-evidence-synthesis-course.html",
    folder: "allmeta/thematic-synthesis",
    path: "./thematic-synthesis/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Qualitative Synthesis",
    summary: "Organise qualitative evidence for systematic reviews. Add participant quotes with study source, descriptive code, and analytical theme, then view as a hierarchical theme tree. Exports themed JSON.",
    note: "Thomas & Harden (2008) thematic-synthesis method.",
    tags: ["qualitative", "thematic-synthesis", "coding"]
  },
  {
    name: "Network MA (SUCRA)",
    featured: true,
    course: "https://mahmood726-cyber.github.io/synthesis-courses/advanced-meta-analysis-course.html",
    folder: "allmeta/bayesian-nma",
    path: "./bayesian-nma/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Network Meta-Analysis",
    summary: "Contrast-based NMA under a consistency model via weighted least squares, with Monte-Carlo posterior sampling for SUCRA treatment rankings. Network diagram, forest of contrasts, SUCRA bars.",
    note: "Fast approximation suitable for exploration. Use MCMC software for publication.",
    tags: ["nma", "sucra", "consistency", "ranking"]
  },
  {
    name: "POTH (hierarchy certainty)",
    folder: "allmeta/poth",
    path: "./poth/index.html",
    added: "2026-06-07",
    collection: "existing",
    mode: "file",
    category: "Network Meta-Analysis",
    summary: "Precision Of Treatment Hierarchy (Wigle 2025): a single 0–1 number for how certain an NMA treatment hierarchy is, from the SUCRA/P-score values — POTH = [12(n−1)/(n+1)]·(1/n)Σ(SUCRA−0.5)². 1 = certain hierarchy, 0 = treatments indistinguishable (median ≈ 0.671). Report it next to any SUCRA ranking.",
    note: "A low POTH means the hierarchy is non-informative — do not claim a treatment is 'ranked best'. Closed-form; mirrors the CRAN poth package.",
    tags: ["nma", "poth", "sucra", "ranking", "hierarchy", "uncertainty", "wigle"]
  },
  {
    name: "Component NMA",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/advanced-meta-analysis-course.html",
    folder: "allmeta/component-nma",
    path: "./component-nma/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Network Meta-Analysis",
    summary: "Additive component network meta-analysis (Welton 2009) for multi-component interventions. Decomposes complex interventions into per-component effects and derives implied combination effects.",
    note: "Assumes additivity on the analysis scale; add interaction terms for synergy.",
    tags: ["component-nma", "complex-interventions", "additive"]
  },
  {
    name: "MCID & NI margin",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/hta-oman-course.html",
    folder: "allmeta/mcid",
    path: "./mcid/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Trial Design",
    summary: "Minimum clinically important difference via distribution-based (0.5·SD, 1·SEM, SDC) and anchor-based (Juniper) methods, plus a non-inferiority margin derived from active-comparator effect and preservation fraction.",
    note: "Triangulate multiple methods; MCID depends on context.",
    tags: ["mcid", "non-inferiority", "ni-margin", "responder"]
  },
  {
    name: "E-value",
    folder: "allmeta/evalue",
    path: "./evalue/index.html",
    added: "2026-06-05",
    collection: "existing",
    mode: "file",
    category: "Sensitivity",
    summary: "E-value (VanderWeele & Ding 2017): the minimum strength of unmeasured confounding — with both exposure and outcome — needed to explain away an observed association, for the point estimate and the confidence limit nearest the null. Supports RR/OR/HR/SMD.",
    note: "For observational estimates; one sensitivity input, not a verdict. Verified vs the EValue R package.",
    tags: ["e-value", "confounding", "sensitivity", "observational", "vanderweele"]
  },
  {
    name: "Transportability",
    folder: "allmeta/transportability",
    path: "./transportability/",
    added: "2026-06-11",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Transport a meta-analytic effect to YOUR target population via effect-modifier standardisation: a random-effects meta-regression (Paule-Mandel τ², Knapp-Hartung CIs) predicting the mean effect at the target's modifier value, with an unmeasured-modifier sensitivity. The aggregate, IPD-free sibling of ML-NMR / one-step network meta-regression — a generalisability estimand no mainstream SR tool offers.",
    note: "Assumption-laden (measured dominant modifier, no unmeasured modifier, linear model, no far extrapolation) — assumptions surfaced in-app. Cross-language validated against SciPy.",
    tags: ["transportability", "generalisability", "meta-regression", "ml-nmr", "effect-modifier", "standardisation", "external-validity"]
  },
  {
    name: "Benefit-risk MCDA",
    folder: "allmeta/benefit-risk",
    path: "./benefit-risk/",
    added: "2026-06-11",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Probabilistic benefit-risk multi-criteria decision analysis: linear partial value functions over benefits + harms, SMAA rank-acceptability (P best) propagating each treatment's effect uncertainty by Monte Carlo, and EVPI — the value of resolving the remaining decision uncertainty (is more research worth it?). Standard ISPOR / Tervonen-SMAA framework, no SR tool ships it.",
    note: "Weights are value judgements (elicit + vary them); value functions are linear; EVPI is on the 0–1 value scale. Deterministic (seeded). Idea integrated from the glp1-obesity-mbnma benefit-risk arm.",
    tags: ["benefit-risk", "mcda", "smaa", "evpi", "value-of-information", "decision-analysis", "ispor", "rank-acceptability"]
  },
  {
    name: "Transitivity & representativeness",
    folder: "allmeta/transitivity",
    path: "./transitivity/",
    added: "2026-06-11",
    collection: "new",
    mode: "file",
    category: "Network Meta-Analysis",
    summary: "Screen the NMA transitivity assumption — the distribution of each effect modifier across the network's nodes/comparisons, flagging modifiers that vary substantially (those comparisons aren't exchangeable) — and map trial representativeness vs a target population per modifier (standardised difference). Two generalisability checks NMAs usually leave to prose.",
    note: "A reviewer-judged screen, not a hypothesis test; CV is scale-relative (a small CV can be a clinically large gap). Pairs with the Transportability app. Idea integrated from the glp1-obesity-mbnma transitivity + representativeness workstreams.",
    tags: ["transitivity", "representativeness", "nma", "effect-modifier", "exchangeability", "generalisability", "external-validity"]
  },
  {
    name: "Surrogate validation",
    folder: "allmeta/surrogate-validation",
    path: "./surrogate-validation/",
    added: "2026-06-11",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Trial-level surrogate validation: regress the final-outcome effects on the surrogate effects across trials and report the naive R², the estimation-error-adjusted R² (Daniels-Hughes / van Houwelingen), leave-one-out robustness, and a surrogate threshold effect — refusing the adjusted R² when the final effects don't vary enough to estimate it (the trap a naive R² hides).",
    note: "Trial-level ≠ individual-level surrogacy; high R² is necessary but not sufficient; needs adequate k + between-trial signal. Cross-language validated vs numpy. Idea integrated from the glp1-obesity-mbnma surrogate arm.",
    tags: ["surrogate", "surrogacy", "trial-level", "daniels-hughes", "validation", "ste", "r-squared", "biomarker"]
  },
  {
    name: "Umbrella overlap (CCA)",
    folder: "allmeta/umbrella-overlap",
    path: "./umbrella-overlap/",
    added: "2026-06-11",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Quantify primary-study overlap across the reviews in an umbrella review (review of reviews) via the Corrected Covered Area (CCA = (N−r)/(r·c−r); Pieper 2014), with Pieper's grooves (slight/moderate/high/very high), a pairwise shared-study matrix, and the most-shared studies — so a pool across overlapping reviews doesn't double-count evidence.",
    note: "Needs the full cited-study list per review (matched on a consistent id). CCA is whole-umbrella; per-outcome overlap can differ. Method integrated from the UmbrellaEngine project.",
    tags: ["umbrella-review", "overlap", "cca", "corrected-covered-area", "pieper", "non-independence", "review-of-reviews"]
  },
  {
    name: "Quantile meta-analysis",
    folder: "allmeta/quantile-ma",
    path: "./quantile-ma/",
    added: "2026-06-11",
    collection: "new",
    mode: "file",
    category: "Heterogeneity",
    summary: "Detect heterogeneous treatment effects across the OUTCOME distribution: random-effects pool the quantile treatment effect (QTE) at each quantile across trials, then a multivariate Wald test on adjacent-difference contrasts asks whether the QTE profile is flat (χ²_{q−1}). A sloped profile means the effect differs at the low vs high end (who benefits more) — which a single pooled effect hides.",
    note: "Stage-1 QTE must come from per-trial quantile regression, not the marginal effect. Wald uses a diagonal cross-quantile covariance → conservative (positive result robust, null not definitive). Reuses ma-core DL; cross-language validated vs numpy/scipy. From the IPD-QMA project.",
    tags: ["quantile", "qte", "heterogeneous-treatment-effects", "hte", "wald", "ipd", "effect-modification", "distribution"]
  },
  {
    name: "Benford screen",
    folder: "allmeta/benford-screen",
    path: "./benford-screen/",
    added: "2026-06-11",
    collection: "new",
    mode: "file",
    category: "Integrity",
    summary: "Forensic first-digit screen: test whether a column of extracted values (sample sizes, event counts, totals) follows Benford's law P(d)=log₁₀(1+1/d) via the Nigrini mean-absolute-deviation conformity class and a χ²(8) goodness-of-fit test, with an observed-vs-Benford first-digit chart. A large deviation can flag fabricated, altered or heavily-rounded data — complementing the integrity suite (spec-collapse, INSPECT-SR, reporting-bias).",
    note: "CRITICAL: Benford is valid only for unbounded quantities spanning ≥2 orders of magnitude — NOT proportions, p-values, percentages or standardised effects (SMD/I²), which fail Benford legitimately. ≥100 values recommended (≥30 minimum). A flag is a prompt to investigate, never proof of fabrication; conformity is not a clean bill of health. χ² validated vs scipy. Method integrated from the BenfordMA project.",
    tags: ["benford", "data-integrity", "nigrini", "mad", "forensics", "fabrication", "first-digit", "anomaly"]
  },
  {
    name: "Transported NMA",
    folder: "allmeta/transported-nma",
    path: "./transported-nma/",
    added: "2026-06-11",
    collection: "new",
    mode: "file",
    category: "Network Meta-Analysis",
    summary: "Transport a network meta-analysis to a TARGET population: entropy-balance each study so the network's weighted effect-modifier means match a target profile (Hainmueller), refit the random-effects NMA on the reweighted variances, and compare the source vs target league table and P-score ranking — with the Kish effective sample size that quantifies how much information the transport costs and whether the answer is interpolation or extrapolation.",
    note: "Corrects only for the MEASURED modifiers supplied; unmeasured modifiers / interactions are not fixed. Entropy balancing matches target moments exactly inside the covariate hull, extrapolates outside it (watch the ESS ratio + achieved-vs-target gap). Variance-inflation reweighting is an aggregate-data approximation to IPD network meta-regression. Reuses the audited WLS NMA solver + ma-core; entropy weights cross-validated vs numpy Newton. From the nmatransport project.",
    tags: ["nma", "transportability", "generalizability", "entropy-balancing", "hainmueller", "target-population", "effect-modifier", "p-score", "external-validity"]
  },
  {
    name: "Fragility index (MA)",
    folder: "allmeta/fragility",
    path: "./fragility/index.html",
    added: "2026-06-05",
    collection: "existing",
    mode: "file",
    category: "Sensitivity",
    summary: "Fragility index for a binary-outcome meta-analysis (Atal 2019): the fewest single-patient event-status changes, added greedily across studies, needed to flip the pooled DL result's statistical significance. Reports FI, fragility quotient, and the modifications applied.",
    note: "Transparency metric, not a test; defined for a significant pooled result. Matches the fragility R package.",
    tags: ["fragility-index", "robustness", "sensitivity", "binary-outcome", "atal"]
  },
  {
    name: "Spec-collapse",
    folder: "allmeta/spec-collapse",
    path: "./spec-collapse/index.html",
    added: "2026-06-05",
    collection: "existing",
    mode: "file",
    category: "Sensitivity",
    summary: "Multiverse / many-analyst meta-analysis done right: run one dataset across a 36-specification grid (3 τ² × 2 CI × 3 outlier × raw/trim-fill) and compare the anti-conservative naive IV-RE pool against a coverage-calibrated weighted-likelihood interval. Flags 'false robustness' when the naive pool's significance is an artefact of pooling re-analyses of one dataset.",
    note: "Port of the Spec-Collapse Atlas aggregator (validated vs metafor across 473 Cochrane reviews); JS engine cross-checked to the Python to 1e-6. Never IV-RE-pool multiverse results.",
    tags: ["multiverse", "spec-curve", "many-analyst", "robustness", "weighted-likelihood", "false-robustness"]
  },
  {
    name: "ROBINS-I",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/risk-of-bias-mastery-course.html",
    folder: "allmeta/robins-i",
    path: "./robins-i/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Risk of Bias",
    summary: "Risk of Bias in Non-randomized Studies of Interventions: 7 domains with signaling questions and algorithmic Low/Moderate/Serious/Critical judgments, plus traffic-light chart.",
    note: "Sterne 2016 decision rules. For non-randomized intervention studies.",
    tags: ["robins-i", "non-randomized", "risk-of-bias", "appraisal"]
  },
  {
    name: "INSPECT-SR",
    folder: "allmeta/inspect-sr",
    path: "./inspect-sr/index.html",
    added: "2026-06-05",
    collection: "existing",
    mode: "file",
    category: "Risk of Bias",
    summary: "INSPECT-SR (Wilkinson 2025, with Cochrane): assess RCT trustworthiness across 21 checks in 4 domains (post-publication notices; conduct/governance/transparency; text/figures; results), reach domain and overall judgements (No/Some/Serious concerns), and re-pool the meta-analysis excluding flagged trials to see whether the result survives.",
    note: "Trustworthiness, not risk-of-bias — orthogonal to RoB-2/GRADE. Reviewer judgements required; not a prescriptive algorithm. Re-pool via the audited ma-core.",
    tags: ["inspect-sr", "trustworthiness", "research-integrity", "problematic-trials", "cochrane", "wilkinson"]
  },
  {
    name: "QUADAS-2",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/risk-of-bias-mastery-course.html",
    folder: "allmeta/quadas-2",
    path: "./quadas-2/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Risk of Bias",
    summary: "Quality Assessment of Diagnostic Accuracy Studies 2: four domains (patient selection, index test, reference standard, flow & timing) rated for risk of bias and applicability, with traffic-light chart.",
    note: "Whiting 2011. For DTA studies — pairs with DTA SROC Explorer and HSROC.",
    tags: ["quadas-2", "dta", "risk-of-bias", "applicability"]
  },
  {
    name: "AMSTAR-2",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/umbrella-reviews-course.html",
    folder: "allmeta/amstar-2",
    path: "./amstar-2/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Risk of Bias",
    summary: "A Measurement Tool to Assess systematic Reviews 2: 16 items with 7 marked critical; derives an overall confidence rating (High / Moderate / Low / Critically Low) from the critical-flaw and non-critical-weakness counts.",
    note: "Shea 2017. For appraising existing systematic reviews.",
    tags: ["amstar-2", "systematic-review-appraisal", "umbrella-review"]
  },
  {
    name: "CINeMA (NMA confidence)",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/grade-certainty-course.html",
    folder: "allmeta/cinema",
    path: "./cinema/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Network Meta-Analysis",
    summary: "Confidence In Network Meta-Analysis: rate six domains (within-study bias, reporting, indirectness, imprecision, heterogeneity, incoherence) per comparison; derives High / Moderate / Low / Very low. Heatmap view.",
    note: "Nikolakopoulou 2020.",
    tags: ["cinema", "nma", "confidence", "certainty"]
  },
  {
    name: "HSROC / Bivariate DTA",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/dta-course-when-the-test-lies-v4.html",
    folder: "allmeta/hsroc",
    path: "./hsroc/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Diagnostic Test Accuracy",
    summary: "Bivariate random-effects DTA meta-analysis on logit(Se) and logit(1-Sp), with summary operating point and an HSROC curve derived from the mean linear predictor. Approximates Reitsma via IGLS.",
    note: "For rigorous estimates use R's mada; this is a browser-native sketch.",
    tags: ["hsroc", "sroc", "bivariate", "dta", "reitsma"]
  },
  {
    name: "GOSH Plot",
    subcategory: "Heterogeneity",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/advanced-meta-analysis-course.html",
    folder: "allmeta/gosh",
    path: "./gosh/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Graphical display of study heterogeneity: enumerate every non-empty subset of studies (≤18 studies), compute its pooled effect and I², and scatter on a (mu, I²) plane. Clusters reveal influential studies or subgroup structure.",
    note: "Olkin, Dahabreh, Trikalinos 2012.",
    tags: ["gosh", "heterogeneity", "subset", "influence"]
  },
  {
    name: "PICO Formulator",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/meta-analysis-topic-selection-course.html",
    folder: "allmeta/pico",
    path: "./pico/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Planning",
    summary: "Frame a review question as PICO, PECO, PICOS, or PICOT. Generates a one-sentence question and a boolean-search skeleton, plus a visual PICO wheel.",
    note: "Pairs with the Search Strategy Translator as the next step.",
    tags: ["pico", "question-framework", "planning"]
  },
  {
    name: "PRISMA 2020 Checklist",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/meta-analysis-writing-course.html",
    folder: "allmeta/prisma-checklist",
    path: "./prisma-checklist/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Reporting",
    summary: "Interactive PRISMA 2020 checklist — all 27 items with status / location fields, progress donut, and JSON export/load.",
    note: "Based on Page et al. 2021.",
    tags: ["prisma-2020", "checklist", "reporting"]
  },
  {
    name: "Search Strategy Translator",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/meta-analysis-topic-selection-course.html",
    folder: "allmeta/search-translator",
    path: "./search-translator/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Search",
    summary: "Translate a PubMed search into Embase (Emtree) and Cochrane CENTRAL syntax. Field tags, MeSH, and operators are rewritten with warnings for unmapped terms.",
    note: "Syntactic aid — always proof-read the output.",
    tags: ["search", "pubmed", "embase", "central", "translation"]
  },
  {
    name: "Search completeness",
    folder: "allmeta/search-completeness",
    path: "./search-completeness/",
    added: "2026-06-11",
    collection: "new",
    mode: "file",
    category: "Search",
    summary: "Quantify how many registered trials a literature-only search MISSES: against a registry cohort (CT.gov NCT ids) + the trial→publication linkage, it reports the miss rate, the trial-to-publication linkage rate (~63.6% literature baseline), the denominator-bias factor (a search of N papers ≈ N/sensitivity registered trials), and categorises each miss (unpublished ghost / published-but-not-retrieved / no link).",
    note: "Retrieval-completeness vs the registry, not absolute truth; complements ROB-ME / reporting-bias as an explicit missing-evidence term. Idea integrated from the glp1-obesity-mbnma registry-vs-MEDLINE arm.",
    tags: ["search-completeness", "registry", "ghost-trials", "publication-bias", "linkage", "ct.gov", "missing-evidence", "denominator-bias"]
  },
  {
    name: "Median → Mean/SD",
    subcategory: "Effect-size tools",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/meta-analysis-methods-course.html",
    folder: "allmeta/median-to-mean",
    path: "./median-to-mean/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Estimate mean and SD from reported median, IQR, min, and max using Wan 2014, Luo 2018, and Shi 2020 formulas. Three scenarios: 5-number / 3-number / IQR-only.",
    note: "Modern default: Luo mean + Shi SD.",
    tags: ["mean-sd", "median", "iqr", "wan", "luo", "shi"]
  },
  {
    name: "RoB 2",
    featured: true,
    course: "https://mahmood726-cyber.github.io/synthesis-courses/risk-of-bias-mastery-course.html",
    folder: "allmeta/rob2",
    path: "./rob2/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Risk of Bias",
    summary: "Cochrane Risk of Bias 2: signaling questions across 5 domains with algorithmic per-domain and overall judgements, plus traffic-light chart.",
    note: "Sterne 2019 decision rules. For RCTs.",
    tags: ["rob-2", "cochrane", "risk-of-bias", "appraisal"]
  },
  {
    name: "PET-PEESE + Trim-and-Fill",
    subcategory: "Publication bias",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/publication-bias-detective.html",
    folder: "allmeta/pet-peese",
    path: "./pet-peese/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Publication-bias adjustments: PET, PEESE, Stanley–Doucouliagos conditional procedure, and Duval–Tweedie trim-and-fill with L₀ / R₀ estimators. Funnel plot overlays the adjustments.",
    note: "Goes beyond Egger's test when asymmetry is present.",
    tags: ["publication-bias", "pet", "peese", "trim-and-fill", "funnel-plot"]
  },
  {
    name: "Proportion MA",
    subcategory: "Pooling",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/meta-analysis-methods-course.html",
    folder: "allmeta/proportion-ma",
    path: "./proportion-ma/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Meta-analysis of proportions / incidences. Freeman-Tukey double-arcsine, logit, or raw pooling with DL or Paule-Mandel τ². Clopper-Pearson per-study CIs; forest plot.",
    note: "For single-arm event rates (e.g., adverse-event incidence, diagnostic yield).",
    tags: ["proportion", "single-arm", "freeman-tukey", "logit"]
  },
  {
    name: "K-M IPD Reconstructor",
    subcategory: "Effect-size tools",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/ipd-meta-analysis-course.html",
    folder: "allmeta/km-reconstructor",
    path: "./km-reconstructor/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Reconstruct individual patient data (event times + censoring) from a Kaplan-Meier curve plus at-risk table (Guyot 2012). NAR fusion: combine EXACT CT.gov/AACT registry KM anchors (zero digitization error) with the at-risk table — the strongest input regime, with a provenance-aware reliability tier. Exports IPD CSV and overlays the fit.",
    note: "Use WebPlotDigitizer for figure curves, or paste exact registry KM-estimate anchors and fuse. Fusion finding integrated from the registry-ipd project (within-20% HR recovery ~59-85% figure-only -> ~69-92% fused on its 42 true-IPD benchmark).",
    tags: ["kaplan-meier", "ipd", "survival", "guyot", "nar-fusion", "registry-native", "ct.gov", "aact"]
  },
  {
    name: "Registry-native survival IPD",
    folder: "allmeta/registry-survival",
    path: "./registry-survival/",
    added: "2026-06-11",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Reconstruct pseudo individual-patient survival data from ClinicalTrials.gov / AACT structured tables (KM-estimate points + number-at-risk + events) with NO Kaplan-Meier figure digitization — exact registry anchors, zero pixel error. Richness-aware tiers: A (Guyot / anchor-exact / QP, best-of by 1-Wasserstein), B (parametric + bootstrap), C (HR-only → refused, never fabricated).",
    note: "Pseudo-IPD, never true IPD; fails closed at Tier C. Engine vendored verbatim (MIT) from the registry-ipd project; complements the figure-based K-M reconstructor (and its NAR-fusion mode).",
    tags: ["registry-native", "pseudo-ipd", "survival", "kaplan-meier", "ct.gov", "aact", "guyot", "tiered", "fail-closed"]
  },
  {
    name: "Citation Dedup",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/meta-sprint-course.html",
    folder: "allmeta/citation-dedup",
    path: "./citation-dedup/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Screening & Extraction",
    summary: "Flag duplicate citations in a pasted list via DOI match, normalised-title trigram Jaccard, first-author surname, and year tolerance. Export cleaned CSV or grouped JSON.",
    note: "Pairs with Screenr as the upstream dedup step before title/abstract screening.",
    tags: ["deduplication", "systematic-review", "jaccard", "trigram"]
  },
  {
    name: "Effect-Size Converter",
    subcategory: "Effect-size tools",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/meta-analysis-methods-course.html",
    folder: "allmeta/effect-size-converter",
    path: "./effect-size-converter/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Convert between OR, RR, RD, SMD, MD, and HR. Derive standard errors from t, F, p-value, or CI. Cox's √3/π transform for OR↔SMD; delta-method propagation for OR↔RR.",
    note: "Browser-only, no backend. Live forest comparison on the SMD scale.",
    tags: ["effect-size", "conversion", "standard-error", "delta-method"]
  },
  {
    name: "Screenr",
    folder: "rayyanreplacement",
    path: "https://mahmood726-cyber.github.io/rayyanreplacement/",
    added: "2026-04-20",
    collection: "existing",
    mode: "url",
    category: "Screening & Extraction",
    summary: "Browser-only Rayyan/Covidence alternative: dual screening with conflict detection, SAFE stopping rules, ML prioritization (TF-IDF + logistic regression), Cohen's κ, and structured data extraction.",
    note: "Hosted as its own GitHub Pages site; linked here as the canonical screening workbench.",
    tags: ["screening", "rayyan", "dual-reviewer", "ml-prioritization", "data-extraction"]
  },
  {
    name: "Dose Response Pro",
    subcategory: "Effect-size tools",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/hta-oman-course.html",
    folder: "allmeta/dosehtml",
    path: "./dosehtml/dose-response-pro.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Dose-response meta-analysis in a single distributable HTML artifact with validation and CLI support alongside it.",
    note: "Canonical browser entry for the dose-response workspace.",
    tags: ["dose-response", "meta-analysis", "validated"]
  },
  {
    name: "TruthCert Pairwise Pro",
    featured: true,
    featuredRank: 1,
    subcategory: "Pooling",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/truthcert-course.html",
    folder: "allmeta/Truthcert1",
    path: "./Truthcert1/TruthCert-PairwisePro-v1.0-production.html",
    added: "2026-04-27",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "End-to-end pairwise meta-analysis workspace: paste data, run pooling with DL/REML/PM/HKSJ, render forest/funnel/cumulative views, export TruthCert receipts. The most-used app in the catalogue — start here for any pairwise MA.",
    note: "Loads the production HTML directly. Use ./Truthcert1/index.html for the landing page that links the bundle, paper, and backups.",
    tags: ["pairwise", "truthcert", "meta-analysis", "anchor"]
  },
  {
    name: "AdaptSim",
    folder: "adaptsim",
    path: "https://mahmood726-cyber.github.io/adaptsim/",
    added: "2026-04-20",
    collection: "existing",
    mode: "url",
    category: "Trial Design",
    summary: "Browser-based adaptive group-sequential trial simulator validated against rpact.",
    note: "Root-level project outside C:\\HTML apps, linked here for easier launch.",
    tags: ["adaptive-design", "group-sequential", "rpact"]
  },
  {
    name: "Al-Mizan",
    subcategory: "Effect-size tools",
    folder: "al-mizan",
    path: "https://mahmood726-cyber.github.io/al-mizan/",
    added: "2026-04-20",
    collection: "existing",
    mode: "url",
    category: "Evidence Synthesis",
    summary: "Evidence equipoise monitor for cumulative meta-analysis, waste estimation, and tipping-point review.",
    note: "Root-level project outside C:\\HTML apps, linked here for easier launch.",
    tags: ["equipoise", "cumulative-meta-analysis", "tsa"]
  },
  {
    name: "CardioOracle",
    folder: "cardiooracle",
    path: "https://mahmood726-cyber.github.io/cardiooracle/",
    added: "2026-04-20",
    collection: "existing",
    mode: "url",
    category: "Clinical Prediction",
    summary: "Browser-native cardiovascular trial outcome prediction tool with calibration, provenance, and training-data exploration.",
    note: "Root-level project outside C:\\HTML apps, linked here for easier launch.",
    tags: ["prediction", "clinicaltrials", "cardiology"]
  },
  {
    name: "CardioSynth Phase 0",
    folder: "cardiosynth",
    path: "https://mahmood726-cyber.github.io/cardiosynth/phase0/colchicine-stemi.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "url",
    category: "Living Meta-Analysis",
    summary: "Phase 0 living cardiology synthesis dashboard built from ClinicalTrials.gov structured results.",
    note: "This links directly to the current phase deliverable because the repo has no separate landing page yet.",
    tags: ["living-review", "cardiology", "ctgov"]
  },
  {
    name: "NICE Cardiology",
    folder: "nice-cardiology-guidance",
    path: "https://mahmood726-cyber.github.io/nice-cardiology-guidance/",
    added: "2026-04-20",
    collection: "existing",
    mode: "url",
    category: "Clinical Dashboard",
    summary: "Critical cardiology guideline review dashboard covering heart failure and acute coronary syndromes.",
    note: "Root-level project outside C:\\HTML apps, linked here for easier launch.",
    tags: ["guidelines", "cardiology", "dashboard"]
  },
  {
    name: "Focus Studio",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/meta-sprint-course.html",
    folder: "allmeta/focus-studio",
    path: "./focus-studio/index.html",
    added: "2026-04-20",
    collection: "new",
    mode: "file",
    category: "Productivity",
    summary: "A polished focus timer with task tracking, session history, and local browser persistence.",
    note: "Standalone productivity app stored in the workspace.",
    tags: ["timer", "tasks", "localstorage"]
  },
  {
    name: "Kanban Lab",
    folder: "allmeta/kanban-lab",
    path: "./kanban-lab/index.html",
    added: "2026-04-20",
    collection: "new",
    mode: "file",
    category: "Productivity",
    summary: "Drag-and-drop planning board for quick project triage with persistent columns and card notes.",
    note: "Standalone productivity app stored in the workspace.",
    tags: ["kanban", "planning", "drag-and-drop"]
  },
  {
    name: "Evidence Board",
    folder: "allmeta/evidence-board",
    path: "./evidence-board/index.html",
    added: "2026-04-20",
    collection: "new",
    mode: "file",
    category: "Research Notes",
    summary: "Structured evidence note board with confidence labels, filtering, and JSON export/import.",
    note: "Standalone research-notes app stored in the workspace.",
    tags: ["research", "notes", "export"]
  },
  {
    name: "HTA Pro",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/hta-oman-course.html",
    folder: "allmeta/HTA",
    path: "./HTA/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Health Technology Assessment",
    summary: "Browser-native Health Technology Assessment workspace covering cost-effectiveness, decision analysis, and benchmark comparisons against TreeAge.",
    note: "Large single-file app (7K+ lines) — opens directly from the file system.",
    tags: ["hta", "cost-effectiveness", "decision-analysis"]
  },
  {
    name: "IPD Meta-Pro",
    subcategory: "Pooling",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/ipd-meta-analysis-course.html",
    folder: "allmeta/IPD-Meta-Pro",
    path: "./IPD-Meta-Pro/ipd-meta-pro.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Individual Participant Data meta-analysis in a single distributable HTML artifact with PLOS ONE and F1000 submission packages.",
    note: "The real app is ipd-meta-pro.html; the index.html file is a thin stub.",
    tags: ["ipd", "meta-analysis", "individual-participant-data"]
  },
  {
    name: "Pairwise AI",
    subcategory: "Pooling",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/meta-analysis-methods-course.html",
    folder: "allmeta/Pairwiseai",
    path: "./Pairwiseai/main-screen.html",
    added: "2026-04-25",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Pairwise meta-analysis AI variant with a dedicated main-screen entry, expert-review tracker, and external validation plan.",
    note: "Companion to TruthCert Pairwise Pro — no dedicated index.html, entry is 'main-screen.html'.",
    tags: ["pairwise", "ai", "meta-analysis"]
  },
  {
    name: "Living Meta",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/living-reviews-course.html",
    folder: "allmeta/living-meta",
    path: "./living-meta/living-meta-complete.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Living Meta-Analysis",
    summary: "Self-contained living meta-analysis browser bundle with CI/container deployment scaffolding and WASM acceleration.",
    note: "Real app is living-meta-complete.html; the index.html file is a thin stub.",
    tags: ["living-review", "meta-analysis", "wasm"]
  },
  {
    name: "NMA Pro v8",
    featured: true,
    featuredRank: 2,
    course: "https://mahmood726-cyber.github.io/synthesis-courses/advanced-meta-analysis-course.html",
    folder: "allmeta/nma-pro-v2",
    path: "./nma-pro-v2/nma-pro-v8.0.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Network Meta-Analysis",
    summary: "End-to-end network meta-analysis workbench v8.0: contrast-based pooling, design-by-treatment inconsistency, node-splitting, SUCRA ranking, league tables, R benchmark harness. The canonical NMA app — start here for any network meta-analysis.",
    note: "Real app is nma-pro-v8.0.html; index.html is a thin stub.",
    tags: ["nma", "network-meta-analysis", "accessibility", "anchor"]
  },
  {
    name: "NMA Dose-Response",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/advanced-meta-analysis-course.html",
    folder: "allmeta/nma-dose-response-app",
    path: "./nma-dose-response-app/index.html",
    added: "2026-04-20",
    collection: "existing",
    mode: "file",
    category: "Network Meta-Analysis",
    summary: "Network meta-analysis for dose-response data, with 40+ novel methods and RSM editorial revisions.",
    note: "Full-featured single-file app; test files live at the app root rather than in a tests/ folder.",
    tags: ["nma", "dose-response", "novel-methods"]
  },
  {
    name: "PRISMA Flow",
    subcategory: "Reporting",
    featured: true,
    course: "https://mahmood726-cyber.github.io/synthesis-courses/meta-analysis-writing-course.html",
    folder: "allmeta/prisma-flow",
    path: "./prisma-flow/index.html",
    added: "2026-04-20",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "PRISMA 2020 flow-diagram generator: enter record counts, render an SVG flow diagram, export as SVG or PNG, save state to localStorage.",
    note: "Single-file HTML, offline, deterministic output, built-in consistency checks.",
    tags: ["prisma", "systematic-review", "flow-diagram"]
  },
  {
    name: "PRISMA-NMA Checklist",
    subcategory: "Reporting",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/advanced-meta-analysis-course.html",
    folder: "allmeta/prisma-nma",
    path: "./prisma-nma/index.html",
    added: "2026-04-25",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "PRISMA-NMA reporting checklist — Hutton 2015 NMA extension over the PRISMA 2009 base. 29 base items (27 PRISMA 2009 + 2 NMA inline at items 18 and 19) plus 5 supplementary NMA items (S1-S5). Fillable, autosaves, exports a Markdown supplement.",
    note: "Single file, offline, localStorage-backed; covers network geometry, transitivity, inconsistency, ranking metrics, and confidence assessment.",
    tags: ["prisma", "nma", "reporting", "hutton-2015"]
  },
  {
    name: "Forest Plot Viewer",
    subcategory: "Pooling",
    featured: true,
    course: "https://mahmood726-cyber.github.io/synthesis-courses/synthesis-course.html",
    folder: "allmeta/forest-plot",
    path: "./forest-plot/index.html",
    added: "2026-04-20",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Standalone forest plot from pasted (label, estimate, SE) studies. Fixed-effect and Paule-Mandel random-effects pooling with I\u00b2 and \u03c4\u00b2.",
    note: "Single-file HTML, offline, no dependencies. SVG / PNG / JSON export.",
    tags: ["forest-plot", "meta-analysis", "pooling"]
  },
  {
    name: "Funnel Plot Explorer",
    subcategory: "Publication bias",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/publication-bias-detective.html",
    folder: "allmeta/funnel-plot",
    path: "./funnel-plot/index.html",
    added: "2026-04-20",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Funnel plot with 95% and 99% pseudo-CI limits plus Egger's regression test for small-study effects (p-value via incomplete-beta t-distribution).",
    note: "Validated against scipy / statsmodels OLS. Low-k warning below 10 studies.",
    tags: ["funnel-plot", "publication-bias", "egger"]
  },
  {
    name: "RoB Traffic Light",
    subcategory: "Reporting",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/risk-of-bias-mastery-course.html",
    folder: "allmeta/rob-traffic-light",
    path: "./rob-traffic-light/index.html",
    added: "2026-04-20",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Risk-of-bias traffic-light plot plus weighted summary bar, robvis-style palette. Accepts low / some / high / unclear / na ratings in several shorthand forms.",
    note: "Matrix grid + weighted-summary view, SVG / PNG / JSON export, offline.",
    tags: ["risk-of-bias", "rob2", "robvis"]
  },
  {
    name: "Heterogeneity Explorer",
    subcategory: "Heterogeneity",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/synthesis-course.html",
    folder: "allmeta/heterogeneity",
    path: "./heterogeneity/index.html",
    added: "2026-04-20",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Q, I\u00b2 (with Q-profile CI), \u03c4\u00b2 under DL (k\u226510) / REML / PM, 95% prediction interval via t_{k-1}, Baujat diagnostic plot, and leave-one-out influence.",
    note: "Follows advanced-stats.md gates (no DL for k<10). SVG / PNG / JSON export.",
    tags: ["heterogeneity", "baujat", "prediction-interval"]
  },
  {
    name: "TSA Calculator",
    subcategory: "Sensitivity",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/cast-when-certainty-kills.html",
    folder: "allmeta/tsa",
    path: "./tsa/index.html",
    added: "2026-04-20",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Trial sequential analysis: cumulative Z-score plotted against O'Brien-Fleming alpha-spending boundaries with diversity-adjusted Required Information Size.",
    note: "Auto-RIS from target effect and power, or manual in inverse-variance units.",
    tags: ["tsa", "alpha-spending", "obrien-fleming"]
  },
  {
    name: "GRADE SoF Builder",
    subcategory: "Reporting",
    featured: true,
    course: "https://mahmood726-cyber.github.io/synthesis-courses/grade-certainty-course.html",
    folder: "allmeta/grade-sof",
    path: "./grade-sof/index.html",
    added: "2026-04-20",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Cochrane-style Summary of Findings table: outcomes, assumed and corresponding risk, relative effect, participants, four-tier GRADE certainty.",
    note: "Print-ready HTML export with standalone styles. JSON import/export.",
    tags: ["grade", "sof", "certainty-of-evidence"]
  },
  {
    name: "DTA SROC Explorer",
    subcategory: "Reporting",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/dta-course-when-the-test-lies-v4.html",
    folder: "allmeta/dta-sroc",
    path: "./dta-sroc/index.html",
    added: "2026-04-20",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Diagnostic test accuracy: per-study Se/Sp in ROC space, Moses SROC curve, and threshold-effect flag via Spearman \u03c1 between logit(Se) and logit(1-Sp).",
    note: "Applies +0.5 continuity correction only when a cell is zero (advanced-stats.md).",
    tags: ["dta", "sroc", "moses"]
  },
  {
    name: "MA Workbench",
    subcategory: "Pooling",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/synthesis-course.html",
    folder: "allmeta/workbench",
    path: "./workbench/index.html",
    added: "2026-04-20",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "One paste, full MA: live forest / funnel / heterogeneity / TSA previews with deep-links to dedicated apps. One-click full HTML report export.",
    note: "Writes to the shared ma-studies-v1 bus so the other apps can pull.",
    tags: ["workbench", "integrator", "bus"]
  },
  {
    name: "Meta-Regression",
    subcategory: "Heterogeneity",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/meta-analysis-methods-course.html",
    folder: "allmeta/meta-regression",
    path: "./meta-regression/index.html",
    added: "2026-04-20",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Random-effects meta-regression with one moderator. Paule-Mandel \u03c4\u00b2, Knapp-Hartung t(k-2) CIs with max(1, \u2026) HKSJ floor.",
    note: "Bus-aware; exports a metafor R script for PM + knha replication.",
    tags: ["meta-regression", "knapp-hartung", "moderator"]
  },
  {
    name: "Cumulative + Subgroup",
    subcategory: "Sensitivity",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/meta-analysis-methods-course.html",
    folder: "allmeta/cumulative-subgroup",
    path: "./cumulative-subgroup/index.html",
    added: "2026-04-20",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Cumulative MA over study order/year; subgroup analysis with between-subgroup Q test and I\u00b2 of differences.",
    note: "Two views in one app. Reads from and writes to the shared bus.",
    tags: ["cumulative", "subgroup", "temporal"]
  },
  {
    name: "WebR Validator",
    subcategory: "Sensitivity",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/becoming-methodologist.html",
    folder: "allmeta/webr-validator",
    path: "./webr-validator/index.html",
    added: "2026-04-20",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Optional in-browser R (WebR) validation against metafor. Alternative paste-back path for local R. HMAC-SHA256 signed TruthCert receipts.",
    note: "WebR loads on explicit click (~30 MB download). URL configurable for self-hosting. Signing key never stored.",
    tags: ["webr", "validation", "truthcert", "hmac"]
  },
  {
    name: "Bayesian MA",
    subcategory: "Pooling",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/advanced-meta-analysis-course.html",
    folder: "allmeta/bayesian-ma",
    path: "./bayesian-ma/index.html",
    added: "2026-04-20",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Conjugate normal-normal Bayesian meta-analysis: closed-form posterior for \u03b8 given studies and a normal prior; 95% CrI, P(\u03b8<c), ROPE probability, prior-sensitivity slider.",
    note: "No MCMC, no stan, no external deps. Deterministic. Bus-aware.",
    tags: ["bayesian", "conjugate", "posterior"]
  },
  {
    name: "PRISMA Screening",
    subcategory: "Reporting",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/meta-sprint-course.html",
    folder: "allmeta/prisma-screen",
    path: "./prisma-screen/index.html",
    added: "2026-04-20",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Pre-MA citation screening: tag include/exclude/duplicate/maybe, Cohen's \u03ba for dual-reviewer agreement, PRISMA-shaped count roll-up, one-click push into the PRISMA Flow generator.",
    note: "Outputs feed directly into prisma-flow/index.html via the prisma-flow-v1 key.",
    tags: ["prisma", "screening", "kappa"]
  },
  {
    name: "Design",
    subcategory: "Protocol",
    folder: "allmeta/design",
    path: "./design/index.html",
    added: "2026-06-08",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Design a systematic review front-to-back: frame the question in PICO/PECO/PICOS/PICOT, set eligibility criteria, and auto-build a boolean search strategy (multi-word terms quoted, synonyms OR-grouped, PICO blocks AND-joined). One click seeds the multi-source Search query, and your include/exclude terms flow into Screen's relevance ranking — via the shared sr-project-v1 envelope. Exports Markdown/JSON; optional AI drafting via local-agent handoff or BYO-key.",
    note: "Writes sr-project-v1 (read by search/index.html 'Load PICO from Design' and by screen for relevance terms). Focused design entry point; the full PRISMA-P/PROSPERO editors are the Protocols and PROSPERO apps. App 3/3 of the search→design→screen pipeline.",
    tags: ["protocol", "pico", "peco", "eligibility", "search-strategy", "prisma-p", "pipeline", "local-first"]
  },
  {
    name: "Search",
    subcategory: "Search",
    folder: "allmeta/search",
    path: "./search/index.html",
    added: "2026-06-08",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Multi-source literature search in the browser: one query across Europe PMC (PubMed + abstracts), Crossref, OpenAlex and ClinicalTrials.gov v2, with cross-source dedup, free deterministic query expansion (synonyms, abbreviations, brand/generic drug names, British/American spellings), TF-IDF cosine relevance ranking, and OpenAlex citation-chasing (snowballing — references + citing papers) to lift recall toward Elicit's semantic index without a key or an account. One-click handoff into Screen via sr-records-v1. Optional AI query expansion via local-agent handoff or BYO-key; API calls go straight from your browser to each public endpoint.",
    note: "Seeds queries from a Design protocol (sr-project-v1); hands off to screen/index.html via sr-records-v1. Exports RIS/CSV/JSON. Part of the Search→Screen→Extract→meta pipeline.",
    tags: ["search", "elicit", "europepmc", "pubmed", "crossref", "openalex", "clinicaltrials", "dedup", "query-expansion", "semantic-ranking", "snowballing", "local-first"]
  },
  {
    name: "Screen",
    subcategory: "Screening",
    folder: "allmeta/screen",
    path: "./screen/index.html",
    added: "2026-06-08",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Rayyan-class title/abstract screening, fully local: keyboard-driven record cards, dual-reviewer with conflict resolution and Cohen's κ, RIS / PubMed .nbib / CSV / JSON import, inline dedup (DOI + trigram-Jaccard), and a free in-browser active-learning classifier (TF-IDF + logistic regression) that re-ranks records from a handful of labels — transparent, reproducible, no key. AI (NL screening rationale) is strictly optional: local-agent handoff (export a task for Claude Code/Codex/Gemini CLI, re-import JSON — zero cost) or bring-your-own-key. One-click PRISMA Flow counts. No account, no paywall, no upload.",
    note: "Imports RIS/.nbib/CSV/JSON; pushes PRISMA counts to prisma-flow/index.html via prisma-flow-v1; exports includes as RIS for downstream extraction. Free deterministic+ML core; AI off by default. Benchmarked on the Cohen ACE-Inhibitors TAR corpus: WSS@95=0.67. Part of the Search→Screen→Extract→meta pipeline.",
    tags: ["screening", "rayyan", "active-learning", "dual-reviewer", "kappa", "dedup", "prisma", "ris", "local-first", "ai-optional", "collaboration", "wss95"]
  },
  {
    name: "Extract",
    subcategory: "Extraction",
    folder: "allmeta/extract",
    path: "./extract/index.html",
    added: "2026-06-08",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Automated structured data extraction for systematic reviews, free and reproducible where Elicit meters it: a transparent in-browser engine pulls PICO, sample sizes (total + per-arm), effect sizes with 95% CIs (HR/RR/OR/MD/SMD), event counts and risk-of-bias cues from included records, then feeds the result straight into the meta-analysis apps via the ma-studies-v1 bus (ratio effects as ln with SE from the CI). Optional one-click handoff to your own agent (Claude Code/Codex/Gemini CLI) or the installable rct-extractor engine (17 specialties), plus BYO-key — all opt-in.",
    note: "Imports included records from Screen (screen-v1); exports sr-extract-v1 (JSON/CSV); writes ma-studies-v1 read by forest-plot and the pooling apps. Engine reads title+abstract — a reviewable first pass, with full-text handoff for the rest. App 4 of the Search→Screen→Extract→meta-analysis pipeline.",
    tags: ["extraction", "elicit", "pico", "effect-size", "risk-of-bias", "meta-analysis", "ma-studies-v1", "pipeline", "local-first", "ai-optional"]
  },
  {
    name: "Paper Studio",
    subcategory: "Reporting",
    folder: "allmeta/paper",
    path: "./paper/index.html",
    added: "2026-06-10",
    collection: "new",
    mode: "file",
    category: "Reporting",
    summary: "Turn a finished review into a manuscript, offline. PICO, included studies, pooled results and PRISMA counts are auto-filled from your review via the cross-tool buses (sr-project-v1 / sr-records-v1 / ma-studies-v1 / ma-pooled-v1); you write the interpretation in guided sections with worked examples and readiness checks. References are built deterministically from the included studies — no hallucinated citations. Exports a clean PDF, Word/HTML/Markdown, a figures bundle, and submittable supplementary (PRISMA 2020 checklist, AMSTAR-2, search strategy). The report stage of the Design→Search→Screen→Extract→synthesis pipeline.",
    note: "Reads the buses through alm-paper-bridge (assembles the host state); the deterministic Paper Studio engine is ported from RapidMeta. 100% browser-side; nothing is uploaded.",
    tags: ["paper", "manuscript", "reporting", "write-up", "prisma", "references", "pipeline", "student", "ma-pooled-v1", "local-first"]
  },
  {
    name: "Correlation MA",
    folder: "allmeta/correlation-ma",
    path: "./correlation-ma/index.html",
    added: "2026-06-01",
    collection: "new",
    mode: "file",
    category: "Pooling",
    summary: "Random-effects meta-analysis of correlation coefficients via Fisher's z transform (ZCOR), back-transformed to r with DL/PM/REML τ², HKSJ, and a t_{k-1} prediction interval. Verified against metafor::rma(measure=\"ZCOR\").",
    tags: ["correlation", "fisher-z", "zcor", "pooling"]
  },
  {
    name: "UWLS (multiplicative heterogeneity)",
    folder: "allmeta/multiplicative-ma",
    path: "./multiplicative-ma/index.html",
    added: "2026-06-07",
    collection: "existing",
    mode: "file",
    category: "Pooling",
    summary: "Unrestricted weighted least squares / multiplicative-heterogeneity meta-analysis (Stanley & Doucouliagos): inflate within-study variances by φ=Q/(k−1) instead of adding τ². Point = fixed-effect estimate, SE = SE_FE·√φ, t_{k−1} CI — identical to lm(yi~1, weights=1/vi). Shown side-by-side with fixed-effect and additive random-effects.",
    note: "Recommended as the PRIMARY estimator for observational meta-analyses (IV-RE weights amplify SE-manipulation); RE as sensitivity. Verified vs R lm to 1e-8.",
    tags: ["uwls", "multiplicative", "heterogeneity", "stanley", "observational", "pooling"]
  },
  {
    name: "Multiplicative-heterogeneity NMA",
    folder: "allmeta/multiplicative-nma",
    path: "./multiplicative-nma/index.html",
    added: "2026-06-07",
    collection: "new",
    mode: "file",
    category: "Network Meta-Analysis",
    summary: "The network generalisation of UWLS: relative effects equal the fixed-effect (common-effect) contrast-based NMA estimates, with every SE inflated by √φ where φ=Q/(n−p), instead of adding a between-study variance τ². Reported alongside additive random-effects (Paule-Mandel τ²) with an AIC verdict — prefer multiplicative when ΔAIC≥2.",
    note: "Two-arm contrast scope (multi-arm needs shared-arm covariance). Common-effect fit + Q match netmeta; engine cross-verified vs an independent WLS oracle. Primary estimator for observational networks.",
    tags: ["nma", "network", "multiplicative", "uwls", "heterogeneity", "aic", "observational"]
  },
  {
    name: "Dose-Response MA",
    folder: "allmeta/dose-response-ma",
    path: "./dose-response-ma/index.html",
    added: "2026-06-01",
    collection: "new",
    mode: "file",
    category: "Pooling",
    summary: "Two-stage Greenland-Longnecker linear dose-response meta-analysis: per-study GLS slope with covariance reconstructed from the trend (case-control, incidence-rate, or cumulative-incidence designs), pooled by REML. Verified against dosresmeta(method=\"reml\").",
    tags: ["dose-response", "greenland-longnecker", "glst", "pooling"]
  },
  {
    name: "RMST Meta-Analysis",
    folder: "allmeta/rmst-ma",
    path: "./rmst-ma/index.html",
    added: "2026-06-01",
    collection: "new",
    mode: "file",
    category: "Pooling",
    summary: "Pool restricted mean survival time (RMST) differences across trials at a common horizon τ*, with DL/PM/REML τ², HKSJ, and a prediction interval. Differences (not ratios) per the RMST convention. Verified against metafor::rma(REML).",
    tags: ["rmst", "survival", "non-ph", "pooling"]
  },
  {
    name: "RoBMA",
    folder: "allmeta/robma",
    path: "./robma/index.html",
    added: "2026-06-01",
    collection: "new",
    mode: "file",
    category: "Publication bias",
    summary: "Robust Bayesian model-averaging over presence/absence of effect and heterogeneity (4 models), giving inclusion Bayes factors for effect and for heterogeneity via adaptive-Simpson marginal likelihoods. Core BFs verified against R integrate(); one-click deep-link to the full RoBMA R package for the publication-bias-adjusted ensemble.",
    tags: ["bayesian", "model-averaging", "bayes-factor", "publication-bias"]
  },
  {
    name: "Project Workspace",
    folder: "allmeta/project",
    path: "./project/index.html",
    added: "2026-06-01",
    collection: "new",
    mode: "file",
    category: "Productivity",
    summary: "Save your whole allmeta review — every app's data and settings, plus the shared ma-studies-v1 bus — as one offline JSON file, and restore it later or on another machine. A single-file, fully-offline alternative to RevMan project files. Round-trip verified.",
    tags: ["project", "save", "workspace", "portability", "offline"]
  },
  {
    name: "Review project (signed pipeline)",
    folder: "allmeta/review-project",
    path: "./review-project/index.html",
    added: "2026-06-06",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Run a whole systematic review as one offline, cryptographically-signed, tamper-evident bundle: protocol → search → screening → extraction → appraisal (RoB 2 / INSPECT-SR) → synthesis → robustness → certainty (GRADE) → report. Each stage's JSON output is chained by SHA-256 and the bundle is HMAC-signed; re-opening verifies the chain and pinpoints any altered stage.",
    note: "Composes the existing apps over a provenance chain; reuses the audited TruthCert signer. Reproducible SR in a single file — no server, no account.",
    tags: ["systematic-review", "pipeline", "provenance", "truthcert", "reproducible", "signed", "offline"]
  },
  {
    name: "Synthēsis Journal PDF",
    folder: "allmeta/synthesis-journal",
    path: "./synthesis-journal/index.html",
    added: "2026-06-12",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Render the synthesis on the bus as a premium, journal-grade article and print it to PDF — a browser port of the Synthēsis paper standard (synthesis-paper-spec/metapaper): Palatino typesetting, a washed structured abstract with a brand left-border, a red key-finding pull-quote, a house-rules forest figure (precision-sized study squares, one red pooled diamond), a booktabs study table, running heads, a page-of-page footer, and a CC-BY / how-to-cite block. Truth-first: every figure and number is read from ma-studies / ma-pooled; nothing is invented, and an empty bus renders a clearly-labelled demo.",
    note: "Reads the cross-tool buses (pooled estimate verbatim from ma-pooled; never re-pooled). Fully offline; figures are inline SVG, no CDN.",
    tags: ["pdf", "manuscript", "journal", "typesetting", "forest", "reporting", "synthesis", "ma-pooled-v1", "ma-studies-v1", "offline"]
  },
  {
    name: "Multivariate MA",
    folder: "allmeta/multivariate-ma",
    path: "./multivariate-ma/index.html",
    added: "2026-06-01",
    collection: "new",
    mode: "file",
    category: "Pooling",
    summary: "Multivariate / multiple-outcome meta-analysis (mvmeta): jointly pool two correlated outcomes using each study's within-study covariance, with an unstructured between-study covariance estimated by REML (μ by GLS; G by Cholesky-parameterised Nelder-Mead). Reports both pooled means with CIs, between-study SDs, the between-study correlation, and a joint-outcome plot with a 95% confidence ellipse. Pure-JS, matches metafor::rma.mv on Berkey 1998 to ~1e-7.",
    tags: ["multivariate", "multiple-outcome", "mvmeta", "rma.mv", "pooling"]
  },
  {
    name: "Parity Ledger",
    featured: true,
    folder: "allmeta/parity",
    path: "./parity/index.html",
    added: "2026-06-01",
    collection: "new",
    mode: "file",
    category: "Reporting",
    summary: "The provability dashboard: every quantitative allmeta method backed by a committed R-parity test, asserting agreement with a named R reference (metafor, mada, dosresmeta, robumeta, RoBMA, EValue, metasens…) to a stated number of decimals, re-run in CI. Generated from the test files themselves, so it cannot claim a method that isn't verified — 63 R-parity tests (44 Playwright specs + 19 per-app Python tests), 250 numeric assertions, 41 distinct R oracles.",
    tags: ["parity", "verification", "reproducibility", "metafor", "provenance"]
  }
];
