window.HTML_APPS_PROJECTS = [
  {
    name: "RCT Extractor",
    featured: true,
    course: "https://mahmood726-cyber.github.io/synthesis-courses/ai-meta-analysis-course.html",
    folder: "C:\\HTML apps\\rct-extractor",
    path: "./rct-extractor/index.html",
    collection: "existing",
    mode: "file",
    category: "Screening & Extraction",
    summary: "Extract effect estimates (HR, OR, RR, MD, SMD, IRR, RD) from RCT publications via a locally-running rct-extractor-v2 FastAPI server (180+ regex patterns, 97.7% sensitivity). Optional local-LLM consensus layer, PDF upload with browser-side text extraction, one-click hand-off to MA Workbench / Forest Plot Viewer.",
    note: "Requires a one-time Python install; see the in-app hint.",
    tags: ["extraction", "pdf", "rct", "regex", "fastapi"]
  },
  {
    name: "Local AI setup",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/ai-meta-analysis-course.html",
    folder: "C:\\HTML apps\\local-ai",
    path: "./local-ai/index.html",
    collection: "existing",
    mode: "file",
    category: "R / WASM",
    summary: "One-page guide to running a local LLM via Ollama so allmeta apps can do structured extraction (PICO from abstracts, effect sizes from results paragraphs) — without sending any data off your device. Live connectivity check included.",
    note: "Complements WebR Studio. PICO Formulator and Effect-Size Converter already wire into it.",
    tags: ["ollama", "local-ai", "llm", "extraction", "privacy"]
  },
  {
    name: "WebR Studio",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/becoming-methodologist.html",
    folder: "C:\\HTML apps\\webr-studio",
    path: "./webr-studio/index.html",
    collection: "existing",
    mode: "file",
    category: "R / WASM",
    summary: "Run real R in your browser via WebR. Curated templates for metafor, meta, netmeta, metasens, bayesmeta, and mada — genuine CRAN package output, no server. First load downloads ~30 MB.",
    note: "Use for gold-standard validation and analyses the browser-native apps can only approximate.",
    tags: ["webr", "r", "wasm", "metafor", "netmeta", "bayesmeta", "metasens", "mada"]
  },
  {
    name: "Local R Install",
    folder: "C:\\HTML apps\\local-install",
    path: "./local-install/index.html",
    collection: "existing",
    mode: "file",
    category: "R / WASM",
    summary: "One-stop recipe for installing R + the allmeta CRAN stack locally, including Stan / JAGS back-ends for real MCMC (gemtc, multinma, rstan, cmdstanr, brms, bayesmeta). Reproduces every browser app in native R.",
    note: "For the 10% of tasks that need local compute.",
    tags: ["r", "install", "stan", "jags", "local", "reproducibility"]
  },
  {
    name: "NMA Global Inconsistency",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/advanced-meta-analysis-course.html",
    folder: "C:\\HTML apps\\nma-global-inconsistency",
    path: "./nma-global-inconsistency/index.html",
    collection: "existing",
    mode: "file",
    category: "Network Meta-Analysis",
    summary: "Fit NMA under consistency vs full design-inconsistency model; compare with a likelihood-ratio test (Higgins 2012). Per-design residual plot to localise inconsistent loops.",
    note: "Complements the per-comparison node-splitting tool.",
    tags: ["nma", "inconsistency", "lr-test", "design-by-treatment"]
  },
  {
    name: "p-curve / p-uniform",
    subcategory: "Publication bias",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/publication-bias-detective.html",
    folder: "C:\\HTML apps\\p-curve",
    path: "./p-curve/index.html",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Publication-bias-robust effect estimation from p-values alone. Right-skew and flatness tests (Simonsohn 2014) plus p-uniform effect size (van Assen 2015).",
    note: "Uses only significant p-values; complements Funnel / PET-PEESE.",
    tags: ["p-curve", "p-uniform", "evidential-value", "p-hacking"]
  },
  {
    name: "Limit meta-analysis",
    subcategory: "Publication bias",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/publication-bias-detective.html",
    folder: "C:\\HTML apps\\limit-ma",
    path: "./limit-ma/index.html",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Rücker limit meta-analysis: extrapolates to the zero-variance limit to adjust for small-study effects. Outputs the FE, RE, and limit estimate with a funnel overlay.",
    note: "Matches metasens::limitmeta (simplified).",
    tags: ["limit-meta", "rucker", "small-study-adjustment"]
  },
  {
    name: "GOSH Meta-Regression",
    subcategory: "Heterogeneity",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/advanced-meta-analysis-course.html",
    folder: "C:\\HTML apps\\gosh-metareg",
    path: "./gosh-metareg/index.html",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "All-subset meta-regression: for every non-trivial subset, fit a single-moderator meta-regression and scatter β against residual I². Reveals whether the moderator effect is subset-robust.",
    note: "k ≤ 18 studies. Extends GOSH with a regression layer.",
    tags: ["gosh", "meta-regression", "robustness", "moderator"]
  },
  {
    name: "PowerMA / RIS",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/cast-when-certainty-kills.html",
    folder: "C:\\HTML apps\\powerma",
    path: "./powerma/index.html",
    collection: "existing",
    mode: "file",
    category: "Trial Design",
    summary: "Pre-meta-analysis power and Required Information Size (RIS) calculator. Binary (RRR) or continuous (MD/SMD) outcomes, α and power, with I² and D² heterogeneity inflation per Wetterslev TSA conventions.",
    note: "Plan a review's target N before starting.",
    tags: ["power", "ris", "sample-size", "tsa"]
  },
  {
    name: "GRADE-CERQual",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/grade-certainty-course.html",
    folder: "C:\\HTML apps\\cerqual",
    path: "./cerqual/index.html",
    collection: "existing",
    mode: "file",
    category: "Qualitative Synthesis",
    summary: "Confidence in qualitative-review findings. Rate four components (methodological limitations, coherence, adequacy, relevance) per finding; derives High / Moderate / Low / Very low confidence.",
    note: "Lewin 2018. Pairs with Thematic Synthesis.",
    tags: ["cerqual", "qualitative", "confidence", "certainty"]
  },
  {
    name: "ROBINS-E",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/risk-of-bias-mastery-course.html",
    folder: "C:\\HTML apps\\robins-e",
    path: "./robins-e/index.html",
    collection: "existing",
    mode: "file",
    category: "Risk of Bias",
    summary: "Risk of Bias in Non-randomized Studies of Exposures: 7 domains with signaling questions and algorithmic judgments, plus traffic-light chart.",
    note: "Higgins 2022 (draft). For exposure epidemiology.",
    tags: ["robins-e", "exposure", "environmental", "risk-of-bias"]
  },
  {
    name: "Citation Chaser",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/meta-analysis-topic-selection-course.html",
    folder: "C:\\HTML apps\\citation-chaser",
    path: "./citation-chaser/index.html",
    collection: "existing",
    mode: "file",
    category: "Search",
    summary: "Forward and backward citation chasing via the OpenAlex API. Paste DOIs as seeds; discover references and citing works. Deduplicated, exportable as CSV, with year histogram.",
    note: "Uses OpenAlex public API — no key required.",
    tags: ["citation-chasing", "openalex", "search", "reference-mining"]
  },
  {
    name: "NMA Inconsistency",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/advanced-meta-analysis-course.html",
    folder: "C:\\HTML apps\\nma-inconsistency",
    path: "./nma-inconsistency/index.html",
    collection: "existing",
    mode: "file",
    category: "Network Meta-Analysis",
    summary: "Node-splitting (Dias 2010) and design-by-treatment inconsistency test (Higgins 2012) for network meta-analysis. Compares direct vs indirect estimates per comparison.",
    note: "Critical check before interpreting NMA results.",
    tags: ["nma", "inconsistency", "node-splitting", "dbt"]
  },
  {
    name: "Bucher Indirect",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/advanced-meta-analysis-course.html",
    folder: "C:\\HTML apps\\bucher",
    path: "./bucher/index.html",
    collection: "existing",
    mode: "file",
    category: "Network Meta-Analysis",
    summary: "Bucher (1997) indirect comparison: estimate A vs B from direct A vs C and B vs C, with log-scale back-transform for ratios.",
    note: "Simplest possible indirect comparison — the building block of NMA.",
    tags: ["bucher", "indirect-comparison", "itc"]
  },
  {
    name: "Multi-level MA",
    subcategory: "Pooling",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/advanced-meta-analysis-course.html",
    folder: "C:\\HTML apps\\multilevel-ma",
    path: "./multilevel-ma/index.html",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Three-level random-effects meta-analysis for dependent effect sizes nested within studies. Separates within-study (τ²_within) from between-study (τ²_study) heterogeneity.",
    note: "Mirrors metafor::rma.mv with a moment-based iteration.",
    tags: ["multi-level", "three-level", "nested", "rma.mv"]
  },
  {
    name: "Pub-bias Tests",
    subcategory: "Publication bias",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/publication-bias-detective.html",
    folder: "C:\\HTML apps\\pubbias-tests",
    path: "./pubbias-tests/index.html",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Suite of small-study-effect tests beyond Egger: Begg-Mazumdar rank correlation, Peters (for binary), Harbord-Egger, and Thompson-Sharp multiplicative.",
    note: "Different tests have different power against different bias mechanisms — report multiple.",
    tags: ["pub-bias", "egger", "begg", "peters", "harbord", "thompson"]
  },
  {
    name: "Copas selection",
    subcategory: "Publication bias",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/publication-bias-detective.html",
    folder: "C:\\HTML apps\\copas",
    path: "./copas/index.html",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Copas selection model: sensitivity of the pooled effect across plausible selection strengths γ. Shows how the adjusted estimate shifts as the assumed unpublished fraction grows.",
    note: "Simplified browser implementation. Full MLE in metasens::copas.",
    tags: ["copas", "pub-bias", "selection-model", "sensitivity"]
  },
  {
    name: "Influence Diagnostics",
    subcategory: "Heterogeneity",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/advanced-meta-analysis-course.html",
    folder: "C:\\HTML apps\\influence",
    path: "./influence/index.html",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Per-study influence on a random-effects MA: Cook's distance, hat values, studentized residuals, DFFITS, covariance ratio, leave-one-out pooled estimates, plus an influence plot.",
    note: "Mirrors metafor::influence(). Flags studies in red on thresholds.",
    tags: ["influence", "cooks-distance", "dffits", "hat", "leave-one-out"]
  },
  {
    name: "Bayesian MA — MCMC",
    subcategory: "Pooling",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/advanced-meta-analysis-course.html",
    folder: "C:\\HTML apps\\bayesian-mcmc",
    path: "./bayesian-mcmc/index.html",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Real Gibbs MCMC for random-effects meta-analysis. Multi-chain with R-hat and ESS diagnostics. Posterior densities for μ and τ, trace plot, and predictive interval.",
    note: "For serious use: bayesmeta / RoBMA / Stan. This is a browser-native implementation.",
    tags: ["bayesian", "mcmc", "gibbs", "predictive", "bayesmeta"]
  },
  {
    name: "MH / Peto pooling",
    subcategory: "Pooling",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/meta-analysis-methods-course.html",
    folder: "C:\\HTML apps\\mh-peto",
    path: "./mh-peto/index.html",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Mantel-Haenszel pooling for OR/RR/RD and Peto one-step OR. Recommended for rare events (&lt; 1%) — no continuity correction required.",
    note: "Cochrane Handbook 10.4.4.",
    tags: ["mantel-haenszel", "peto", "rare-events", "2x2"]
  },
  {
    name: "Thematic Synthesis",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/qualitative-evidence-synthesis-course.html",
    folder: "C:\\HTML apps\\thematic-synthesis",
    path: "./thematic-synthesis/index.html",
    collection: "existing",
    mode: "file",
    category: "Qualitative Synthesis",
    summary: "Organise qualitative evidence for systematic reviews. Add participant quotes with study source, descriptive code, and analytical theme, then view as a hierarchical theme tree. Exports themed JSON.",
    note: "Thomas & Harden (2008) thematic-synthesis method.",
    tags: ["qualitative", "thematic-synthesis", "coding"]
  },
  {
    name: "Network MA (SUCRA)",
    featured: true,
    course: "https://mahmood726-cyber.github.io/synthesis-courses/advanced-meta-analysis-course.html",
    folder: "C:\\HTML apps\\bayesian-nma",
    path: "./bayesian-nma/index.html",
    collection: "existing",
    mode: "file",
    category: "Network Meta-Analysis",
    summary: "Contrast-based NMA under a consistency model via weighted least squares, with Monte-Carlo posterior sampling for SUCRA treatment rankings. Network diagram, forest of contrasts, SUCRA bars.",
    note: "Fast approximation suitable for exploration. Use MCMC software for publication.",
    tags: ["nma", "sucra", "consistency", "ranking"]
  },
  {
    name: "Component NMA",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/advanced-meta-analysis-course.html",
    folder: "C:\\HTML apps\\component-nma",
    path: "./component-nma/index.html",
    collection: "existing",
    mode: "file",
    category: "Network Meta-Analysis",
    summary: "Additive component network meta-analysis (Welton 2009) for multi-component interventions. Decomposes complex interventions into per-component effects and derives implied combination effects.",
    note: "Assumes additivity on the analysis scale; add interaction terms for synergy.",
    tags: ["component-nma", "complex-interventions", "additive"]
  },
  {
    name: "MCID & NI margin",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/hta-oman-course.html",
    folder: "C:\\HTML apps\\mcid",
    path: "./mcid/index.html",
    collection: "existing",
    mode: "file",
    category: "Trial Design",
    summary: "Minimum clinically important difference via distribution-based (0.5·SD, 1·SEM, SDC) and anchor-based (Juniper) methods, plus a non-inferiority margin derived from active-comparator effect and preservation fraction.",
    note: "Triangulate multiple methods; MCID depends on context.",
    tags: ["mcid", "non-inferiority", "ni-margin", "responder"]
  },
  {
    name: "ROBINS-I",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/risk-of-bias-mastery-course.html",
    folder: "C:\\HTML apps\\robins-i",
    path: "./robins-i/index.html",
    collection: "existing",
    mode: "file",
    category: "Risk of Bias",
    summary: "Risk of Bias in Non-randomized Studies of Interventions: 7 domains with signaling questions and algorithmic Low/Moderate/Serious/Critical judgments, plus traffic-light chart.",
    note: "Sterne 2016 decision rules. For non-randomized intervention studies.",
    tags: ["robins-i", "non-randomized", "risk-of-bias", "appraisal"]
  },
  {
    name: "QUADAS-2",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/risk-of-bias-mastery-course.html",
    folder: "C:\\HTML apps\\quadas-2",
    path: "./quadas-2/index.html",
    collection: "existing",
    mode: "file",
    category: "Risk of Bias",
    summary: "Quality Assessment of Diagnostic Accuracy Studies 2: four domains (patient selection, index test, reference standard, flow & timing) rated for risk of bias and applicability, with traffic-light chart.",
    note: "Whiting 2011. For DTA studies — pairs with DTA SROC Explorer and HSROC.",
    tags: ["quadas-2", "dta", "risk-of-bias", "applicability"]
  },
  {
    name: "AMSTAR-2",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/umbrella-reviews-course.html",
    folder: "C:\\HTML apps\\amstar-2",
    path: "./amstar-2/index.html",
    collection: "existing",
    mode: "file",
    category: "Risk of Bias",
    summary: "A Measurement Tool to Assess systematic Reviews 2: 16 items with 7 marked critical; derives an overall confidence rating (High / Moderate / Low / Critically Low) from the critical-flaw and non-critical-weakness counts.",
    note: "Shea 2017. For appraising existing systematic reviews.",
    tags: ["amstar-2", "systematic-review-appraisal", "umbrella-review"]
  },
  {
    name: "CINeMA (NMA confidence)",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/grade-certainty-course.html",
    folder: "C:\\HTML apps\\cinema",
    path: "./cinema/index.html",
    collection: "existing",
    mode: "file",
    category: "Network Meta-Analysis",
    summary: "Confidence In Network Meta-Analysis: rate six domains (within-study bias, reporting, indirectness, imprecision, heterogeneity, incoherence) per comparison; derives High / Moderate / Low / Very low. Heatmap view.",
    note: "Nikolakopoulou 2020.",
    tags: ["cinema", "nma", "confidence", "certainty"]
  },
  {
    name: "HSROC / Bivariate DTA",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/dta-course-when-the-test-lies-v4.html",
    folder: "C:\\HTML apps\\hsroc",
    path: "./hsroc/index.html",
    collection: "existing",
    mode: "file",
    category: "Diagnostic Test Accuracy",
    summary: "Bivariate random-effects DTA meta-analysis on logit(Se) and logit(1-Sp), with summary operating point and an HSROC curve derived from the mean linear predictor. Approximates Reitsma via IGLS.",
    note: "For rigorous estimates use R's mada; this is a browser-native sketch.",
    tags: ["hsroc", "sroc", "bivariate", "dta", "reitsma"]
  },
  {
    name: "GOSH Plot",
    subcategory: "Heterogeneity",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/advanced-meta-analysis-course.html",
    folder: "C:\\HTML apps\\gosh",
    path: "./gosh/index.html",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Graphical display of study heterogeneity: enumerate every non-empty subset of studies (≤18 studies), compute its pooled effect and I², and scatter on a (mu, I²) plane. Clusters reveal influential studies or subgroup structure.",
    note: "Olkin, Dahabreh, Trikalinos 2012.",
    tags: ["gosh", "heterogeneity", "subset", "influence"]
  },
  {
    name: "PICO Formulator",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/meta-analysis-topic-selection-course.html",
    folder: "C:\\HTML apps\\pico",
    path: "./pico/index.html",
    collection: "existing",
    mode: "file",
    category: "Planning",
    summary: "Frame a review question as PICO, PECO, PICOS, or PICOT. Generates a one-sentence question and a boolean-search skeleton, plus a visual PICO wheel.",
    note: "Pairs with the Search Strategy Translator as the next step.",
    tags: ["pico", "question-framework", "planning"]
  },
  {
    name: "PRISMA 2020 Checklist",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/meta-analysis-writing-course.html",
    folder: "C:\\HTML apps\\prisma-checklist",
    path: "./prisma-checklist/index.html",
    collection: "existing",
    mode: "file",
    category: "Reporting",
    summary: "Interactive PRISMA 2020 checklist — all 27 items with status / location fields, progress donut, and JSON export/load.",
    note: "Based on Page et al. 2021.",
    tags: ["prisma-2020", "checklist", "reporting"]
  },
  {
    name: "Search Strategy Translator",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/meta-analysis-topic-selection-course.html",
    folder: "C:\\HTML apps\\search-translator",
    path: "./search-translator/index.html",
    collection: "existing",
    mode: "file",
    category: "Search",
    summary: "Translate a PubMed search into Embase (Emtree) and Cochrane CENTRAL syntax. Field tags, MeSH, and operators are rewritten with warnings for unmapped terms.",
    note: "Syntactic aid — always proof-read the output.",
    tags: ["search", "pubmed", "embase", "central", "translation"]
  },
  {
    name: "Median → Mean/SD",
    subcategory: "Effect-size tools",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/meta-analysis-methods-course.html",
    folder: "C:\\HTML apps\\median-to-mean",
    path: "./median-to-mean/index.html",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Estimate mean and SD from reported median, IQR, min, and max using Wan 2014, Luo 2018, and Shi 2020 formulas. Three scenarios: 5-number / 3-number / IQR-only.",
    note: "Modern default: Luo mean + Shi SD.",
    tags: ["mean-sd", "median", "iqr", "wan", "luo", "shi"]
  },
  {
    name: "RoB 2",
    featured: true,
    course: "https://mahmood726-cyber.github.io/synthesis-courses/risk-of-bias-mastery-course.html",
    folder: "C:\\HTML apps\\rob2",
    path: "./rob2/index.html",
    collection: "existing",
    mode: "file",
    category: "Risk of Bias",
    summary: "Cochrane Risk of Bias 2: signaling questions across 5 domains with algorithmic per-domain and overall judgements, plus traffic-light chart.",
    note: "Sterne 2019 decision rules. For RCTs.",
    tags: ["rob-2", "cochrane", "risk-of-bias", "appraisal"]
  },
  {
    name: "PET-PEESE + Trim-and-Fill",
    subcategory: "Publication bias",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/publication-bias-detective.html",
    folder: "C:\\HTML apps\\pet-peese",
    path: "./pet-peese/index.html",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Publication-bias adjustments: PET, PEESE, Stanley–Doucouliagos conditional procedure, and Duval–Tweedie trim-and-fill with L₀ / R₀ estimators. Funnel plot overlays the adjustments.",
    note: "Goes beyond Egger's test when asymmetry is present.",
    tags: ["publication-bias", "pet", "peese", "trim-and-fill", "funnel-plot"]
  },
  {
    name: "Proportion MA",
    subcategory: "Pooling",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/meta-analysis-methods-course.html",
    folder: "C:\\HTML apps\\proportion-ma",
    path: "./proportion-ma/index.html",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Meta-analysis of proportions / incidences. Freeman-Tukey double-arcsine, logit, or raw pooling with DL or Paule-Mandel τ². Clopper-Pearson per-study CIs; forest plot.",
    note: "For single-arm event rates (e.g., adverse-event incidence, diagnostic yield).",
    tags: ["proportion", "single-arm", "freeman-tukey", "logit"]
  },
  {
    name: "K-M IPD Reconstructor",
    subcategory: "Effect-size tools",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/ipd-meta-analysis-course.html",
    folder: "C:\\HTML apps\\km-reconstructor",
    path: "./km-reconstructor/index.html",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Reconstruct individual patient data (event times + censoring) from a digitized Kaplan-Meier curve plus at-risk table. Guyot 2012 algorithm. Exports IPD CSV and overlays the fit.",
    note: "Use WebPlotDigitizer to get curve points from published figures.",
    tags: ["kaplan-meier", "ipd", "survival", "guyot"]
  },
  {
    name: "Citation Dedup",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/meta-sprint-course.html",
    folder: "C:\\HTML apps\\citation-dedup",
    path: "./citation-dedup/index.html",
    collection: "existing",
    mode: "file",
    category: "Screening & Extraction",
    summary: "Flag duplicate citations in a pasted list via DOI match, normalised-title trigram Jaccard, first-author surname, and year tolerance. Export cleaned CSV or grouped JSON.",
    note: "Pairs with Screenr as the upstream dedup step before title/abstract screening.",
    tags: ["deduplication", "systematic-review", "jaccard", "trigram"]
  },
  {
    name: "Effect-Size Converter",
    subcategory: "Effect-size tools",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/meta-analysis-methods-course.html",
    folder: "C:\\HTML apps\\effect-size-converter",
    path: "./effect-size-converter/index.html",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Convert between OR, RR, RD, SMD, MD, and HR. Derive standard errors from t, F, p-value, or CI. Cox's √3/π transform for OR↔SMD; delta-method propagation for OR↔RR.",
    note: "Browser-only, no backend. Live forest comparison on the SMD scale.",
    tags: ["effect-size", "conversion", "standard-error", "delta-method"]
  },
  {
    name: "Screenr",
    folder: "C:\\Projects\\rayyanreplacement",
    path: "https://mahmood726-cyber.github.io/rayyanreplacement/",
    collection: "existing",
    mode: "url",
    category: "Screening & Extraction",
    summary: "Browser-only Rayyan/Covidence alternative: dual screening with conflict detection, SAFE stopping rules, ML prioritization (TF-IDF + logistic regression), Cohen's κ, and structured data extraction.",
    note: "Hosted as its own GitHub Pages site; linked here as the canonical screening workbench.",
    tags: ["screening", "rayyan", "dual-reviewer", "ml-prioritization", "data-extraction"]
  },
  {
    name: "Dose Response Pro",
    subcategory: "Effect-size tools",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/hta-oman-course.html",
    folder: "C:\\HTML apps\\dosehtml",
    path: "./dosehtml/dose-response-pro.html",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Dose-response meta-analysis in a single distributable HTML artifact with validation and CLI support alongside it.",
    note: "Canonical browser entry for the dose-response workspace.",
    tags: ["dose-response", "meta-analysis", "validated"]
  },
  {
    name: "TruthCert Pairwise Pro",
    subcategory: "Pooling",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/truthcert-course.html",
    folder: "C:\\HTML apps\\Truthcert1",
    path: "./Truthcert1/index.html",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Pairwise meta-analysis workspace with a stable landing page, production HTML build, and paper package.",
    note: "Use the landing page to reach the production build without hunting through backup artifacts.",
    tags: ["pairwise", "truthcert", "meta-analysis"]
  },
  {
    name: "AdaptSim",
    folder: "C:\\AdaptSim",
    path: "https://mahmood726-cyber.github.io/adaptsim/",
    collection: "existing",
    mode: "url",
    category: "Trial Design",
    summary: "Browser-based adaptive group-sequential trial simulator validated against rpact.",
    note: "Root-level project outside C:\\HTML apps, linked here for easier launch.",
    tags: ["adaptive-design", "group-sequential", "rpact"]
  },
  {
    name: "Al-Mizan",
    subcategory: "Effect-size tools",
    folder: "C:\\AlMizan",
    path: "https://mahmood726-cyber.github.io/al-mizan/",
    collection: "existing",
    mode: "url",
    category: "Evidence Synthesis",
    summary: "Evidence equipoise monitor for cumulative meta-analysis, waste estimation, and tipping-point review.",
    note: "Root-level project outside C:\\HTML apps, linked here for easier launch.",
    tags: ["equipoise", "cumulative-meta-analysis", "tsa"]
  },
  {
    name: "CardioOracle",
    folder: "C:\\Models\\CardioOracle",
    path: "https://mahmood726-cyber.github.io/cardiooracle/",
    collection: "existing",
    mode: "url",
    category: "Clinical Prediction",
    summary: "Browser-native cardiovascular trial outcome prediction tool with calibration, provenance, and training-data exploration.",
    note: "Root-level project outside C:\\HTML apps, linked here for easier launch.",
    tags: ["prediction", "clinicaltrials", "cardiology"]
  },
  {
    name: "CardioSynth Phase 0",
    folder: "C:\\cardiosynth",
    path: "https://mahmood726-cyber.github.io/cardiosynth/phase0/colchicine-stemi.html",
    collection: "existing",
    mode: "url",
    category: "Living Meta-Analysis",
    summary: "Phase 0 living cardiology synthesis dashboard built from ClinicalTrials.gov structured results.",
    note: "This links directly to the current phase deliverable because the repo has no separate landing page yet.",
    tags: ["living-review", "cardiology", "ctgov"]
  },
  {
    name: "NICE Cardiology",
    folder: "C:\\NICECardiology",
    path: "https://mahmood726-cyber.github.io/nice-cardiology-guidance/",
    collection: "existing",
    mode: "url",
    category: "Clinical Dashboard",
    summary: "Critical cardiology guideline review dashboard covering heart failure and acute coronary syndromes.",
    note: "Root-level project outside C:\\HTML apps, linked here for easier launch.",
    tags: ["guidelines", "cardiology", "dashboard"]
  },
  {
    name: "Focus Studio",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/meta-sprint-course.html",
    folder: "C:\\HTML apps\\focus-studio",
    path: "./focus-studio/index.html",
    collection: "new",
    mode: "file",
    category: "Productivity",
    summary: "A polished focus timer with task tracking, session history, and local browser persistence.",
    note: "Standalone productivity app stored in the workspace.",
    tags: ["timer", "tasks", "localstorage"]
  },
  {
    name: "Kanban Lab",
    folder: "C:\\HTML apps\\kanban-lab",
    path: "./kanban-lab/index.html",
    collection: "new",
    mode: "file",
    category: "Productivity",
    summary: "Drag-and-drop planning board for quick project triage with persistent columns and card notes.",
    note: "Standalone productivity app stored in the workspace.",
    tags: ["kanban", "planning", "drag-and-drop"]
  },
  {
    name: "Evidence Board",
    folder: "C:\\HTML apps\\evidence-board",
    path: "./evidence-board/index.html",
    collection: "new",
    mode: "file",
    category: "Research Notes",
    summary: "Structured evidence note board with confidence labels, filtering, and JSON export/import.",
    note: "Standalone research-notes app stored in the workspace.",
    tags: ["research", "notes", "export"]
  },
  {
    name: "HTA Pro",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/hta-oman-course.html",
    folder: "C:\\HTML apps\\HTA",
    path: "./HTA/index.html",
    collection: "existing",
    mode: "file",
    category: "Health Technology Assessment",
    summary: "Browser-native Health Technology Assessment workspace covering cost-effectiveness, decision analysis, and benchmark comparisons against TreeAge.",
    note: "Large single-file app (7K+ lines) — opens directly from the file system.",
    tags: ["hta", "cost-effectiveness", "decision-analysis"]
  },
  {
    name: "IPD Meta-Pro",
    subcategory: "Pooling",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/ipd-meta-analysis-course.html",
    folder: "C:\\HTML apps\\IPD-Meta-Pro",
    path: "./IPD-Meta-Pro/ipd-meta-pro.html",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Individual Participant Data meta-analysis in a single distributable HTML artifact with PLOS ONE and F1000 submission packages.",
    note: "The real app is ipd-meta-pro.html; the index.html file is a thin stub.",
    tags: ["ipd", "meta-analysis", "individual-participant-data"]
  },
  {
    name: "Pairwise AI",
    subcategory: "Pooling",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/meta-analysis-methods-course.html",
    folder: "C:\\HTML apps\\Pairwiseai",
    path: "./Pairwiseai/main-screen.html",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Pairwise meta-analysis AI variant with a dedicated main-screen entry, expert-review tracker, and external validation plan.",
    note: "Companion to TruthCert Pairwise Pro — no dedicated index.html, entry is 'main-screen.html'.",
    tags: ["pairwise", "ai", "meta-analysis"]
  },
  {
    name: "Living Meta",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/living-reviews-course.html",
    folder: "C:\\HTML apps\\living-meta",
    path: "./living-meta/living-meta-complete.html",
    collection: "existing",
    mode: "file",
    category: "Living Meta-Analysis",
    summary: "Self-contained living meta-analysis browser bundle with CI/container deployment scaffolding and WASM acceleration.",
    note: "Real app is living-meta-complete.html; the index.html file is a thin stub.",
    tags: ["living-review", "meta-analysis", "wasm"]
  },
  {
    name: "NMA Pro v8",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/advanced-meta-analysis-course.html",
    folder: "C:\\HTML apps\\nma-pro-v2",
    path: "./nma-pro-v2/nma-pro-v8.0.html",
    collection: "existing",
    mode: "file",
    category: "Network Meta-Analysis",
    summary: "Network meta-analysis workbench v8.0 with accessibility hardening, R benchmark harness, and rapid-review workflow.",
    note: "Real app is nma-pro-v8.0.html; index.html is a thin stub.",
    tags: ["nma", "network-meta-analysis", "accessibility"]
  },
  {
    name: "NMA Dose-Response",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/advanced-meta-analysis-course.html",
    folder: "C:\\HTML apps\\nma-dose-response-app",
    path: "./nma-dose-response-app/index.html",
    collection: "existing",
    mode: "file",
    category: "Network Meta-Analysis",
    summary: "Network meta-analysis for dose-response data, with 40+ novel methods and RSM editorial revisions.",
    note: "Full-featured single-file app; test files live at the app root rather than in a tests/ folder.",
    tags: ["nma", "dose-response", "novel-methods"]
  },
  {
    name: "PRISMA Flow",
    subcategory: "Reporting",
    featured: true,
    course: "https://mahmood726-cyber.github.io/synthesis-courses/meta-analysis-writing-course.html",
    folder: "C:\\HTML apps\\prisma-flow",
    path: "./prisma-flow/index.html",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "PRISMA 2020 flow-diagram generator: enter record counts, render an SVG flow diagram, export as SVG or PNG, save state to localStorage.",
    note: "Single-file HTML, offline, deterministic output, built-in consistency checks.",
    tags: ["prisma", "systematic-review", "flow-diagram"]
  },
  {
    name: "Forest Plot Viewer",
    subcategory: "Pooling",
    featured: true,
    course: "https://mahmood726-cyber.github.io/synthesis-courses/synthesis-course.html",
    folder: "C:\\HTML apps\\forest-plot",
    path: "./forest-plot/index.html",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Standalone forest plot from pasted (label, estimate, SE) studies. Fixed-effect and Paule-Mandel random-effects pooling with I\u00b2 and \u03c4\u00b2.",
    note: "Single-file HTML, offline, no dependencies. SVG / PNG / JSON export.",
    tags: ["forest-plot", "meta-analysis", "pooling"]
  },
  {
    name: "Funnel Plot Explorer",
    subcategory: "Publication bias",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/publication-bias-detective.html",
    folder: "C:\\HTML apps\\funnel-plot",
    path: "./funnel-plot/index.html",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Funnel plot with 95% and 99% pseudo-CI limits plus Egger's regression test for small-study effects (p-value via incomplete-beta t-distribution).",
    note: "Validated against scipy / statsmodels OLS. Low-k warning below 10 studies.",
    tags: ["funnel-plot", "publication-bias", "egger"]
  },
  {
    name: "RoB Traffic Light",
    subcategory: "Reporting",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/risk-of-bias-mastery-course.html",
    folder: "C:\\HTML apps\\rob-traffic-light",
    path: "./rob-traffic-light/index.html",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Risk-of-bias traffic-light plot plus weighted summary bar, robvis-style palette. Accepts low / some / high / unclear / na ratings in several shorthand forms.",
    note: "Matrix grid + weighted-summary view, SVG / PNG / JSON export, offline.",
    tags: ["risk-of-bias", "rob2", "robvis"]
  },
  {
    name: "Heterogeneity Explorer",
    subcategory: "Heterogeneity",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/synthesis-course.html",
    folder: "C:\\HTML apps\\heterogeneity",
    path: "./heterogeneity/index.html",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Q, I\u00b2, \u03c4\u00b2 under DL (k\u226510) / REML / PM, 95% prediction interval via t_{k-2}, Baujat diagnostic plot, and leave-one-out influence.",
    note: "Follows advanced-stats.md gates (no DL for k<10). SVG / PNG / JSON export.",
    tags: ["heterogeneity", "baujat", "prediction-interval"]
  },
  {
    name: "TSA Calculator",
    subcategory: "Sensitivity",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/cast-when-certainty-kills.html",
    folder: "C:\\HTML apps\\tsa",
    path: "./tsa/index.html",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Trial sequential analysis: cumulative Z-score plotted against O'Brien-Fleming alpha-spending boundaries with diversity-adjusted Required Information Size.",
    note: "Auto-RIS from target effect and power, or manual in inverse-variance units.",
    tags: ["tsa", "alpha-spending", "obrien-fleming"]
  },
  {
    name: "GRADE SoF Builder",
    subcategory: "Reporting",
    featured: true,
    course: "https://mahmood726-cyber.github.io/synthesis-courses/grade-certainty-course.html",
    folder: "C:\\HTML apps\\grade-sof",
    path: "./grade-sof/index.html",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Cochrane-style Summary of Findings table: outcomes, assumed and corresponding risk, relative effect, participants, four-tier GRADE certainty.",
    note: "Print-ready HTML export with standalone styles. JSON import/export.",
    tags: ["grade", "sof", "certainty-of-evidence"]
  },
  {
    name: "DTA SROC Explorer",
    subcategory: "Reporting",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/dta-course-when-the-test-lies-v4.html",
    folder: "C:\\HTML apps\\dta-sroc",
    path: "./dta-sroc/index.html",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Diagnostic test accuracy: per-study Se/Sp in ROC space, Moses SROC curve, and threshold-effect flag via Spearman \u03c1 between logit(Se) and logit(1-Sp).",
    note: "Applies +0.5 continuity correction only when a cell is zero (advanced-stats.md).",
    tags: ["dta", "sroc", "moses"]
  },
  {
    name: "MA Workbench",
    subcategory: "Pooling",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/synthesis-course.html",
    folder: "C:\\HTML apps\\workbench",
    path: "./workbench/index.html",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "One paste, full MA: live forest / funnel / heterogeneity / TSA previews with deep-links to dedicated apps. One-click full HTML report export.",
    note: "Writes to the shared ma-studies-v1 bus so the other apps can pull.",
    tags: ["workbench", "integrator", "bus"]
  },
  {
    name: "Meta-Regression",
    subcategory: "Heterogeneity",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/meta-analysis-methods-course.html",
    folder: "C:\\HTML apps\\meta-regression",
    path: "./meta-regression/index.html",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Random-effects meta-regression with one moderator. Paule-Mandel \u03c4\u00b2, Knapp-Hartung t(k-2) CIs with max(1, \u2026) HKSJ floor.",
    note: "Bus-aware; exports a metafor R script for PM + knha replication.",
    tags: ["meta-regression", "knapp-hartung", "moderator"]
  },
  {
    name: "Cumulative + Subgroup",
    subcategory: "Sensitivity",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/meta-analysis-methods-course.html",
    folder: "C:\\HTML apps\\cumulative-subgroup",
    path: "./cumulative-subgroup/index.html",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Cumulative MA over study order/year; subgroup analysis with between-subgroup Q test and I\u00b2 of differences.",
    note: "Two views in one app. Reads from and writes to the shared bus.",
    tags: ["cumulative", "subgroup", "temporal"]
  },
  {
    name: "WebR Validator",
    subcategory: "Sensitivity",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/becoming-methodologist.html",
    folder: "C:\\HTML apps\\webr-validator",
    path: "./webr-validator/index.html",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Optional in-browser R (WebR) validation against metafor. Alternative paste-back path for local R. HMAC-SHA256 signed TruthCert receipts.",
    note: "WebR loads on explicit click (~30 MB download). URL configurable for self-hosting. Signing key never stored.",
    tags: ["webr", "validation", "truthcert", "hmac"]
  },
  {
    name: "Bayesian MA",
    subcategory: "Pooling",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/advanced-meta-analysis-course.html",
    folder: "C:\\HTML apps\\bayesian-ma",
    path: "./bayesian-ma/index.html",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Conjugate normal-normal Bayesian meta-analysis: closed-form posterior for \u03b8 given studies and a normal prior; 95% CrI, P(\u03b8<c), ROPE probability, prior-sensitivity slider.",
    note: "No MCMC, no stan, no external deps. Deterministic. Bus-aware.",
    tags: ["bayesian", "conjugate", "posterior"]
  },
  {
    name: "PRISMA Screening",
    subcategory: "Reporting",
    course: "https://mahmood726-cyber.github.io/synthesis-courses/meta-sprint-course.html",
    folder: "C:\\HTML apps\\prisma-screen",
    path: "./prisma-screen/index.html",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Pre-MA citation screening: tag include/exclude/duplicate/maybe, Cohen's \u03ba for dual-reviewer agreement, PRISMA-shaped count roll-up, one-click push into the PRISMA Flow generator.",
    note: "Outputs feed directly into prisma-flow/index.html via the prisma-flow-v1 key.",
    tags: ["prisma", "screening", "kappa"]
  }
];
